/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:49.1-68.10" *)
module ALU_adder_16b(Sign, Zero, Parity, Overflow, Co, Sum, A, B, Cin);
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:52.16-52.20" *)
  output Sign;
  wire Sign;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:52.21-52.25" *)
  output Zero;
  wire Zero;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:52.26-52.32" *)
  output Parity;
  wire Parity;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:52.33-52.41" *)
  output Overflow;
  wire Overflow;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:51.16-51.18" *)
  output Co;
  wire Co;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:50.22-50.25" *)
  output [15:0] Sum;
  wire [15:0] Sum;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:53.21-53.22" *)
  input [15:0] A;
  wire [15:0] A;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:54.21-54.22" *)
  input [15:0] B;
  wire [15:0] B;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:55.15-55.18" *)
  input Cin;
  wire Cin;
  wire [3:0] _00_;
  wire [1:0] _01_;
  wire [7:0] _02_;
  wire [3:0] _03_;
  wire [1:0] _04_;
  wire _05_;
  wire [7:0] _06_;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.53-66.69" *)
  wire _07_;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.53-66.80" *)
  wire _08_;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.21-66.35" *)
  wire _09_;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.21-66.47" *)
  wire _10_;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.53-66.59" *)
  wire _11_;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.63-66.69" *)
  wire _12_;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.39-66.47" *)
  wire _13_;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)
  wire _14_;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:56.9-56.11" *)
  wire c1;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:56.12-56.14" *)
  wire c2;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:56.15-56.17" *)
  wire c3;
  assign _06_[6] = Sum[12] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  Sum[13];
  assign _06_[7] = Sum[14] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  Sum[15];
  assign _00_[0] = _06_[0] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  _06_[1];
  assign _00_[1] = _06_[2] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  _06_[3];
  assign _00_[2] = _06_[4] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  _06_[5];
  assign _00_[3] = _06_[6] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  _06_[7];
  assign _01_[0] = _00_[0] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  _00_[1];
  assign _01_[1] = _00_[2] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  _00_[3];
  assign _14_ = _01_[0] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  _01_[1];
  assign _02_[0] = Sum[0] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  Sum[1];
  assign _02_[1] = Sum[2] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  Sum[3];
  assign _02_[2] = Sum[4] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  Sum[5];
  assign _02_[3] = Sum[6] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  Sum[7];
  assign _02_[4] = Sum[8] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  Sum[9];
  assign _02_[5] = Sum[10] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  Sum[11];
  assign _02_[6] = Sum[12] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  Sum[13];
  assign _02_[7] = Sum[14] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  Sum[15];
  assign _03_[0] = _02_[0] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  _02_[1];
  assign _03_[1] = _02_[2] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  _02_[3];
  assign _03_[2] = _02_[4] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  _02_[5];
  assign _03_[3] = _02_[6] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  _02_[7];
  assign _04_[0] = _03_[0] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  _03_[1];
  assign _04_[1] = _03_[2] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  _03_[3];
  assign _05_ = _04_[0] ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *)  _04_[1];
  assign _06_[0] = Sum[0] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  Sum[1];
  assign _06_[1] = Sum[2] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  Sum[3];
  assign _06_[2] = Sum[4] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  Sum[5];
  assign _06_[3] = Sum[6] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  Sum[7];
  assign _06_[4] = Sum[8] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  Sum[9];
  assign _06_[5] = Sum[10] |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *)  Sum[11];
  assign Parity = ~(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:65.19-65.24" *) _05_;
  assign Zero = ~(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:64.17-64.22" *) _14_;
  assign _13_ = ~(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.39-66.47" *) Sum[15];
  assign _11_ = ~(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.53-66.59" *) A[15];
  assign _12_ = ~(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.63-66.69" *) B[15];
  assign _09_ = A[15] &(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.21-66.35" *)  B[15];
  assign _10_ = _09_ &(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.21-66.47" *)  _13_;
  assign _07_ = _11_ &(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.53-66.69" *)  _12_;
  assign _08_ = _07_ &(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.53-66.80" *)  Sum[15];
  assign Overflow = _10_ |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:66.20-66.81" *)  _08_;
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:58.12-58.45" *)
  adder_4b A1 (
    .A(A[3:0]),
    .B(B[3:0]),
    .Cin(Cin),
    .Co(c1),
    .Sum(Sum[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:59.12-59.44" *)
  adder_4b A2 (
    .A(A[7:4]),
    .B(B[7:4]),
    .Cin(c1),
    .Co(c2),
    .Sum(Sum[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:60.12-60.47" *)
  adder_4b A3 (
    .A(A[11:8]),
    .B(B[11:8]),
    .Cin(c2),
    .Co(c3),
    .Sum(Sum[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:61.12-61.50" *)
  adder_4b A4 (
    .A(A[15:12]),
    .B(B[15:12]),
    .Cin(c3),
    .Co(Co),
    .Sum(Sum[15:12])
  );
  assign Sign = Sum[15];
endmodule

(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:2.1-6.10" *)
module AND(F, A, B);
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:3.15-3.16" *)
  output F;
  wire F;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:4.14-4.15" *)
  input A;
  wire A;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:4.16-4.17" *)
  input B;
  wire B;
  assign F = A &(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:5.13-5.19" *)  B;
endmodule

(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:20.1-31.10" *)
module FA(Co, Sum, A, B, Cin);
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:21.20-21.22" *)
  output Co;
  wire Co;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:21.15-21.18" *)
  output Sum;
  wire Sum;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:22.14-22.15" *)
  input A;
  wire A;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:22.17-22.18" *)
  input B;
  wire B;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:22.20-22.23" *)
  input Cin;
  wire Cin;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:23.8-23.10" *)
  wire w1;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:23.11-23.13" *)
  wire w2;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:23.14-23.16" *)
  wire w3;
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:25.7-25.17" *)
  XOR G1 (
    .A(A),
    .B(B),
    .F(w1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:26.7-26.21" *)
  XOR G2 (
    .A(w1),
    .B(Cin),
    .F(Sum)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:27.7-27.17" *)
  AND G3 (
    .A(A),
    .B(B),
    .F(w2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:28.7-28.20" *)
  AND G4 (
    .A(w1),
    .B(Cin),
    .F(w3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:29.6-29.18" *)
  OR G5 (
    .A(w2),
    .B(w3),
    .F(Co)
  );
endmodule

(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:8.1-12.10" *)
module OR(F, A, B);
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:9.15-9.16" *)
  output F;
  wire F;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:10.14-10.15" *)
  input A;
  wire A;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:10.16-10.17" *)
  input B;
  wire B;
  assign F = A |(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:11.13-11.19" *)  B;
endmodule

(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:14.1-18.10" *)
module XOR(F, A, B);
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:15.15-15.16" *)
  output F;
  wire F;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:16.14-16.15" *)
  input A;
  wire A;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:16.16-16.17" *)
  input B;
  wire B;
  assign F = A ^(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:17.13-17.18" *)  B;
endmodule

(* src = "./ALU_Adder/ALU_Adder_16_bit.sv:34.1-47.10" *)
module adder_4b(Co, Sum, A, B, Cin);
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:36.15-36.17" *)
  output Co;
  wire Co;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:35.20-35.23" *)
  output [3:0] Sum;
  wire [3:0] Sum;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:37.20-37.21" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:38.20-38.21" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:39.15-39.18" *)
  input Cin;
  wire Cin;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:40.9-40.11" *)
  wire c1;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:40.12-40.14" *)
  wire c2;
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:40.15-40.17" *)
  wire c3;
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:42.6-42.34" *)
  FA FA1 (
    .A(A[0]),
    .B(B[0]),
    .Cin(Cin),
    .Co(c1),
    .Sum(Sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:43.6-43.33" *)
  FA FA2 (
    .A(A[1]),
    .B(B[1]),
    .Cin(c1),
    .Co(c2),
    .Sum(Sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:44.6-44.33" *)
  FA FA3 (
    .A(A[2]),
    .B(B[2]),
    .Cin(c2),
    .Co(c3),
    .Sum(Sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./ALU_Adder/ALU_Adder_16_bit.sv:45.6-45.33" *)
  FA FA4 (
    .A(A[3]),
    .B(B[3]),
    .Cin(c3),
    .Co(Co),
    .Sum(Sum[3])
  );
endmodule
