/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./APB_Master/apb_2.sv:10.1-111.10" *)
module apb_2(clk, rst, cmd_i, psel_o, penable_o, paddr_o, pwrite_o, pwdata_o, pready_i, prdata_i);
  (* src = "./APB_Master/apb_2.sv:11.28-11.31" *)
  input clk;
  wire clk;
  (* src = "./APB_Master/apb_2.sv:12.28-12.31" *)
  input rst;
  wire rst;
  (* src = "./APB_Master/apb_2.sv:14.28-14.33" *)
  input [1:0] cmd_i;
  wire [1:0] cmd_i;
  (* src = "./APB_Master/apb_2.sv:16.28-16.34" *)
  output psel_o;
  wire psel_o;
  (* src = "./APB_Master/apb_2.sv:17.28-17.37" *)
  output penable_o;
  wire penable_o;
  (* src = "./APB_Master/apb_2.sv:18.28-18.35" *)
  output [31:0] paddr_o;
  wire [31:0] paddr_o;
  (* src = "./APB_Master/apb_2.sv:19.28-19.36" *)
  output pwrite_o;
  wire pwrite_o;
  (* src = "./APB_Master/apb_2.sv:20.28-20.36" *)
  output [31:0] pwdata_o;
  wire [31:0] pwdata_o;
  (* src = "./APB_Master/apb_2.sv:21.28-21.36" *)
  input pready_i;
  wire pready_i;
  (* src = "./APB_Master/apb_2.sv:22.28-22.36" *)
  input [31:0] prdata_i;
  wire [31:0] prdata_i;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire [1:0] _019_;
  wire [1:0] _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  (* src = "./APB_Master/apb_2.sv:85.20-85.34" *)
  wire _024_;
  (* src = "./APB_Master/apb_2.sv:85.38-85.52" *)
  wire _025_;
  (* src = "./APB_Master/apb_2.sv:48.14-48.41" *)
  wire _026_;
  (* src = "./APB_Master/apb_2.sv:92.32-92.56" *)
  wire _027_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:579.28-579.29" *)
  wire [5:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:591.28-591.35" *)
  wire [5:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:581.22-581.23" *)
  wire [2:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:586.19-586.22" *)
  wire [1:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:579.28-579.29" *)
  wire [1:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:591.28-591.35" *)
  wire [1:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:586.19-586.22" *)
  wire [0:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:579.28-579.29" *)
  wire [1:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:591.28-591.35" *)
  wire [1:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:586.19-586.22" *)
  wire [0:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "31" *)
  wire [31:0] _038_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:287.21-287.22" *)
  wire [31:0] _039_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:270.26-270.27" *)
  wire [31:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_2.sv:96.32-96.66|./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:268.22-268.23" *)
  wire [31:0] _041_;
  (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:605.13-605.15" *)
  wire _042_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _043_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _044_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _045_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _046_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _047_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _048_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _049_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _050_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _051_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _052_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _053_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _054_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _055_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _056_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _057_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _058_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _059_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _060_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _061_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _062_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _063_;
  (* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _064_;
  (* src = "./APB_Master/apb_2.sv:94.31-94.73" *)
  wire [31:0] _065_;
  (* src = "./APB_Master/apb_2.sv:26.16-26.19" *)
  reg [1:0] cmd;
  (* enum_type = "$enum0" *)
  (* enum_value_00 = "\\IDLE" *)
  (* enum_value_01 = "\\SETUP" *)
  (* enum_value_10 = "\\ACCESS" *)
  (* src = "./APB_Master/apb_2.sv:38.20-38.28" *)
  (* wiretype = "\\state" *)
  wire [1:0] nx_state;
  (* src = "./APB_Master/apb_2.sv:29.16-29.21" *)
  wire [31:0] paddr;
  (* src = "./APB_Master/apb_2.sv:28.16-28.23" *)
  reg penable;
  (* src = "./APB_Master/apb_2.sv:28.25-28.36" *)
  wire penable_nxt;
  (* enum_type = "$enum0" *)
  (* enum_value_00 = "\\IDLE" *)
  (* enum_value_01 = "\\SETUP" *)
  (* enum_value_10 = "\\ACCESS" *)
  (* src = "./APB_Master/apb_2.sv:38.11-38.19" *)
  (* wiretype = "\\state" *)
  reg [1:0] pr_state;
  (* src = "./APB_Master/apb_2.sv:27.16-27.20" *)
  reg psel;
  (* src = "./APB_Master/apb_2.sv:27.22-27.30" *)
  wire psel_nxt;
  (* src = "./APB_Master/apb_2.sv:31.16-31.22" *)
  reg [31:0] pwdata;
  (* src = "./APB_Master/apb_2.sv:30.16-30.22" *)
  reg pwrite;
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[0] <= 1'h0;
    else if (_006_) pwdata[0] <= _065_[0];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[1] <= 1'h0;
    else if (_006_) pwdata[1] <= _065_[1];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[2] <= 1'h0;
    else if (_006_) pwdata[2] <= _065_[2];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[3] <= 1'h0;
    else if (_006_) pwdata[3] <= _065_[3];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[4] <= 1'h0;
    else if (_006_) pwdata[4] <= _065_[4];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[5] <= 1'h0;
    else if (_006_) pwdata[5] <= _065_[5];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[6] <= 1'h0;
    else if (_006_) pwdata[6] <= _065_[6];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[7] <= 1'h0;
    else if (_006_) pwdata[7] <= _065_[7];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[8] <= 1'h0;
    else if (_006_) pwdata[8] <= _065_[8];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[9] <= 1'h0;
    else if (_006_) pwdata[9] <= _065_[9];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[10] <= 1'h0;
    else if (_006_) pwdata[10] <= _065_[10];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[11] <= 1'h0;
    else if (_006_) pwdata[11] <= _065_[11];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[12] <= 1'h0;
    else if (_006_) pwdata[12] <= _065_[12];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[13] <= 1'h0;
    else if (_006_) pwdata[13] <= _065_[13];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[14] <= 1'h0;
    else if (_006_) pwdata[14] <= _065_[14];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[15] <= 1'h0;
    else if (_006_) pwdata[15] <= _065_[15];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[16] <= 1'h0;
    else if (_006_) pwdata[16] <= _065_[16];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[17] <= 1'h0;
    else if (_006_) pwdata[17] <= _065_[17];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[18] <= 1'h0;
    else if (_006_) pwdata[18] <= _065_[18];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[19] <= 1'h0;
    else if (_006_) pwdata[19] <= _065_[19];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[20] <= 1'h0;
    else if (_006_) pwdata[20] <= _065_[20];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[21] <= 1'h0;
    else if (_006_) pwdata[21] <= _065_[21];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[22] <= 1'h0;
    else if (_006_) pwdata[22] <= _065_[22];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[23] <= 1'h0;
    else if (_006_) pwdata[23] <= _065_[23];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[24] <= 1'h0;
    else if (_006_) pwdata[24] <= _065_[24];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[25] <= 1'h0;
    else if (_006_) pwdata[25] <= _065_[25];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[26] <= 1'h0;
    else if (_006_) pwdata[26] <= _065_[26];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[27] <= 1'h0;
    else if (_006_) pwdata[27] <= _065_[27];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[28] <= 1'h0;
    else if (_006_) pwdata[28] <= _065_[28];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[29] <= 1'h0;
    else if (_006_) pwdata[29] <= _065_[29];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[30] <= 1'h0;
    else if (_006_) pwdata[30] <= _065_[30];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwdata[31] <= 1'h0;
    else if (_006_) pwdata[31] <= _065_[31];
  reg \paddr_reg[0] ;
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \paddr_reg[0]  <= 1'h0;
    else if (_006_) \paddr_reg[0]  <= _041_[0];
  assign paddr[0] = \paddr_reg[0] ;
  reg \paddr_reg[30] ;
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \paddr_reg[30]  <= 1'h0;
    else if (_006_) \paddr_reg[30]  <= 1'h1;
  assign paddr[30] = \paddr_reg[30] ;
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwrite <= 1'h1;
    else if (_006_) pwrite <= _041_[0];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) psel <= 1'h0;
    else if (_005_) psel <= psel_nxt;
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[0] <= 1'h0;
    else if (_004_) pr_state[0] <= nx_state[0];
  (* src = "./APB_Master/apb_2.sv:56.3-73.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[1] <= 1'h0;
    else if (_004_) pr_state[1] <= nx_state[1];
  (* src = "./APB_Master/apb_2.sv:46.3-49.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) cmd[0] <= 1'h0;
    else if (_026_) cmd[0] <= cmd_i[0];
  (* src = "./APB_Master/apb_2.sv:46.3-49.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) cmd[1] <= 1'h0;
    else if (_026_) cmd[1] <= cmd_i[1];
  (* src = "./APB_Master/apb_2.sv:51.3-54.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) penable <= 1'h1;
    else if (_000_) penable <= penable_nxt;
  assign _007_ = ~cmd[1];
  assign _039_[0] = ~prdata_i[0];
  assign _009_ = ~pr_state[0];
  assign _010_ = ~pr_state[1];
  assign _011_ = ~cmd_i[0];
  assign _012_ = ~cmd_i[1];
  assign _015_ = ~_028_[0];
  assign _038_[10] = prdata_i[10] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[9];
  assign _038_[8] = prdata_i[8] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[7];
  assign _038_[6] = prdata_i[6] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[5];
  assign _038_[20] = prdata_i[20] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[19];
  assign _038_[4] = prdata_i[4] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[3];
  assign _038_[2] = prdata_i[2] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[1];
  assign _038_[29] = _056_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[27];
  assign _038_[22] = prdata_i[22] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[21];
  assign _038_[25] = _054_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[23];
  assign _038_[21] = _052_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[19];
  assign _038_[14] = prdata_i[14] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[13];
  assign _038_[17] = _050_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[15];
  assign _038_[24] = prdata_i[24] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[23];
  assign _038_[13] = _048_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[11];
  assign _038_[9] = _046_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[7];
  assign _038_[16] = prdata_i[16] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[15];
  assign _038_[5] = _044_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[3];
  assign _038_[26] = prdata_i[26] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[25];
  assign _038_[27] = _062_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[23];
  assign _038_[19] = _060_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[15];
  assign _038_[11] = _058_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[7];
  assign _038_[28] = prdata_i[28] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[27];
  assign _038_[23] = _064_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[15];
  assign _038_[12] = prdata_i[12] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[11];
  assign _038_[15] = _063_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _038_[7];
  assign _064_ = _061_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _060_;
  assign _063_ = _059_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _058_;
  assign _038_[30] = prdata_i[30] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[29];
  assign _038_[7] = _057_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _038_[3];
  assign _062_ = _055_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _054_;
  assign _061_ = _053_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _052_;
  assign _060_ = _051_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _050_;
  assign _059_ = _049_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _048_;
  assign _058_ = _047_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _046_;
  assign _057_ = _045_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _044_;
  assign _038_[3] = _043_ &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _038_[1];
  assign _056_ = prdata_i[29] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[28];
  assign _055_ = prdata_i[27] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[26];
  assign _054_ = prdata_i[25] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[24];
  assign _053_ = prdata_i[23] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[22];
  assign _052_ = prdata_i[21] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[20];
  assign _051_ = prdata_i[19] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[18];
  assign _050_ = prdata_i[17] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[16];
  assign _049_ = prdata_i[15] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[14];
  assign _048_ = prdata_i[13] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[12];
  assign _047_ = prdata_i[11] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[10];
  assign _046_ = prdata_i[9] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[8];
  assign _045_ = prdata_i[7] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[6];
  assign _044_ = prdata_i[5] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[4];
  assign _043_ = prdata_i[3] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  prdata_i[2];
  assign _038_[18] = prdata_i[18] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _038_[17];
  assign _038_[1] = prdata_i[1] &(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  prdata_i[0];
  assign _020_[0] = cmd_i[0] ^(* src = "./APB_Master/apb_2.sv:102.24-102.36" *)  cmd[0];
  assign _020_[1] = cmd_i[1] ^(* src = "./APB_Master/apb_2.sv:102.24-102.36" *)  cmd[1];
  assign _029_[4] = _028_[4] &(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:593.44-593.84" *)  _030_[2];
  assign _029_[5] = _028_[5] &(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:593.44-593.84" *)  _030_[2];
  assign _029_[0] = _028_[0] &(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:593.44-593.84" *)  _030_[0];
  assign _033_[1] = _032_[1] &(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:593.44-593.84" *)  _029_[3];
  assign _036_[0] = _035_[0] &(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:593.44-593.84" *)  _030_[0];
  assign _040_[1] = prdata_i[1] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  prdata_i[0];
  assign _040_[2] = prdata_i[2] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[1];
  assign _040_[3] = prdata_i[3] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[2];
  assign _040_[4] = prdata_i[4] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[3];
  assign _040_[5] = prdata_i[5] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[4];
  assign _040_[6] = prdata_i[6] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[5];
  assign _040_[7] = prdata_i[7] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[6];
  assign _040_[8] = prdata_i[8] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[7];
  assign _040_[9] = prdata_i[9] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[8];
  assign _040_[10] = prdata_i[10] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[9];
  assign _040_[11] = prdata_i[11] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[10];
  assign _040_[12] = prdata_i[12] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[11];
  assign _040_[13] = prdata_i[13] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[12];
  assign _040_[14] = prdata_i[14] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[13];
  assign _040_[15] = prdata_i[15] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[14];
  assign _040_[16] = prdata_i[16] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[15];
  assign _040_[17] = prdata_i[17] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[16];
  assign _040_[18] = prdata_i[18] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[17];
  assign _040_[19] = prdata_i[19] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[18];
  assign _040_[20] = prdata_i[20] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[19];
  assign _040_[21] = prdata_i[21] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[20];
  assign _040_[22] = prdata_i[22] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[21];
  assign _040_[23] = prdata_i[23] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[22];
  assign _040_[24] = prdata_i[24] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[23];
  assign _040_[25] = prdata_i[25] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[24];
  assign _040_[26] = prdata_i[26] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[25];
  assign _040_[27] = prdata_i[27] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[26];
  assign _040_[28] = prdata_i[28] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[27];
  assign _040_[29] = prdata_i[29] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[28];
  assign _040_[30] = prdata_i[30] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[29];
  assign _040_[31] = prdata_i[31] ^(* src = "./APB_Master/apb_2.sv:94.52-94.68|/share/techmap.v:296.13-296.25" *)  _038_[30];
  assign _006_ = pready_i & _029_[3];
  assign _016_ = _003_ & _000_;
  assign _005_ = _016_ & pready_i;
  assign _003_ = _015_ | _014_;
  assign _017_ = _002_ & _001_;
  assign _004_ = _017_ & pready_i;
  assign _018_ = _030_[0] | _030_[2];
  assign _002_ = _018_ | _029_[3];
  assign _001_ = _019_[0] | _013_;
  assign _021_ = cmd_i[0] |(* src = "./APB_Master/apb_2.sv:85.20-85.34" *)  _012_;
  assign _022_ = _011_ |(* src = "./APB_Master/apb_2.sv:85.38-85.52" *)  cmd_i[1];
  assign _008_ = cmd[0] |(* src = "./APB_Master/apb_2.sv:93.32-93.44" *)  _007_;
  assign _028_[0] = _020_[0] |(* src = "./APB_Master/apb_2.sv:102.24-102.36" *)  _020_[1];
  assign _014_ = pr_state[0] |(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14" *)  _010_;
  assign _023_ = _009_ |(* src = "./APB_Master/apb_2.sv:88.16-88.16|./APB_Master/apb_2.sv:83.5-109.14" *)  pr_state[1];
  assign _031_[1] = _029_[3] |(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:601.20-601.31" *)  _029_[5];
  assign _031_[0] = _029_[0] |(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:601.20-601.31" *)  _029_[4];
  assign _000_ = _030_[0] |(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:605.13-605.15" *)  _029_[3];
  assign _042_ = _000_ |(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:605.13-605.15" *)  _030_[2];
  assign _034_ = _030_[0] |(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:601.20-601.31" *)  _033_[1];
  assign _037_ = _036_[0] |(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:601.20-601.31" *)  _029_[3];
  assign _013_ = pr_state[0] |(* src = "./APB_Master/apb_2.sv:83.20-83.20|./APB_Master/apb_2.sv:83.5-109.14" *)  pr_state[1];
  assign _024_ = ~(* src = "./APB_Master/apb_2.sv:85.20-85.34" *) _021_;
  assign _025_ = ~(* src = "./APB_Master/apb_2.sv:85.38-85.52" *) _022_;
  assign _041_[0] = ~(* src = "./APB_Master/apb_2.sv:96.49-96.65" *) _008_;
  assign _030_[2] = ~(* src = "./APB_Master/apb_2.sv:83.20-83.20|./APB_Master/apb_2.sv:83.5-109.14" *) _013_;
  assign _030_[0] = ~(* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14" *) _014_;
  assign _029_[3] = ~(* src = "./APB_Master/apb_2.sv:88.16-88.16|./APB_Master/apb_2.sv:83.5-109.14" *) _023_;
  assign _026_ = pready_i &(* src = "./APB_Master/apb_2.sv:48.14-48.41" *)  _023_;
  assign _019_[0] = _024_ |(* src = "./APB_Master/apb_2.sv:85.20-85.52" *)  _025_;
  assign _027_ = penable &(* src = "./APB_Master/apb_2.sv:92.32-92.56" *)  pready_i;
  assign _032_[1] = ~(* src = "./APB_Master/apb_2.sv:92.31-92.67" *) _027_;
  assign _065_[0] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _039_[0];
  assign _065_[1] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[1];
  assign _065_[2] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[2];
  assign _065_[3] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[3];
  assign _065_[4] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[4];
  assign _065_[5] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[5];
  assign _065_[6] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[6];
  assign _065_[7] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[7];
  assign _065_[8] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[8];
  assign _065_[9] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[9];
  assign _065_[10] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[10];
  assign _065_[11] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[11];
  assign _065_[12] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[12];
  assign _065_[13] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[13];
  assign _065_[14] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[14];
  assign _065_[15] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[15];
  assign _065_[16] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[16];
  assign _065_[17] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[17];
  assign _065_[18] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[18];
  assign _065_[19] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[19];
  assign _065_[20] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[20];
  assign _065_[21] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[21];
  assign _065_[22] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[22];
  assign _065_[23] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[23];
  assign _065_[24] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[24];
  assign _065_[25] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[25];
  assign _065_[26] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[26];
  assign _065_[27] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[27];
  assign _065_[28] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[28];
  assign _065_[29] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[29];
  assign _065_[30] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[30];
  assign _065_[31] = _008_ ? (* src = "./APB_Master/apb_2.sv:94.31-94.73" *) 1'h0 : _040_[31];
  assign _035_[0] = _028_[0] ? (* src = "./APB_Master/apb_2.sv:102.24-102.36|./APB_Master/apb_2.sv:102.20-106.23" *) 1'hx : 1'h0;
  assign _028_[4] = _019_[0] ? (* src = "./APB_Master/apb_2.sv:85.20-85.52|./APB_Master/apb_2.sv:85.16-87.19" *) 1'h1 : 1'hx;
  assign _028_[5] = _019_[0] ? (* src = "./APB_Master/apb_2.sv:85.20-85.52|./APB_Master/apb_2.sv:85.16-87.19" *) 1'h0 : 1'hx;
  assign nx_state[0] = _042_ ? (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:605.13-605.25" *) _031_[0] : 1'hx;
  assign nx_state[1] = _042_ ? (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:605.13-605.25" *) _031_[1] : 1'hx;
  assign penable_nxt = _000_ ? (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:605.13-605.25" *) _034_ : 1'hx;
  assign psel_nxt = _000_ ? (* src = "./APB_Master/apb_2.sv:97.18-97.18|./APB_Master/apb_2.sv:83.5-109.14|/share/techmap.v:605.13-605.25" *) _037_ : 1'hx;
  assign _036_[1] = _029_[3];
  assign _040_[0] = _039_[0];
  assign _032_[0] = 1'h1;
  assign _038_[0] = prdata_i[0];
  assign _033_[0] = _030_[0];
  assign _041_[31:1] = 31'h00000000;
  assign _039_[31:1] = prdata_i[31:1];
  assign _019_[1] = _013_;
  assign _028_[3:1] = 3'h4;
  assign _030_[1] = _029_[3];
  assign _029_[2:1] = 2'h0;
  assign _035_[1] = 1'h1;
  assign { paddr[31], paddr[29:1] } = { paddr[30], 1'h0, paddr[30], paddr[30], paddr[30], paddr[30], 1'h0, paddr[30], 1'h0, paddr[30], 1'h0, paddr[30], paddr[30], 1'h0, paddr[30], paddr[30], paddr[30], 2'h0, paddr[30], 1'h0, paddr[30], 1'h0, paddr[30], paddr[30], paddr[30], paddr[30], paddr[30], paddr[30], paddr[30] };
  assign pwdata_o = pwdata;
  assign pwrite_o = pwrite;
  assign paddr_o = { paddr[30], paddr[30], 1'h0, paddr[30], paddr[30], paddr[30], paddr[30], 1'h0, paddr[30], 1'h0, paddr[30], 1'h0, paddr[30], paddr[30], 1'h0, paddr[30], paddr[30], paddr[30], 2'h0, paddr[30], 1'h0, paddr[30], 1'h0, paddr[30], paddr[30], paddr[30], paddr[30], paddr[30], paddr[30], paddr[30], paddr[0] };
  assign penable_o = penable;
  assign psel_o = psel;
endmodule
