/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./APB_Master/apb_1.sv:25.1-121.10" *)
module apb_1(event_a_i, event_b_i, event_c_i, clk, rst, psel_o, penable_o, paddr_o, pwrite_o, pwdata_o, pready_i);
  (* src = "./APB_Master/apb_1.sv:27.25-27.34" *)
  input event_a_i;
  wire event_a_i;
  (* src = "./APB_Master/apb_1.sv:28.25-28.34" *)
  input event_b_i;
  wire event_b_i;
  (* src = "./APB_Master/apb_1.sv:29.25-29.34" *)
  input event_c_i;
  wire event_c_i;
  (* src = "./APB_Master/apb_1.sv:31.28-31.31" *)
  input clk;
  wire clk;
  (* src = "./APB_Master/apb_1.sv:32.28-32.31" *)
  input rst;
  wire rst;
  (* src = "./APB_Master/apb_1.sv:34.28-34.34" *)
  output psel_o;
  wire psel_o;
  (* src = "./APB_Master/apb_1.sv:35.28-35.37" *)
  output penable_o;
  wire penable_o;
  (* src = "./APB_Master/apb_1.sv:36.28-36.35" *)
  output [31:0] paddr_o;
  wire [31:0] paddr_o;
  (* src = "./APB_Master/apb_1.sv:37.28-37.36" *)
  output pwrite_o;
  wire pwrite_o;
  (* src = "./APB_Master/apb_1.sv:38.28-38.36" *)
  output [31:0] pwdata_o;
  wire [31:0] pwdata_o;
  (* src = "./APB_Master/apb_1.sv:39.28-39.36" *)
  input pready_i;
  wire pready_i;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire [15:0] _015_;
  wire [7:0] _016_;
  wire [3:0] _017_;
  wire [1:0] _018_;
  wire [31:0] _019_;
  wire _020_;
  (* src = "./APB_Master/apb_1.sv:106.32-106.66" *)
  wire _021_;
  (* src = "./APB_Master/apb_1.sv:106.32-106.78" *)
  wire _022_;
  (* src = "./APB_Master/apb_1.sv:112.24-112.46" *)
  wire _023_;
  (* src = "./APB_Master/apb_1.sv:106.48-106.66" *)
  wire _024_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:579.28-579.29" *)
  wire [5:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:591.28-591.35" *)
  wire [5:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:581.22-581.23" *)
  wire [2:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:586.19-586.22" *)
  wire [1:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:579.28-579.29" *)
  wire [1:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:591.28-591.35" *)
  wire [1:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:586.19-586.22" *)
  wire [0:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:579.28-579.29" *)
  wire [1:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:591.28-591.35" *)
  wire [1:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:586.19-586.22" *)
  wire [0:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "31" *)
  wire [31:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:287.21-287.22" *)
  wire [31:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:270.26-270.27" *)
  wire [31:0] _037_;
  (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:605.13-605.15" *)
  wire _038_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _039_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _040_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _041_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _042_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _043_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _044_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _045_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _046_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _047_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _048_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _049_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _050_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _051_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _052_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _053_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _054_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _055_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _056_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _057_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _058_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _059_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _060_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _061_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _062_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _063_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _064_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _065_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _066_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _067_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _068_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _069_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _070_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _071_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _072_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _073_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _074_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _075_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _076_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _077_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _078_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _079_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _080_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _081_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _082_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _083_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _084_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _085_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _086_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _087_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _088_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _089_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _090_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _091_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _092_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _093_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _094_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _095_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _096_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _097_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _098_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _099_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _100_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _101_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _102_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _103_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _104_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _105_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _106_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _107_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _108_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _109_;
  (* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _110_;
  (* src = "./APB_Master/apb_1.sv:105.61-105.104" *)
  wire [31:0] _111_;
  (* src = "./APB_Master/apb_1.sv:105.31-105.104" *)
  wire [31:0] _112_;
  (* enum_type = "$enum0" *)
  (* enum_value_00 = "\\IDLE" *)
  (* enum_value_01 = "\\SETUP" *)
  (* enum_value_10 = "\\ACCESS" *)
  (* src = "./APB_Master/apb_1.sv:53.20-53.28" *)
  (* wiretype = "\\state" *)
  wire [1:0] nx_state;
  (* src = "./APB_Master/apb_1.sv:45.16-45.21" *)
  wire [31:0] paddr;
  (* src = "./APB_Master/apb_1.sv:44.16-44.23" *)
  reg penable;
  (* src = "./APB_Master/apb_1.sv:44.25-44.36" *)
  wire penable_nxt;
  (* enum_type = "$enum0" *)
  (* enum_value_00 = "\\IDLE" *)
  (* enum_value_01 = "\\SETUP" *)
  (* enum_value_10 = "\\ACCESS" *)
  (* src = "./APB_Master/apb_1.sv:53.11-53.19" *)
  (* wiretype = "\\state" *)
  reg [1:0] pr_state;
  (* src = "./APB_Master/apb_1.sv:43.16-43.20" *)
  reg psel;
  (* src = "./APB_Master/apb_1.sv:43.22-43.30" *)
  wire psel_nxt;
  (* src = "./APB_Master/apb_1.sv:47.16-47.22" *)
  wire [31:0] pwdata;
  (* src = "./APB_Master/apb_1.sv:46.16-46.22" *)
  reg pwrite;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pwrite <= 1'h0;
    else if (_004_) pwrite <= 1'h1;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) psel <= 1'h0;
    else if (_006_) psel <= psel_nxt;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[0] <= 1'h0;
    else if (_005_) pr_state[0] <= nx_state[0];
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[1] <= 1'h0;
    else if (_005_) pr_state[1] <= nx_state[1];
  reg \pwdata_reg[1] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[1]  <= 1'h0;
    else if (_004_) \pwdata_reg[1]  <= _036_[1];
  assign pwdata[1] = \pwdata_reg[1] ;
  reg \pwdata_reg[2] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[2]  <= 1'h0;
    else if (_004_) \pwdata_reg[2]  <= _037_[2];
  assign pwdata[2] = \pwdata_reg[2] ;
  reg \pwdata_reg[3] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[3]  <= 1'h0;
    else if (_004_) \pwdata_reg[3]  <= _037_[3];
  assign pwdata[3] = \pwdata_reg[3] ;
  reg \pwdata_reg[4] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[4]  <= 1'h0;
    else if (_004_) \pwdata_reg[4]  <= _037_[4];
  assign pwdata[4] = \pwdata_reg[4] ;
  reg \pwdata_reg[5] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[5]  <= 1'h0;
    else if (_004_) \pwdata_reg[5]  <= _037_[5];
  assign pwdata[5] = \pwdata_reg[5] ;
  reg \pwdata_reg[6] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[6]  <= 1'h0;
    else if (_004_) \pwdata_reg[6]  <= _037_[6];
  assign pwdata[6] = \pwdata_reg[6] ;
  reg \pwdata_reg[7] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[7]  <= 1'h0;
    else if (_004_) \pwdata_reg[7]  <= _037_[7];
  assign pwdata[7] = \pwdata_reg[7] ;
  reg \pwdata_reg[8] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[8]  <= 1'h0;
    else if (_004_) \pwdata_reg[8]  <= _037_[8];
  assign pwdata[8] = \pwdata_reg[8] ;
  reg \pwdata_reg[9] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[9]  <= 1'h0;
    else if (_004_) \pwdata_reg[9]  <= _037_[9];
  assign pwdata[9] = \pwdata_reg[9] ;
  reg \pwdata_reg[10] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[10]  <= 1'h0;
    else if (_004_) \pwdata_reg[10]  <= _037_[10];
  assign pwdata[10] = \pwdata_reg[10] ;
  reg \pwdata_reg[11] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[11]  <= 1'h0;
    else if (_004_) \pwdata_reg[11]  <= _037_[11];
  assign pwdata[11] = \pwdata_reg[11] ;
  reg \pwdata_reg[12] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[12]  <= 1'h0;
    else if (_004_) \pwdata_reg[12]  <= _037_[12];
  assign pwdata[12] = \pwdata_reg[12] ;
  reg \pwdata_reg[13] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[13]  <= 1'h0;
    else if (_004_) \pwdata_reg[13]  <= _037_[13];
  assign pwdata[13] = \pwdata_reg[13] ;
  reg \pwdata_reg[14] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[14]  <= 1'h0;
    else if (_004_) \pwdata_reg[14]  <= _037_[14];
  assign pwdata[14] = \pwdata_reg[14] ;
  reg \pwdata_reg[15] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[15]  <= 1'h0;
    else if (_004_) \pwdata_reg[15]  <= _037_[15];
  assign pwdata[15] = \pwdata_reg[15] ;
  reg \pwdata_reg[16] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[16]  <= 1'h0;
    else if (_004_) \pwdata_reg[16]  <= _037_[16];
  assign pwdata[16] = \pwdata_reg[16] ;
  reg \pwdata_reg[17] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[17]  <= 1'h0;
    else if (_004_) \pwdata_reg[17]  <= _037_[17];
  assign pwdata[17] = \pwdata_reg[17] ;
  reg \pwdata_reg[18] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[18]  <= 1'h0;
    else if (_004_) \pwdata_reg[18]  <= _037_[18];
  assign pwdata[18] = \pwdata_reg[18] ;
  reg \pwdata_reg[19] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[19]  <= 1'h0;
    else if (_004_) \pwdata_reg[19]  <= _037_[19];
  assign pwdata[19] = \pwdata_reg[19] ;
  reg \pwdata_reg[20] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[20]  <= 1'h0;
    else if (_004_) \pwdata_reg[20]  <= _037_[20];
  assign pwdata[20] = \pwdata_reg[20] ;
  reg \pwdata_reg[21] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[21]  <= 1'h0;
    else if (_004_) \pwdata_reg[21]  <= _037_[21];
  assign pwdata[21] = \pwdata_reg[21] ;
  reg \pwdata_reg[22] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[22]  <= 1'h0;
    else if (_004_) \pwdata_reg[22]  <= _037_[22];
  assign pwdata[22] = \pwdata_reg[22] ;
  reg \pwdata_reg[23] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[23]  <= 1'h0;
    else if (_004_) \pwdata_reg[23]  <= _037_[23];
  assign pwdata[23] = \pwdata_reg[23] ;
  reg \pwdata_reg[24] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[24]  <= 1'h0;
    else if (_004_) \pwdata_reg[24]  <= _037_[24];
  assign pwdata[24] = \pwdata_reg[24] ;
  reg \pwdata_reg[25] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[25]  <= 1'h0;
    else if (_004_) \pwdata_reg[25]  <= _037_[25];
  assign pwdata[25] = \pwdata_reg[25] ;
  reg \pwdata_reg[26] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[26]  <= 1'h0;
    else if (_004_) \pwdata_reg[26]  <= _037_[26];
  assign pwdata[26] = \pwdata_reg[26] ;
  reg \pwdata_reg[27] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[27]  <= 1'h0;
    else if (_004_) \pwdata_reg[27]  <= _037_[27];
  assign pwdata[27] = \pwdata_reg[27] ;
  reg \pwdata_reg[28] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[28]  <= 1'h0;
    else if (_004_) \pwdata_reg[28]  <= _037_[28];
  assign pwdata[28] = \pwdata_reg[28] ;
  reg \pwdata_reg[29] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[29]  <= 1'h0;
    else if (_004_) \pwdata_reg[29]  <= _037_[29];
  assign pwdata[29] = \pwdata_reg[29] ;
  reg \pwdata_reg[30] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[30]  <= 1'h0;
    else if (_004_) \pwdata_reg[30]  <= _037_[30];
  assign pwdata[30] = \pwdata_reg[30] ;
  reg \pwdata_reg[31] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pwdata_reg[31]  <= 1'h0;
    else if (_004_) \pwdata_reg[31]  <= _037_[31];
  assign pwdata[31] = \pwdata_reg[31] ;
  reg \paddr_reg[28] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \paddr_reg[28]  <= 1'h0;
    else if (_004_) \paddr_reg[28]  <= _112_[12];
  assign paddr[28] = \paddr_reg[28] ;
  reg \paddr_reg[29] ;
  (* src = "./APB_Master/apb_1.sv:68.3-83.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \paddr_reg[29]  <= 1'h0;
    else if (_004_) \paddr_reg[29]  <= _112_[13];
  assign paddr[29] = \paddr_reg[29] ;
  (* src = "./APB_Master/apb_1.sv:63.3-66.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) penable <= 1'h1;
    else if (_000_) penable <= penable_nxt;
  assign _036_[1] = ~pwdata[1];
  assign _036_[16] = ~pwdata[16];
  assign _036_[15] = ~pwdata[15];
  assign _036_[11] = ~pwdata[11];
  assign _036_[9] = ~pwdata[9];
  assign _036_[7] = ~pwdata[7];
  assign _036_[4] = ~pwdata[4];
  assign _036_[18] = ~pwdata[18];
  assign _036_[23] = ~pwdata[23];
  assign _036_[26] = ~pwdata[26];
  assign _036_[28] = ~pwdata[28];
  assign _036_[31] = ~pwdata[31];
  assign _036_[30] = ~pwdata[30];
  assign _007_ = ~pr_state[0];
  assign _008_ = ~pr_state[1];
  assign _011_ = ~_025_[0];
  assign _089_ = _036_[2] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  pwdata[1];
  assign _035_[14] = pwdata[14] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _092_;
  assign _035_[29] = _046_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _088_;
  assign _088_ = _070_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[27];
  assign _035_[22] = pwdata[22] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[21];
  assign _035_[25] = pwdata[25] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _087_;
  assign _087_ = _068_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[23];
  assign _035_[21] = pwdata[21] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _086_;
  assign _086_ = _066_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[19];
  assign _092_ = _036_[14] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[13];
  assign _035_[17] = _043_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _085_;
  assign _085_ = _064_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[15];
  assign _035_[24] = pwdata[24] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[23];
  assign _035_[13] = _062_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[11];
  assign _035_[9] = pwdata[9] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _084_;
  assign _084_ = _060_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[7];
  assign _093_ = _036_[16] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[15];
  assign _035_[5] = _099_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _083_;
  assign _083_ = _058_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[3];
  assign _095_ = _036_[26] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[25];
  assign _035_[27] = _108_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _082_;
  assign _082_ = _076_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[23];
  assign _035_[26] = pwdata[26] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _095_;
  assign _035_[19] = _106_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _081_;
  assign _081_ = _074_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[15];
  assign _035_[11] = _105_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _080_;
  assign _080_ = _072_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[7];
  assign _096_ = _036_[28] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[27];
  assign _035_[23] = _110_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _079_;
  assign _079_ = _078_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[15];
  assign _035_[28] = pwdata[28] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _096_;
  assign _035_[12] = pwdata[12] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[11];
  assign _035_[15] = _109_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _056_;
  assign _056_ = _077_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _035_[7];
  assign _078_ = _075_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _074_;
  assign _110_ = _107_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _055_;
  assign _055_ = _075_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _106_;
  assign _077_ = _073_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _072_;
  assign _109_ = _101_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _054_;
  assign _054_ = _073_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _105_;
  assign _097_ = _036_[30] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[29];
  assign _035_[7] = _104_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _053_;
  assign _053_ = _071_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _035_[3];
  assign _076_ = _069_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _068_;
  assign _108_ = _103_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _052_;
  assign _052_ = _069_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[25];
  assign _075_ = _067_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _066_;
  assign _107_ = pwdata[23] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _051_;
  assign _051_ = _067_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[21];
  assign _074_ = _065_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _064_;
  assign _106_ = _102_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _050_;
  assign _050_ = _065_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _043_;
  assign _073_ = _063_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _062_;
  assign _072_ = _061_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _060_;
  assign _105_ = pwdata[11] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _049_;
  assign _049_ = _061_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[9];
  assign _071_ = _059_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _058_;
  assign _104_ = _100_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _048_;
  assign _048_ = _059_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _099_;
  assign _035_[30] = pwdata[30] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _097_;
  assign _035_[3] = _098_ |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _047_;
  assign _047_ = _057_ &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[1];
  assign _070_ = pwdata[29] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _036_[28];
  assign _046_ = pwdata[29] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[28];
  assign _069_ = _036_[27] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _036_[26];
  assign _103_ = pwdata[27] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _045_;
  assign _045_ = _036_[27] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[26];
  assign _068_ = _036_[25] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  pwdata[24];
  assign _067_ = _036_[23] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  pwdata[22];
  assign _066_ = _036_[21] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  pwdata[20];
  assign _065_ = _036_[19] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _036_[18];
  assign _102_ = pwdata[19] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _044_;
  assign _044_ = _036_[19] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[18];
  assign _064_ = pwdata[17] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _036_[16];
  assign _043_ = pwdata[17] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[16];
  assign _063_ = _036_[15] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _036_[14];
  assign _101_ = pwdata[15] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _042_;
  assign _042_ = _036_[15] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[14];
  assign _062_ = pwdata[13] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  pwdata[12];
  assign _061_ = _036_[11] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  pwdata[10];
  assign _060_ = _036_[9] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  pwdata[8];
  assign _059_ = _036_[7] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _036_[6];
  assign _100_ = pwdata[7] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _041_;
  assign _041_ = _036_[7] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[6];
  assign _058_ = _036_[5] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _036_[4];
  assign _099_ = pwdata[5] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _040_;
  assign _040_ = _036_[5] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[4];
  assign _057_ = _036_[3] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _036_[2];
  assign _098_ = pwdata[3] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _039_;
  assign _039_ = _036_[3] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  pwdata[2];
  assign _094_ = _036_[18] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[17];
  assign _015_[0] = _036_[1] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[1];
  assign _019_[2] = _037_[2] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[2];
  assign _019_[3] = _037_[3] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[3];
  assign _019_[4] = _037_[4] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[4];
  assign _019_[5] = _037_[5] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[5];
  assign _019_[6] = _037_[6] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[6];
  assign _019_[7] = _037_[7] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[7];
  assign _019_[8] = _037_[8] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[8];
  assign _019_[9] = _037_[9] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[9];
  assign _019_[10] = _037_[10] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[10];
  assign _019_[11] = _037_[11] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[11];
  assign _019_[12] = _037_[12] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[12];
  assign _019_[13] = _037_[13] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[13];
  assign _019_[14] = _037_[14] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[14];
  assign _019_[15] = _037_[15] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[15];
  assign _019_[16] = _037_[16] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[16];
  assign _019_[17] = _037_[17] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[17];
  assign _019_[18] = _037_[18] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[18];
  assign _019_[19] = _037_[19] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[19];
  assign _019_[20] = _037_[20] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[20];
  assign _019_[21] = _037_[21] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[21];
  assign _019_[22] = _037_[22] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[22];
  assign _019_[23] = _037_[23] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[23];
  assign _019_[24] = _037_[24] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[24];
  assign _019_[25] = _037_[25] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[25];
  assign _019_[26] = _037_[26] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[26];
  assign _019_[27] = _037_[27] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[27];
  assign _019_[28] = _037_[28] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[28];
  assign _019_[29] = _037_[29] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[29];
  assign _019_[30] = _037_[30] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[30];
  assign _019_[31] = _037_[31] ^(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  pwdata[31];
  assign _026_[4] = _025_[4] &(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:593.44-593.84" *)  _027_[2];
  assign _026_[5] = _025_[5] &(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:593.44-593.84" *)  _027_[2];
  assign _026_[0] = _025_[0] &(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:593.44-593.84" *)  _027_[0];
  assign _030_[1] = _029_[1] &(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:593.44-593.84" *)  _026_[3];
  assign _033_[0] = _032_[0] &(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:593.44-593.84" *)  _027_[0];
  assign _037_[2] = _036_[2] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  pwdata[1];
  assign _037_[3] = _036_[3] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[2];
  assign _037_[4] = _036_[4] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[3];
  assign _037_[5] = _036_[5] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[4];
  assign _037_[6] = _036_[6] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[5];
  assign _037_[7] = _036_[7] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[6];
  assign _037_[8] = pwdata[8] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[7];
  assign _037_[9] = _036_[9] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[8];
  assign _037_[10] = pwdata[10] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[9];
  assign _037_[11] = _036_[11] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[10];
  assign _037_[12] = pwdata[12] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[11];
  assign _037_[13] = pwdata[13] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[12];
  assign _037_[14] = _036_[14] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[13];
  assign _037_[15] = _036_[15] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[14];
  assign _037_[16] = _036_[16] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[15];
  assign _037_[17] = pwdata[17] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[16];
  assign _037_[18] = _036_[18] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[17];
  assign _037_[19] = _036_[19] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[18];
  assign _037_[20] = pwdata[20] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[19];
  assign _037_[21] = _036_[21] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[20];
  assign _037_[22] = pwdata[22] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[21];
  assign _037_[23] = _036_[23] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[22];
  assign _037_[24] = pwdata[24] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[23];
  assign _037_[25] = _036_[25] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[24];
  assign _037_[26] = _036_[26] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[25];
  assign _037_[27] = _036_[27] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[26];
  assign _037_[28] = _036_[28] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[27];
  assign _037_[29] = pwdata[29] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[28];
  assign _037_[30] = _036_[30] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[29];
  assign _037_[31] = _036_[31] ^(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:296.13-296.25" *)  _035_[30];
  assign _035_[10] = pwdata[10] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[9];
  assign _035_[18] = pwdata[18] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _094_;
  assign _035_[8] = pwdata[8] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[7];
  assign _035_[16] = pwdata[16] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _093_;
  assign _035_[6] = pwdata[6] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _091_;
  assign _091_ = _036_[6] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[5];
  assign _035_[20] = pwdata[20] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[19];
  assign _035_[4] = pwdata[4] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _090_;
  assign _090_ = _036_[4] &(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _035_[3];
  assign _035_[2] = pwdata[2] |(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _089_;
  assign _012_ = _003_ & _000_;
  assign _006_ = _012_ & pready_i;
  assign _003_ = _011_ | _010_;
  assign _013_ = _002_ & _001_;
  assign _005_ = _013_ & pready_i;
  assign _014_ = _027_[0] | _027_[2];
  assign _002_ = _014_ | _026_[3];
  assign _001_ = _025_[0] | _009_;
  assign _004_ = pready_i & _026_[3];
  assign _015_[1] = _019_[2] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[3];
  assign _015_[2] = _019_[4] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[5];
  assign _015_[3] = _019_[6] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[7];
  assign _015_[4] = _019_[8] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[9];
  assign _015_[5] = _019_[10] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[11];
  assign _015_[6] = _019_[12] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[13];
  assign _015_[7] = _019_[14] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[15];
  assign _015_[8] = _019_[16] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[17];
  assign _015_[9] = _019_[18] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[19];
  assign _015_[10] = _019_[20] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[21];
  assign _015_[11] = _019_[22] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[23];
  assign _015_[12] = _019_[24] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[25];
  assign _015_[13] = _019_[26] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[27];
  assign _015_[14] = _019_[28] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[29];
  assign _015_[15] = _019_[30] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _019_[31];
  assign _016_[0] = _015_[0] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _015_[1];
  assign _016_[1] = _015_[2] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _015_[3];
  assign _016_[2] = _015_[4] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _015_[5];
  assign _016_[3] = _015_[6] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _015_[7];
  assign _016_[4] = _015_[8] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _015_[9];
  assign _016_[5] = _015_[10] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _015_[11];
  assign _016_[6] = _015_[12] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _015_[13];
  assign _016_[7] = _015_[14] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _015_[15];
  assign _017_[0] = _016_[0] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _016_[1];
  assign _017_[1] = _016_[2] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _016_[3];
  assign _017_[2] = _016_[4] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _016_[5];
  assign _017_[3] = _016_[6] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _016_[7];
  assign _018_[0] = _017_[0] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _017_[1];
  assign _018_[1] = _017_[2] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _017_[3];
  assign _024_ = _018_[0] |(* src = "./APB_Master/apb_1.sv:106.48-106.66" *)  _018_[1];
  assign _010_ = pr_state[0] |(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14" *)  _008_;
  assign _020_ = _007_ |(* src = "./APB_Master/apb_1.sv:98.17-98.17|./APB_Master/apb_1.sv:93.5-119.14" *)  pr_state[1];
  assign _028_[1] = _026_[3] |(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:601.20-601.31" *)  _026_[5];
  assign _028_[0] = _026_[0] |(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:601.20-601.31" *)  _026_[4];
  assign _000_ = _027_[0] |(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:605.13-605.15" *)  _026_[3];
  assign _038_ = _000_ |(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:605.13-605.15" *)  _027_[2];
  assign _031_ = _027_[0] |(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:601.20-601.31" *)  _030_[1];
  assign _034_ = _033_[0] |(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:601.20-601.31" *)  _026_[3];
  assign _009_ = pr_state[0] |(* src = "./APB_Master/apb_1.sv:93.20-93.20|./APB_Master/apb_1.sv:93.5-119.14" *)  pr_state[1];
  assign _027_[2] = ~(* src = "./APB_Master/apb_1.sv:93.20-93.20|./APB_Master/apb_1.sv:93.5-119.14" *) _009_;
  assign _027_[0] = ~(* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14" *) _010_;
  assign _026_[3] = ~(* src = "./APB_Master/apb_1.sv:98.17-98.17|./APB_Master/apb_1.sv:93.5-119.14" *) _020_;
  assign _021_ = penable &(* src = "./APB_Master/apb_1.sv:106.32-106.66" *)  _024_;
  assign _022_ = _021_ &(* src = "./APB_Master/apb_1.sv:106.32-106.78" *)  pready_i;
  assign _023_ = event_a_i |(* src = "./APB_Master/apb_1.sv:112.24-112.46" *)  event_b_i;
  assign _025_[0] = _023_ |(* src = "./APB_Master/apb_1.sv:112.24-112.59" *)  event_c_i;
  assign _111_[12] = ~(* src = "./APB_Master/apb_1.sv:105.61-105.104" *) event_b_i;
  assign _112_[12] = event_a_i ? (* src = "./APB_Master/apb_1.sv:105.31-105.104" *) 1'h1 : _111_[12];
  assign _112_[13] = ~(* src = "./APB_Master/apb_1.sv:105.31-105.104" *) event_a_i;
  assign _029_[1] = ~(* src = "./APB_Master/apb_1.sv:106.31-106.89" *) _022_;
  assign _032_[0] = _025_[0] ? (* src = "./APB_Master/apb_1.sv:112.24-112.59|./APB_Master/apb_1.sv:112.20-116.23" *) 1'hx : 1'h0;
  assign _025_[4] = _025_[0] ? (* src = "./APB_Master/apb_1.sv:95.20-95.55|./APB_Master/apb_1.sv:95.16-97.19" *) 1'h1 : 1'hx;
  assign _025_[5] = _025_[0] ? (* src = "./APB_Master/apb_1.sv:95.20-95.55|./APB_Master/apb_1.sv:95.16-97.19" *) 1'h0 : 1'hx;
  assign nx_state[0] = _038_ ? (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:605.13-605.25" *) _028_[0] : 1'hx;
  assign nx_state[1] = _038_ ? (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:605.13-605.25" *) _028_[1] : 1'hx;
  assign penable_nxt = _000_ ? (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:605.13-605.25" *) _031_ : 1'hx;
  assign psel_nxt = _000_ ? (* src = "./APB_Master/apb_1.sv:107.18-107.18|./APB_Master/apb_1.sv:93.5-119.14|/share/techmap.v:605.13-605.25" *) _034_ : 1'hx;
  assign _036_[2] = ~(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:279.31-279.37" *) pwdata[2];
  assign _036_[3] = ~(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:279.31-279.37" *) pwdata[3];
  assign _036_[5] = ~(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:279.31-279.37" *) pwdata[5];
  assign _036_[6] = ~(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:279.31-279.37" *) pwdata[6];
  assign _036_[14] = ~(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:279.31-279.37" *) pwdata[14];
  assign _036_[19] = ~(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:279.31-279.37" *) pwdata[19];
  assign _036_[21] = ~(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:279.31-279.37" *) pwdata[21];
  assign _036_[25] = ~(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:279.31-279.37" *) pwdata[25];
  assign _036_[27] = ~(* src = "./APB_Master/apb_1.sv:103.31-103.53|/share/techmap.v:279.31-279.37" *) pwdata[27];
  assign _037_[1:0] = { _036_[1], 1'h0 };
  assign _035_[1:0] = { pwdata[1], 1'h0 };
  assign { _036_[29], _036_[24], _036_[22], _036_[20], _036_[17], _036_[13:12], _036_[10], _036_[8], _036_[0] } = { pwdata[29], pwdata[24], pwdata[22], pwdata[20], pwdata[17], pwdata[13:12], pwdata[10], pwdata[8], 1'h0 };
  assign _032_[1] = 1'h1;
  assign _033_[1] = _026_[3];
  assign _029_[0] = 1'h1;
  assign _030_[0] = _027_[0];
  assign _025_[3:1] = 3'h4;
  assign _027_[1] = _026_[3];
  assign _026_[2:1] = 2'h0;
  assign _019_[1:0] = { _015_[0], 1'h0 };
  assign { _112_[31:14], _112_[11:0] } = { 2'h0, _112_[13:12], 26'h0000000 };
  assign { _111_[31:13], _111_[11:0] } = { 3'h1, _111_[12], 27'h0001000 };
  assign pwdata[0] = 1'h0;
  assign { paddr[31:30], paddr[27:0] } = { 16'h0000, paddr[29:28], 12'h000 };
  assign pwdata_o = { pwdata[31:1], 1'h0 };
  assign pwrite_o = pwrite;
  assign paddr_o = { 2'h0, paddr[29:28], 14'h0000, paddr[29:28], 12'h000 };
  assign penable_o = penable;
  assign psel_o = psel;
endmodule
