/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* dynports =  1  *)
(* top =  1  *)
(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:9.1-106.10" *)
module async_FIFO(rd_data, full, empty, rd, wr, wr_data, r_clk, w_clk, r_rst, w_rst);
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:17.28-17.35" *)
  output [7:0] rd_data;
  wire [7:0] rd_data;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:14.16-14.20" *)
  output full;
  reg full;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:14.21-14.26" *)
  output empty;
  reg empty;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:15.39-15.41" *)
  input rd;
  wire rd;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:15.42-15.44" *)
  input wr;
  wire wr;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:16.27-16.34" *)
  input [7:0] wr_data;
  wire [7:0] wr_data;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:15.15-15.20" *)
  input r_clk;
  wire r_clk;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:15.27-15.32" *)
  input w_clk;
  wire w_clk;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:15.21-15.26" *)
  input r_rst;
  wire r_rst;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:15.33-15.38" *)
  input w_rst;
  wire w_rst;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:95.3-98.6" *)
  wire _000_;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:101.3-104.6" *)
  wire _001_;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.29-88.40" *)
  wire _002_;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.29-89.39" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire [1:0] _016_;
  wire [1:0] _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire [3:0] _026_;
  wire [1:0] _027_;
  wire [3:0] _028_;
  wire [1:0] _029_;
  wire [3:0] _030_;
  wire [1:0] _031_;
  wire [3:0] _032_;
  wire [1:0] _033_;
  wire [3:0] _034_;
  wire [1:0] _035_;
  wire [3:0] _036_;
  wire [1:0] _037_;
  wire [3:0] _038_;
  wire [1:0] _039_;
  wire [3:0] _040_;
  wire [1:0] _041_;
  wire [3:0] _042_;
  wire [1:0] _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire [3:0] _047_;
  wire [3:0] _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:103.27-103.54" *)
  wire _065_;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:38.20-38.25" *)
  wire _066_;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:52.20-52.26" *)
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:591.28-591.35" *)
  wire [63:0] _076_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:581.22-581.23" *)
  wire [7:0] _077_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:583.21-583.22" *)
  wire [7:0] _078_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:586.19-586.22" *)
  wire [7:0] _079_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 3" *)
  wire [3:0] _080_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:287.21-287.22" *)
  (* unused_bits = "3" *)
  wire [3:0] _081_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [3:0] _082_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:62.17-62.30|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 3" *)
  wire [3:0] _083_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:62.17-62.30|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:287.21-287.22" *)
  (* unused_bits = "3" *)
  wire [3:0] _084_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:62.17-62.30|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [3:0] _085_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.44-88.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _086_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.44-88.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:287.21-287.22" *)
  wire [3:0] _087_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.44-88.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:270.26-270.27" *)
  wire [3:0] _088_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.44-89.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _089_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.44-89.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:287.21-287.22" *)
  wire [3:0] _090_;
  (* force_downto = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.44-89.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:270.26-270.27" *)
  wire [3:0] _091_;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.15" *)
  wire _092_;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:20.21-20.25" *)
  reg [7:0] \FIFO[0] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:20.21-20.25" *)
  reg [7:0] \FIFO[1] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:20.21-20.25" *)
  reg [7:0] \FIFO[2] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:20.21-20.25" *)
  reg [7:0] \FIFO[3] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:20.21-20.25" *)
  reg [7:0] \FIFO[4] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:20.21-20.25" *)
  reg [7:0] \FIFO[5] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:20.21-20.25" *)
  reg [7:0] \FIFO[6] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:20.21-20.25" *)
  reg [7:0] \FIFO[7] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:27.18-27.28" *)
  wire [3:0] bin_rd_ptr;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:28.18-28.32" *)
  wire [3:0] bin_rd_ptr_nxt;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:27.29-27.39" *)
  wire [3:0] bin_wr_ptr;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:28.33-28.47" *)
  wire [3:0] bin_wr_ptr_nxt;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:24.18-24.27" *)
  reg [3:0] gr_rd_ptr;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:25.18-25.31" *)
  wire [3:0] gr_rd_ptr_nxt;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:24.28-24.37" *)
  reg [3:0] gr_wr_ptr;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:25.32-25.45" *)
  wire [3:0] gr_wr_ptr_nxt;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:21.21-21.31" *)
  reg [7:0] rd_data_ff;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:19.18-19.24" *)
  (* unused_bits = "3" *)
  wire [3:0] rd_ptr;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:22.18-22.29" *)
  wire [3:0] sync_rd_ptr;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:22.30-22.41" *)
  wire [3:0] sync_wr_ptr;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:19.25-19.31" *)
  (* unused_bits = "3" *)
  wire [3:0] wr_ptr;
  reg \rd_ptr_reg[0] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:59.3-64.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) \rd_ptr_reg[0]  <= 1'h0;
    else if (_002_) \rd_ptr_reg[0]  <= _084_[0];
  assign rd_ptr[0] = \rd_ptr_reg[0] ;
  reg \rd_ptr_reg[1] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:59.3-64.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) \rd_ptr_reg[1]  <= 1'h0;
    else if (_002_) \rd_ptr_reg[1]  <= _085_[1];
  assign rd_ptr[1] = \rd_ptr_reg[1] ;
  reg \rd_ptr_reg[2] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:59.3-64.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) \rd_ptr_reg[2]  <= 1'h0;
    else if (_002_) \rd_ptr_reg[2]  <= _085_[2];
  assign rd_ptr[2] = \rd_ptr_reg[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[0] [0] <= 1'h0;
    else if (_011_) \FIFO[0] [0] <= wr_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[0] [1] <= 1'h0;
    else if (_011_) \FIFO[0] [1] <= wr_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[0] [2] <= 1'h0;
    else if (_011_) \FIFO[0] [2] <= wr_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[0] [3] <= 1'h0;
    else if (_011_) \FIFO[0] [3] <= wr_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[0] [4] <= 1'h0;
    else if (_011_) \FIFO[0] [4] <= wr_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[0] [5] <= 1'h0;
    else if (_011_) \FIFO[0] [5] <= wr_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[0] [6] <= 1'h0;
    else if (_011_) \FIFO[0] [6] <= wr_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[0] [7] <= 1'h0;
    else if (_011_) \FIFO[0] [7] <= wr_data[7];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[5] [0] <= 1'h0;
    else if (_010_) \FIFO[5] [0] <= wr_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[5] [1] <= 1'h0;
    else if (_010_) \FIFO[5] [1] <= wr_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[5] [2] <= 1'h0;
    else if (_010_) \FIFO[5] [2] <= wr_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[5] [3] <= 1'h0;
    else if (_010_) \FIFO[5] [3] <= wr_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[5] [4] <= 1'h0;
    else if (_010_) \FIFO[5] [4] <= wr_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[5] [5] <= 1'h0;
    else if (_010_) \FIFO[5] [5] <= wr_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[5] [6] <= 1'h0;
    else if (_010_) \FIFO[5] [6] <= wr_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[5] [7] <= 1'h0;
    else if (_010_) \FIFO[5] [7] <= wr_data[7];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[1] [0] <= 1'h0;
    else if (_009_) \FIFO[1] [0] <= wr_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[1] [1] <= 1'h0;
    else if (_009_) \FIFO[1] [1] <= wr_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[1] [2] <= 1'h0;
    else if (_009_) \FIFO[1] [2] <= wr_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[1] [3] <= 1'h0;
    else if (_009_) \FIFO[1] [3] <= wr_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[1] [4] <= 1'h0;
    else if (_009_) \FIFO[1] [4] <= wr_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[1] [5] <= 1'h0;
    else if (_009_) \FIFO[1] [5] <= wr_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[1] [6] <= 1'h0;
    else if (_009_) \FIFO[1] [6] <= wr_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[1] [7] <= 1'h0;
    else if (_009_) \FIFO[1] [7] <= wr_data[7];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[3] [0] <= 1'h0;
    else if (_008_) \FIFO[3] [0] <= wr_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[3] [1] <= 1'h0;
    else if (_008_) \FIFO[3] [1] <= wr_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[3] [2] <= 1'h0;
    else if (_008_) \FIFO[3] [2] <= wr_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[3] [3] <= 1'h0;
    else if (_008_) \FIFO[3] [3] <= wr_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[3] [4] <= 1'h0;
    else if (_008_) \FIFO[3] [4] <= wr_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[3] [5] <= 1'h0;
    else if (_008_) \FIFO[3] [5] <= wr_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[3] [6] <= 1'h0;
    else if (_008_) \FIFO[3] [6] <= wr_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[3] [7] <= 1'h0;
    else if (_008_) \FIFO[3] [7] <= wr_data[7];
  reg \wr_ptr_reg[0] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:43.3-48.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \wr_ptr_reg[0]  <= 1'h0;
    else if (_003_) \wr_ptr_reg[0]  <= _081_[0];
  assign wr_ptr[0] = \wr_ptr_reg[0] ;
  reg \wr_ptr_reg[1] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:43.3-48.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \wr_ptr_reg[1]  <= 1'h0;
    else if (_003_) \wr_ptr_reg[1]  <= _082_[1];
  assign wr_ptr[1] = \wr_ptr_reg[1] ;
  reg \wr_ptr_reg[2] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:43.3-48.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \wr_ptr_reg[2]  <= 1'h0;
    else if (_003_) \wr_ptr_reg[2]  <= _082_[2];
  assign wr_ptr[2] = \wr_ptr_reg[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[7] [0] <= 1'h0;
    else if (_007_) \FIFO[7] [0] <= wr_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[7] [1] <= 1'h0;
    else if (_007_) \FIFO[7] [1] <= wr_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[7] [2] <= 1'h0;
    else if (_007_) \FIFO[7] [2] <= wr_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[7] [3] <= 1'h0;
    else if (_007_) \FIFO[7] [3] <= wr_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[7] [4] <= 1'h0;
    else if (_007_) \FIFO[7] [4] <= wr_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[7] [5] <= 1'h0;
    else if (_007_) \FIFO[7] [5] <= wr_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[7] [6] <= 1'h0;
    else if (_007_) \FIFO[7] [6] <= wr_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[7] [7] <= 1'h0;
    else if (_007_) \FIFO[7] [7] <= wr_data[7];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[4] [0] <= 1'h0;
    else if (_006_) \FIFO[4] [0] <= wr_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[4] [1] <= 1'h0;
    else if (_006_) \FIFO[4] [1] <= wr_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[4] [2] <= 1'h0;
    else if (_006_) \FIFO[4] [2] <= wr_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[4] [3] <= 1'h0;
    else if (_006_) \FIFO[4] [3] <= wr_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[4] [4] <= 1'h0;
    else if (_006_) \FIFO[4] [4] <= wr_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[4] [5] <= 1'h0;
    else if (_006_) \FIFO[4] [5] <= wr_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[4] [6] <= 1'h0;
    else if (_006_) \FIFO[4] [6] <= wr_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[4] [7] <= 1'h0;
    else if (_006_) \FIFO[4] [7] <= wr_data[7];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:50.3-55.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) rd_data_ff[0] <= 1'h0;
    else if (_002_) rd_data_ff[0] <= _078_[0];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:50.3-55.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) rd_data_ff[1] <= 1'h0;
    else if (_002_) rd_data_ff[1] <= _078_[1];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:50.3-55.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) rd_data_ff[2] <= 1'h0;
    else if (_002_) rd_data_ff[2] <= _078_[2];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:50.3-55.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) rd_data_ff[3] <= 1'h0;
    else if (_002_) rd_data_ff[3] <= _078_[3];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:50.3-55.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) rd_data_ff[4] <= 1'h0;
    else if (_002_) rd_data_ff[4] <= _078_[4];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:50.3-55.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) rd_data_ff[5] <= 1'h0;
    else if (_002_) rd_data_ff[5] <= _078_[5];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:50.3-55.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) rd_data_ff[6] <= 1'h0;
    else if (_002_) rd_data_ff[6] <= _078_[6];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:50.3-55.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) rd_data_ff[7] <= 1'h0;
    else if (_002_) rd_data_ff[7] <= _078_[7];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[2] [0] <= 1'h0;
    else if (_005_) \FIFO[2] [0] <= wr_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[2] [1] <= 1'h0;
    else if (_005_) \FIFO[2] [1] <= wr_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[2] [2] <= 1'h0;
    else if (_005_) \FIFO[2] [2] <= wr_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[2] [3] <= 1'h0;
    else if (_005_) \FIFO[2] [3] <= wr_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[2] [4] <= 1'h0;
    else if (_005_) \FIFO[2] [4] <= wr_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[2] [5] <= 1'h0;
    else if (_005_) \FIFO[2] [5] <= wr_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[2] [6] <= 1'h0;
    else if (_005_) \FIFO[2] [6] <= wr_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[2] [7] <= 1'h0;
    else if (_005_) \FIFO[2] [7] <= wr_data[7];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[6] [0] <= 1'h0;
    else if (_004_) \FIFO[6] [0] <= wr_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[6] [1] <= 1'h0;
    else if (_004_) \FIFO[6] [1] <= wr_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[6] [2] <= 1'h0;
    else if (_004_) \FIFO[6] [2] <= wr_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[6] [3] <= 1'h0;
    else if (_004_) \FIFO[6] [3] <= wr_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[6] [4] <= 1'h0;
    else if (_004_) \FIFO[6] [4] <= wr_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[6] [5] <= 1'h0;
    else if (_004_) \FIFO[6] [5] <= wr_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[6] [6] <= 1'h0;
    else if (_004_) \FIFO[6] [6] <= wr_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:34.3-41.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \FIFO[6] [7] <= 1'h0;
    else if (_004_) \FIFO[6] [7] <= wr_data[7];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:101.3-104.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) full <= 1'h0;
    else full <= _001_;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:95.3-98.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) empty <= 1'h1;
    else empty <= _000_;
  reg \bin_wr_ptr_reg[0] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:83.3-86.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \bin_wr_ptr_reg[0]  <= 1'h0;
    else \bin_wr_ptr_reg[0]  <= bin_wr_ptr_nxt[0];
  assign bin_wr_ptr[0] = \bin_wr_ptr_reg[0] ;
  reg \bin_wr_ptr_reg[1] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:83.3-86.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \bin_wr_ptr_reg[1]  <= 1'h0;
    else \bin_wr_ptr_reg[1]  <= bin_wr_ptr_nxt[1];
  assign bin_wr_ptr[1] = \bin_wr_ptr_reg[1] ;
  reg \bin_wr_ptr_reg[2] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:83.3-86.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) \bin_wr_ptr_reg[2]  <= 1'h0;
    else \bin_wr_ptr_reg[2]  <= bin_wr_ptr_nxt[2];
  assign bin_wr_ptr[2] = \bin_wr_ptr_reg[2] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:78.3-81.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) gr_wr_ptr[0] <= 1'h0;
    else gr_wr_ptr[0] <= gr_wr_ptr_nxt[0];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:78.3-81.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) gr_wr_ptr[1] <= 1'h0;
    else gr_wr_ptr[1] <= gr_wr_ptr_nxt[1];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:78.3-81.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) gr_wr_ptr[2] <= 1'h0;
    else gr_wr_ptr[2] <= gr_wr_ptr_nxt[2];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:78.3-81.6" *)
  always @(posedge w_clk, negedge w_rst)
    if (!w_rst) gr_wr_ptr[3] <= 1'h0;
    else gr_wr_ptr[3] <= bin_wr_ptr_nxt[3];
  reg \bin_rd_ptr_reg[0] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:73.4-76.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) \bin_rd_ptr_reg[0]  <= 1'h0;
    else \bin_rd_ptr_reg[0]  <= bin_rd_ptr_nxt[0];
  assign bin_rd_ptr[0] = \bin_rd_ptr_reg[0] ;
  reg \bin_rd_ptr_reg[1] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:73.4-76.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) \bin_rd_ptr_reg[1]  <= 1'h0;
    else \bin_rd_ptr_reg[1]  <= bin_rd_ptr_nxt[1];
  assign bin_rd_ptr[1] = \bin_rd_ptr_reg[1] ;
  reg \bin_rd_ptr_reg[2] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:73.4-76.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) \bin_rd_ptr_reg[2]  <= 1'h0;
    else \bin_rd_ptr_reg[2]  <= bin_rd_ptr_nxt[2];
  assign bin_rd_ptr[2] = \bin_rd_ptr_reg[2] ;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:68.3-71.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) gr_rd_ptr[0] <= 1'h0;
    else gr_rd_ptr[0] <= gr_rd_ptr_nxt[0];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:68.3-71.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) gr_rd_ptr[1] <= 1'h0;
    else gr_rd_ptr[1] <= gr_rd_ptr_nxt[1];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:68.3-71.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) gr_rd_ptr[2] <= 1'h0;
    else gr_rd_ptr[2] <= gr_rd_ptr_nxt[2];
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:68.3-71.6" *)
  always @(posedge r_clk, negedge r_rst)
    if (!r_rst) gr_rd_ptr[3] <= 1'h0;
    else gr_rd_ptr[3] <= bin_rd_ptr_nxt[3];
  assign _090_[0] = ~bin_wr_ptr[0];
  assign _087_[0] = ~bin_rd_ptr[0];
  assign _084_[0] = ~rd_ptr[0];
  assign _081_[0] = ~wr_ptr[0];
  assign _012_ = ~rd_ptr[1];
  assign _013_ = ~rd_ptr[2];
  assign _014_ = ~wr_ptr[1];
  assign _015_ = ~wr_ptr[2];
  assign _080_[1] = wr_ptr[1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  wr_ptr[0];
  assign _083_[1] = rd_ptr[1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:62.17-62.30|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  rd_ptr[0];
  assign _086_[2] = bin_rd_ptr[2] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.44-88.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _086_[1];
  assign _086_[1] = bin_rd_ptr[1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.44-88.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  bin_rd_ptr[0];
  assign _089_[2] = bin_wr_ptr[2] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.44-89.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _089_[1];
  assign _089_[1] = bin_wr_ptr[1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.44-89.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  bin_wr_ptr[0];
  assign _002_ = rd &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.29-88.40" *)  _067_;
  assign _003_ = wr &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.29-89.39" *)  _066_;
  assign gr_rd_ptr_nxt[0] = bin_rd_ptr_nxt[1] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:92.27-92.63" *)  bin_rd_ptr_nxt[0];
  assign gr_rd_ptr_nxt[1] = bin_rd_ptr_nxt[2] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:92.27-92.63" *)  bin_rd_ptr_nxt[1];
  assign gr_rd_ptr_nxt[2] = bin_rd_ptr_nxt[3] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:92.27-92.63" *)  bin_rd_ptr_nxt[2];
  assign gr_wr_ptr_nxt[0] = bin_wr_ptr_nxt[1] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:93.27-93.63" *)  bin_wr_ptr_nxt[0];
  assign gr_wr_ptr_nxt[1] = bin_wr_ptr_nxt[2] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:93.27-93.63" *)  bin_wr_ptr_nxt[1];
  assign gr_wr_ptr_nxt[2] = bin_wr_ptr_nxt[3] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:93.27-93.63" *)  bin_wr_ptr_nxt[2];
  assign _047_[0] = gr_rd_ptr_nxt[0] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:97.27-97.55" *)  sync_wr_ptr[0];
  assign _047_[1] = gr_rd_ptr_nxt[1] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:97.27-97.55" *)  sync_wr_ptr[1];
  assign _047_[2] = gr_rd_ptr_nxt[2] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:97.27-97.55" *)  sync_wr_ptr[2];
  assign _047_[3] = bin_rd_ptr_nxt[3] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:97.27-97.55" *)  sync_wr_ptr[3];
  assign _048_[0] = gr_wr_ptr_nxt[0] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:103.26-103.94" *)  sync_rd_ptr[0];
  assign _048_[1] = gr_wr_ptr_nxt[1] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:103.26-103.94" *)  sync_rd_ptr[1];
  assign _048_[2] = _065_ ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:103.26-103.94" *)  sync_rd_ptr[2];
  assign _076_[56] = \FIFO[0] [0] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[7];
  assign _076_[57] = \FIFO[0] [1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[7];
  assign _076_[58] = \FIFO[0] [2] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[7];
  assign _076_[59] = \FIFO[0] [3] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[7];
  assign _076_[60] = \FIFO[0] [4] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[7];
  assign _076_[61] = \FIFO[0] [5] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[7];
  assign _076_[62] = \FIFO[0] [6] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[7];
  assign _076_[63] = \FIFO[0] [7] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[7];
  assign _076_[48] = \FIFO[1] [0] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[6];
  assign _076_[49] = \FIFO[1] [1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[6];
  assign _076_[50] = \FIFO[1] [2] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[6];
  assign _076_[51] = \FIFO[1] [3] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[6];
  assign _076_[52] = \FIFO[1] [4] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[6];
  assign _076_[53] = \FIFO[1] [5] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[6];
  assign _076_[54] = \FIFO[1] [6] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[6];
  assign _076_[55] = \FIFO[1] [7] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[6];
  assign _076_[40] = \FIFO[2] [0] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[5];
  assign _076_[41] = \FIFO[2] [1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[5];
  assign _076_[42] = \FIFO[2] [2] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[5];
  assign _076_[43] = \FIFO[2] [3] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[5];
  assign _076_[44] = \FIFO[2] [4] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[5];
  assign _076_[45] = \FIFO[2] [5] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[5];
  assign _076_[46] = \FIFO[2] [6] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[5];
  assign _076_[47] = \FIFO[2] [7] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[5];
  assign _076_[32] = \FIFO[3] [0] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[4];
  assign _076_[33] = \FIFO[3] [1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[4];
  assign _076_[34] = \FIFO[3] [2] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[4];
  assign _076_[35] = \FIFO[3] [3] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[4];
  assign _076_[36] = \FIFO[3] [4] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[4];
  assign _076_[37] = \FIFO[3] [5] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[4];
  assign _076_[38] = \FIFO[3] [6] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[4];
  assign _076_[39] = \FIFO[3] [7] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[4];
  assign _076_[24] = \FIFO[4] [0] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[3];
  assign _076_[25] = \FIFO[4] [1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[3];
  assign _076_[26] = \FIFO[4] [2] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[3];
  assign _076_[27] = \FIFO[4] [3] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[3];
  assign _076_[28] = \FIFO[4] [4] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[3];
  assign _076_[29] = \FIFO[4] [5] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[3];
  assign _076_[30] = \FIFO[4] [6] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[3];
  assign _076_[31] = \FIFO[4] [7] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[3];
  assign _076_[16] = \FIFO[5] [0] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[2];
  assign _076_[17] = \FIFO[5] [1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[2];
  assign _076_[18] = \FIFO[5] [2] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[2];
  assign _076_[19] = \FIFO[5] [3] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[2];
  assign _076_[20] = \FIFO[5] [4] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[2];
  assign _076_[21] = \FIFO[5] [5] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[2];
  assign _076_[22] = \FIFO[5] [6] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[2];
  assign _076_[23] = \FIFO[5] [7] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[2];
  assign _076_[8] = \FIFO[6] [0] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[1];
  assign _076_[9] = \FIFO[6] [1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[1];
  assign _076_[10] = \FIFO[6] [2] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[1];
  assign _076_[11] = \FIFO[6] [3] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[1];
  assign _076_[12] = \FIFO[6] [4] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[1];
  assign _076_[13] = \FIFO[6] [5] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[1];
  assign _076_[14] = \FIFO[6] [6] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[1];
  assign _076_[15] = \FIFO[6] [7] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[1];
  assign _076_[0] = \FIFO[7] [0] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[0];
  assign _076_[1] = \FIFO[7] [1] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[0];
  assign _076_[2] = \FIFO[7] [2] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[0];
  assign _076_[3] = \FIFO[7] [3] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[0];
  assign _076_[4] = \FIFO[7] [4] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[0];
  assign _076_[5] = \FIFO[7] [5] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[0];
  assign _076_[6] = \FIFO[7] [6] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[0];
  assign _076_[7] = \FIFO[7] [7] &(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:593.44-593.84" *)  _077_[0];
  assign _082_[1] = wr_ptr[1] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:296.13-296.25" *)  wr_ptr[0];
  assign _082_[2] = wr_ptr[2] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:296.13-296.25" *)  _080_[1];
  assign _085_[1] = rd_ptr[1] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:62.17-62.30|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:296.13-296.25" *)  rd_ptr[0];
  assign _085_[2] = rd_ptr[2] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:62.17-62.30|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:296.13-296.25" *)  _083_[1];
  assign _088_[1] = bin_rd_ptr[1] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.44-88.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:296.13-296.25" *)  bin_rd_ptr[0];
  assign _088_[2] = bin_rd_ptr[2] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.44-88.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:296.13-296.25" *)  _086_[1];
  assign _088_[3] = gr_rd_ptr[3] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.44-88.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:296.13-296.25" *)  _086_[2];
  assign _091_[1] = bin_wr_ptr[1] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.44-89.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:296.13-296.25" *)  bin_wr_ptr[0];
  assign _091_[2] = bin_wr_ptr[2] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.44-89.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:296.13-296.25" *)  _089_[1];
  assign _091_[3] = gr_wr_ptr[3] ^(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.44-89.61|./Asynchronous_FIFO/asynch_FIFO.sv:46.17-46.30|/share/techmap.v:296.13-296.25" *)  _089_[2];
  assign _011_ = _003_ & _075_;
  assign _010_ = _003_ & _070_;
  assign _009_ = _003_ & _074_;
  assign _008_ = _003_ & _072_;
  assign _007_ = _003_ & _068_;
  assign _006_ = _003_ & _071_;
  assign _005_ = _003_ & _073_;
  assign _004_ = _003_ & _069_;
  assign _016_[0] = _047_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:97.27-97.55" *)  _047_[1];
  assign _016_[1] = _047_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:97.27-97.55" *)  _047_[3];
  assign _049_ = _016_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:97.27-97.55" *)  _016_[1];
  assign _017_[0] = _048_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:103.26-103.94" *)  _048_[1];
  assign _017_[1] = _048_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:103.26-103.94" *)  sync_rd_ptr[3];
  assign _050_ = _017_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:103.26-103.94" *)  _017_[1];
  assign _051_ = _018_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  _013_;
  assign _052_ = _019_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  _013_;
  assign _053_ = _020_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  _013_;
  assign _054_ = _021_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  _013_;
  assign _018_ = _084_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  _012_;
  assign _055_ = _018_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  rd_ptr[2];
  assign _019_ = rd_ptr[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  _012_;
  assign _056_ = _019_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  rd_ptr[2];
  assign _020_ = _084_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  rd_ptr[1];
  assign _057_ = _020_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  rd_ptr[2];
  assign _058_ = _022_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  _015_;
  assign _059_ = _023_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  _015_;
  assign _060_ = _024_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  _015_;
  assign _061_ = _025_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  _015_;
  assign _022_ = _081_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  _014_;
  assign _062_ = _022_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  wr_ptr[2];
  assign _023_ = wr_ptr[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  _014_;
  assign _063_ = _023_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  wr_ptr[2];
  assign _024_ = _081_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  wr_ptr[1];
  assign _064_ = _024_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  wr_ptr[2];
  assign _026_[0] = _076_[7] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[15];
  assign _026_[1] = _076_[23] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[31];
  assign _026_[2] = _076_[39] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[47];
  assign _026_[3] = _076_[55] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[63];
  assign _027_[0] = _026_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _026_[1];
  assign _027_[1] = _026_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _026_[3];
  assign _079_[7] = _027_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _027_[1];
  assign _028_[0] = _076_[6] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[14];
  assign _028_[1] = _076_[22] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[30];
  assign _028_[2] = _076_[38] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[46];
  assign _028_[3] = _076_[54] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[62];
  assign _029_[0] = _028_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _028_[1];
  assign _029_[1] = _028_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _028_[3];
  assign _079_[6] = _029_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _029_[1];
  assign _030_[0] = _076_[5] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[13];
  assign _030_[1] = _076_[21] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[29];
  assign _030_[2] = _076_[37] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[45];
  assign _030_[3] = _076_[53] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[61];
  assign _031_[0] = _030_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _030_[1];
  assign _031_[1] = _030_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _030_[3];
  assign _079_[5] = _031_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _031_[1];
  assign _032_[0] = _076_[4] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[12];
  assign _032_[1] = _076_[20] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[28];
  assign _032_[2] = _076_[36] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[44];
  assign _032_[3] = _076_[52] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[60];
  assign _033_[0] = _032_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _032_[1];
  assign _033_[1] = _032_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _032_[3];
  assign _079_[4] = _033_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _033_[1];
  assign _034_[0] = _076_[3] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[11];
  assign _034_[1] = _076_[19] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[27];
  assign _034_[2] = _076_[35] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[43];
  assign _034_[3] = _076_[51] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[59];
  assign _035_[0] = _034_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _034_[1];
  assign _035_[1] = _034_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _034_[3];
  assign _079_[3] = _035_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _035_[1];
  assign _036_[0] = _076_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[10];
  assign _036_[1] = _076_[18] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[26];
  assign _036_[2] = _076_[34] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[42];
  assign _036_[3] = _076_[50] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[58];
  assign _037_[0] = _036_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _036_[1];
  assign _037_[1] = _036_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _036_[3];
  assign _079_[2] = _037_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _037_[1];
  assign _038_[0] = _076_[1] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[9];
  assign _038_[1] = _076_[17] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[25];
  assign _038_[2] = _076_[33] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[41];
  assign _038_[3] = _076_[49] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[57];
  assign _039_[0] = _038_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _038_[1];
  assign _039_[1] = _038_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _038_[3];
  assign _079_[1] = _039_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _039_[1];
  assign _040_[0] = _076_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[8];
  assign _040_[1] = _076_[16] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[24];
  assign _040_[2] = _076_[32] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[40];
  assign _040_[3] = _076_[48] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _076_[56];
  assign _041_[0] = _040_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _040_[1];
  assign _041_[1] = _040_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _040_[3];
  assign _079_[0] = _041_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:601.20-601.31" *)  _041_[1];
  assign _042_[0] = _077_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.15" *)  _077_[1];
  assign _042_[1] = _077_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.15" *)  _077_[3];
  assign _042_[2] = _077_[4] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.15" *)  _077_[5];
  assign _042_[3] = _077_[6] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.15" *)  _077_[7];
  assign _043_[0] = _042_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.15" *)  _042_[1];
  assign _043_[1] = _042_[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.15" *)  _042_[3];
  assign _092_ = _043_[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.15" *)  _043_[1];
  assign _044_ = gr_wr_ptr_nxt[2] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:103.27-103.54" *)  bin_wr_ptr_nxt[3];
  assign _021_ = rd_ptr[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  rd_ptr[1];
  assign _045_ = _021_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *)  rd_ptr[2];
  assign _025_ = wr_ptr[0] |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  wr_ptr[1];
  assign _046_ = _025_ |(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *)  wr_ptr[2];
  assign _067_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.34-88.40" *) empty;
  assign _066_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.34-89.39" *) full;
  assign _065_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:103.27-103.54" *) _044_;
  assign _077_[0] = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *) _051_;
  assign _077_[1] = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *) _052_;
  assign _077_[2] = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *) _053_;
  assign _077_[3] = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *) _054_;
  assign _077_[4] = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *) _055_;
  assign _077_[5] = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *) _056_;
  assign _077_[6] = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *) _057_;
  assign _077_[7] = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25" *) _045_;
  assign _068_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *) _058_;
  assign _069_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *) _059_;
  assign _070_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *) _060_;
  assign _071_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *) _061_;
  assign _072_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *) _062_;
  assign _073_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *) _063_;
  assign _074_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *) _064_;
  assign _075_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:39.7-39.40" *) _046_;
  assign bin_rd_ptr_nxt[0] = _002_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.28-88.74" *) _087_[0] : bin_rd_ptr[0];
  assign bin_rd_ptr_nxt[1] = _002_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.28-88.74" *) _088_[1] : bin_rd_ptr[1];
  assign bin_rd_ptr_nxt[2] = _002_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.28-88.74" *) _088_[2] : bin_rd_ptr[2];
  assign bin_rd_ptr_nxt[3] = _002_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:88.28-88.74" *) _088_[3] : gr_rd_ptr[3];
  assign bin_wr_ptr_nxt[0] = _003_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.28-89.74" *) _090_[0] : bin_wr_ptr[0];
  assign bin_wr_ptr_nxt[1] = _003_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.28-89.74" *) _091_[1] : bin_wr_ptr[1];
  assign bin_wr_ptr_nxt[2] = _003_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.28-89.74" *) _091_[2] : bin_wr_ptr[2];
  assign bin_wr_ptr_nxt[3] = _003_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:89.28-89.74" *) _091_[3] : gr_wr_ptr[3];
  assign _000_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:97.26-97.66" *) _049_;
  assign _001_ = ~(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:103.25-103.105" *) _050_;
  assign _078_[0] = _092_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.25" *) _079_[0] : 1'hx;
  assign _078_[1] = _092_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.25" *) _079_[1] : 1'hx;
  assign _078_[2] = _092_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.25" *) _079_[2] : 1'hx;
  assign _078_[3] = _092_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.25" *) _079_[3] : 1'hx;
  assign _078_[4] = _092_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.25" *) _079_[4] : 1'hx;
  assign _078_[5] = _092_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.25" *) _079_[5] : 1'hx;
  assign _078_[6] = _092_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.25" *) _079_[6] : 1'hx;
  assign _078_[7] = _092_ ? (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:53.21-53.25|/share/techmap.v:605.13-605.25" *) _079_[7] : 1'hx;
  (* module_not_derived = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:30.8-30.81" *)
  sync rd_sync (
    .clk(w_clk),
    .rst(w_rst),
    .sync_i(gr_rd_ptr),
    .sync_o(sync_rd_ptr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:32.8-32.81" *)
  sync wr_sync (
    .clk(r_clk),
    .rst(r_rst),
    .sync_i(gr_wr_ptr),
    .sync_o(sync_wr_ptr)
  );
  assign _091_[0] = _090_[0];
  assign _082_[0] = _081_[0];
  assign _087_[3:1] = { gr_rd_ptr[3], bin_rd_ptr[2:1] };
  assign _080_[0] = wr_ptr[0];
  assign _048_[3] = sync_rd_ptr[3];
  assign _089_[0] = bin_wr_ptr[0];
  assign _081_[3:1] = wr_ptr[3:1];
  assign _090_[3:1] = { gr_wr_ptr[3], bin_wr_ptr[2:1] };
  assign _085_[0] = _084_[0];
  assign _083_[0] = rd_ptr[0];
  assign _084_[3:1] = rd_ptr[3:1];
  assign _088_[0] = _087_[0];
  assign _086_[0] = bin_rd_ptr[0];
  assign bin_wr_ptr[3] = gr_wr_ptr[3];
  assign bin_rd_ptr[3] = gr_rd_ptr[3];
  assign gr_wr_ptr_nxt[3] = bin_wr_ptr_nxt[3];
  assign gr_rd_ptr_nxt[3] = bin_rd_ptr_nxt[3];
  assign rd_data = rd_data_ff;
endmodule

(* dynports =  1  *)
(* src = "./Asynchronous_FIFO/asynch_FIFO.sv:109.1-129.10" *)
module sync(sync_o, rst, clk, sync_i);
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:114.25-114.31" *)
  output [3:0] sync_o;
  reg [3:0] sync_o;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:115.19-115.22" *)
  input rst;
  wire rst;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:115.15-115.18" *)
  input clk;
  wire clk;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:113.24-113.30" *)
  input [3:0] sync_i;
  wire [3:0] sync_i;
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:117.18-117.19" *)
  reg [3:0] Q;
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:119.3-128.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[0] <= 1'h0;
    else Q[0] <= sync_i[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:119.3-128.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[1] <= 1'h0;
    else Q[1] <= sync_i[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:119.3-128.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[2] <= 1'h0;
    else Q[2] <= sync_i[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:119.3-128.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[3] <= 1'h0;
    else Q[3] <= sync_i[3];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:119.3-128.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) sync_o[0] <= 1'h0;
    else sync_o[0] <= Q[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:119.3-128.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) sync_o[1] <= 1'h0;
    else sync_o[1] <= Q[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:119.3-128.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) sync_o[2] <= 1'h0;
    else sync_o[2] <= Q[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./Asynchronous_FIFO/asynch_FIFO.sv:119.3-128.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) sync_o[3] <= 1'h0;
    else sync_o[3] <= Q[3];
endmodule
