/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Bin_to_Gray/b2g.sv:1.1-7.10" *)
module b2g(gr_o, bin);
  (* src = "./Bin_to_Gray/b2g.sv:3.23-3.27" *)
  output [3:0] gr_o;
  wire [3:0] gr_o;
  (* src = "./Bin_to_Gray/b2g.sv:2.23-2.26" *)
  input [3:0] bin;
  wire [3:0] bin;
  assign gr_o[0] = bin[1] ^(* src = "./Bin_to_Gray/b2g.sv:5.53-5.66" *)  bin[0];
  assign gr_o[1] = bin[2] ^(* src = "./Bin_to_Gray/b2g.sv:5.39-5.52" *)  bin[1];
  assign gr_o[2] = bin[3] ^(* src = "./Bin_to_Gray/b2g.sv:5.25-5.38" *)  bin[2];
  assign gr_o[3] = bin[3];
endmodule
