/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Comparator/comp_2bit.sv:2.1-13.10" *)
module comp_2b(Eq, Gt, Lt, A, B);
  (* src = "./Comparator/comp_2bit.sv:3.16-3.18" *)
  output Eq;
  wire Eq;
  (* src = "./Comparator/comp_2bit.sv:3.19-3.21" *)
  output Gt;
  wire Gt;
  (* src = "./Comparator/comp_2bit.sv:3.22-3.24" *)
  output Lt;
  wire Lt;
  (* src = "./Comparator/comp_2bit.sv:4.20-4.21" *)
  input [1:0] A;
  wire [1:0] A;
  (* src = "./Comparator/comp_2bit.sv:4.22-4.23" *)
  input [1:0] B;
  wire [1:0] B;
  wire [1:0] _00_;
  wire _01_;
  (* src = "./Comparator/comp_2bit.sv:10.18-10.31" *)
  wire _02_;
  (* src = "./Comparator/comp_2bit.sv:10.37-10.51" *)
  wire _03_;
  (* src = "./Comparator/comp_2bit.sv:10.37-10.60" *)
  wire _04_;
  (* src = "./Comparator/comp_2bit.sv:11.18-11.31" *)
  wire _05_;
  (* src = "./Comparator/comp_2bit.sv:11.37-11.52" *)
  wire _06_;
  (* src = "./Comparator/comp_2bit.sv:11.37-11.60" *)
  wire _07_;
  (* src = "./Comparator/comp_2bit.sv:10.26-10.31" *)
  wire _08_;
  (* src = "./Comparator/comp_2bit.sv:10.55-10.60" *)
  wire _09_;
  (* src = "./Comparator/comp_2bit.sv:11.18-11.23" *)
  wire _10_;
  (* src = "./Comparator/comp_2bit.sv:11.47-11.52" *)
  wire _11_;
  (* src = "./Comparator/comp_2bit.sv:6.9-6.15" *)
  wire Eq_MSB;
  assign _00_[0] = A[0] ^(* src = "./Comparator/comp_2bit.sv:9.17-9.21" *)  B[0];
  assign _00_[1] = A[1] ^(* src = "./Comparator/comp_2bit.sv:9.17-9.21" *)  B[1];
  assign _01_ = _00_[0] |(* src = "./Comparator/comp_2bit.sv:9.17-9.21" *)  _00_[1];
  assign _08_ = ~(* src = "./Comparator/comp_2bit.sv:10.26-10.31" *) B[1];
  assign _09_ = ~(* src = "./Comparator/comp_2bit.sv:10.55-10.60" *) B[0];
  assign _10_ = ~(* src = "./Comparator/comp_2bit.sv:11.18-11.23" *) A[1];
  assign _11_ = ~(* src = "./Comparator/comp_2bit.sv:11.47-11.52" *) A[0];
  assign Eq_MSB = ~(* src = "./Comparator/comp_2bit.sv:7.19-7.33" *) _00_[1];
  assign _02_ = A[1] &(* src = "./Comparator/comp_2bit.sv:10.18-10.31" *)  _08_;
  assign _03_ = Eq_MSB &(* src = "./Comparator/comp_2bit.sv:10.37-10.51" *)  A[0];
  assign _04_ = _03_ &(* src = "./Comparator/comp_2bit.sv:10.37-10.60" *)  _09_;
  assign Gt = _02_ |(* src = "./Comparator/comp_2bit.sv:10.17-10.61" *)  _04_;
  assign _05_ = _10_ &(* src = "./Comparator/comp_2bit.sv:11.18-11.31" *)  B[1];
  assign _06_ = Eq_MSB &(* src = "./Comparator/comp_2bit.sv:11.37-11.52" *)  _11_;
  assign _07_ = _06_ &(* src = "./Comparator/comp_2bit.sv:11.37-11.60" *)  B[0];
  assign Lt = _05_ |(* src = "./Comparator/comp_2bit.sv:11.17-11.61" *)  _07_;
  assign Eq = ~(* src = "./Comparator/comp_2bit.sv:9.16-9.32" *) _01_;
endmodule
