/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./counter_with_load/count.sv:7.1-27.10" *)
module Counter(Cnt, load, load_val, clk, rst);
  (* src = "./counter_with_load/count.sv:8.23-8.26" *)
  output [15:0] Cnt;
  reg [15:0] Cnt;
  (* src = "./counter_with_load/count.sv:9.15-9.19" *)
  input load;
  wire load;
  (* src = "./counter_with_load/count.sv:10.22-10.30" *)
  input [15:0] load_val;
  wire [15:0] load_val;
  (* src = "./counter_with_load/count.sv:9.20-9.23" *)
  input clk;
  wire clk;
  (* src = "./counter_with_load/count.sv:9.24-9.27" *)
  input rst;
  wire rst;
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  wire [15:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire [7:0] _016_;
  wire [3:0] _017_;
  wire [1:0] _018_;
  wire _019_;
  (* force_downto = 32'd1 *)
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "15" *)
  wire [15:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:287.21-287.22" *)
  wire [15:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:270.26-270.27" *)
  wire [15:0] _022_;
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _023_;
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _024_;
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _025_;
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _026_;
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _027_;
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _028_;
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _029_;
  (* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _030_;
  (* src = "./counter_with_load/count.sv:24.32-24.71" *)
  wire [15:0] _031_;
  (* src = "./counter_with_load/count.sv:12.16-12.27" *)
  reg [15:0] load_val_ff;
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[3] <= 1'h0;
    else if (load) load_val_ff[3] <= load_val[3];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[4] <= 1'h0;
    else if (load) load_val_ff[4] <= load_val[4];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[5] <= 1'h0;
    else if (load) load_val_ff[5] <= load_val[5];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[6] <= 1'h0;
    else if (load) load_val_ff[6] <= load_val[6];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[7] <= 1'h0;
    else if (load) load_val_ff[7] <= load_val[7];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[8] <= 1'h0;
    else if (load) load_val_ff[8] <= load_val[8];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[9] <= 1'h0;
    else if (load) load_val_ff[9] <= load_val[9];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[10] <= 1'h0;
    else if (load) load_val_ff[10] <= load_val[10];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[11] <= 1'h0;
    else if (load) load_val_ff[11] <= load_val[11];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[12] <= 1'h0;
    else if (load) load_val_ff[12] <= load_val[12];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[13] <= 1'h0;
    else if (load) load_val_ff[13] <= load_val[13];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[14] <= 1'h0;
    else if (load) load_val_ff[14] <= load_val[14];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[15] <= 1'h0;
    else if (load) load_val_ff[15] <= load_val[15];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[0] <= 1'h0;
    else Cnt[0] <= _000_[0];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[1] <= 1'h0;
    else Cnt[1] <= _000_[1];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[2] <= 1'h0;
    else Cnt[2] <= _000_[2];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[3] <= 1'h0;
    else Cnt[3] <= _000_[3];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[4] <= 1'h0;
    else Cnt[4] <= _000_[4];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[5] <= 1'h0;
    else Cnt[5] <= _000_[5];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[6] <= 1'h0;
    else Cnt[6] <= _000_[6];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[7] <= 1'h0;
    else Cnt[7] <= _000_[7];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[8] <= 1'h0;
    else Cnt[8] <= _000_[8];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[9] <= 1'h0;
    else Cnt[9] <= _000_[9];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[10] <= 1'h0;
    else Cnt[10] <= _000_[10];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[11] <= 1'h0;
    else Cnt[11] <= _000_[11];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[12] <= 1'h0;
    else Cnt[12] <= _000_[12];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[13] <= 1'h0;
    else Cnt[13] <= _000_[13];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[14] <= 1'h0;
    else Cnt[14] <= _000_[14];
  (* src = "./counter_with_load/count.sv:19.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[15] <= 1'h0;
    else Cnt[15] <= _000_[15];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[0] <= 1'h0;
    else if (load) load_val_ff[0] <= load_val[0];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[1] <= 1'h0;
    else if (load) load_val_ff[1] <= load_val[1];
  (* src = "./counter_with_load/count.sv:14.3-17.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) load_val_ff[2] <= 1'h0;
    else if (load) load_val_ff[2] <= load_val[2];
  assign _021_[0] = ~Cnt[0];
  assign _001_ = ~Cnt[15];
  assign _002_ = ~Cnt[14];
  assign _003_ = ~Cnt[13];
  assign _004_ = ~Cnt[12];
  assign _005_ = ~Cnt[11];
  assign _006_ = ~Cnt[10];
  assign _007_ = ~Cnt[9];
  assign _008_ = ~Cnt[8];
  assign _009_ = ~Cnt[7];
  assign _010_ = ~Cnt[6];
  assign _011_ = ~Cnt[5];
  assign _012_ = ~Cnt[4];
  assign _013_ = ~Cnt[3];
  assign _014_ = ~Cnt[2];
  assign _015_ = ~Cnt[1];
  assign _022_[1] = Cnt[1] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  Cnt[0];
  assign _022_[2] = Cnt[2] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[1];
  assign _022_[3] = Cnt[3] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[2];
  assign _022_[4] = Cnt[4] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[3];
  assign _022_[5] = Cnt[5] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[4];
  assign _022_[6] = Cnt[6] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[5];
  assign _022_[7] = Cnt[7] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[6];
  assign _022_[8] = Cnt[8] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[7];
  assign _022_[9] = Cnt[9] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[8];
  assign _022_[10] = Cnt[10] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[9];
  assign _022_[11] = Cnt[11] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[10];
  assign _022_[12] = Cnt[12] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[11];
  assign _022_[13] = Cnt[13] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[12];
  assign _022_[14] = Cnt[14] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[13];
  assign _022_[15] = Cnt[15] ^(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:296.13-296.25" *)  _020_[14];
  assign _020_[8] = Cnt[8] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[7];
  assign _020_[4] = Cnt[4] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[3];
  assign _020_[10] = Cnt[10] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[9];
  assign _020_[2] = Cnt[2] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[1];
  assign _020_[13] = _028_ &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[11];
  assign _020_[9] = _026_ &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[7];
  assign _020_[12] = Cnt[12] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[11];
  assign _020_[5] = _024_ &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[3];
  assign _020_[11] = _030_ &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[7];
  assign _020_[14] = Cnt[14] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[13];
  assign _020_[7] = _029_ &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _020_[3];
  assign _030_ = _027_ &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _026_;
  assign _029_ = _025_ &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _024_;
  assign _020_[3] = _023_ &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _020_[1];
  assign _028_ = Cnt[13] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[12];
  assign _027_ = Cnt[11] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[10];
  assign _026_ = Cnt[9] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[8];
  assign _025_ = Cnt[7] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[6];
  assign _024_ = Cnt[5] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[4];
  assign _023_ = Cnt[3] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[2];
  assign _020_[6] = Cnt[6] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _020_[5];
  assign _020_[1] = Cnt[1] &(* src = "./counter_with_load/count.sv:24.60-24.71|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[0];
  assign _016_[0] = _021_[0] |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _015_;
  assign _016_[1] = _014_ |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _013_;
  assign _016_[2] = _012_ |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _011_;
  assign _016_[3] = _010_ |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _009_;
  assign _016_[4] = _008_ |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _007_;
  assign _016_[5] = _006_ |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _005_;
  assign _016_[6] = _004_ |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _003_;
  assign _016_[7] = _002_ |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _001_;
  assign _017_[0] = _016_[0] |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _016_[1];
  assign _017_[1] = _016_[2] |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _016_[3];
  assign _017_[2] = _016_[4] |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _016_[5];
  assign _017_[3] = _016_[6] |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _016_[7];
  assign _018_[0] = _017_[0] |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _017_[1];
  assign _018_[1] = _017_[2] |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _017_[3];
  assign _019_ = _018_[0] |(* src = "./counter_with_load/count.sv:24.33-24.42" *)  _018_[1];
  assign _031_[0] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _021_[0] : load_val_ff[0];
  assign _031_[1] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[1] : load_val_ff[1];
  assign _031_[2] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[2] : load_val_ff[2];
  assign _031_[3] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[3] : load_val_ff[3];
  assign _031_[4] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[4] : load_val_ff[4];
  assign _031_[5] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[5] : load_val_ff[5];
  assign _031_[6] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[6] : load_val_ff[6];
  assign _031_[7] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[7] : load_val_ff[7];
  assign _031_[8] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[8] : load_val_ff[8];
  assign _031_[9] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[9] : load_val_ff[9];
  assign _031_[10] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[10] : load_val_ff[10];
  assign _031_[11] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[11] : load_val_ff[11];
  assign _031_[12] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[12] : load_val_ff[12];
  assign _031_[13] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[13] : load_val_ff[13];
  assign _031_[14] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[14] : load_val_ff[14];
  assign _031_[15] = _019_ ? (* src = "./counter_with_load/count.sv:24.32-24.71" *) _022_[15] : load_val_ff[15];
  assign _000_[0] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[0] : _031_[0];
  assign _000_[1] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[1] : _031_[1];
  assign _000_[2] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[2] : _031_[2];
  assign _000_[3] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[3] : _031_[3];
  assign _000_[4] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[4] : _031_[4];
  assign _000_[5] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[5] : _031_[5];
  assign _000_[6] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[6] : _031_[6];
  assign _000_[7] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[7] : _031_[7];
  assign _000_[8] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[8] : _031_[8];
  assign _000_[9] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[9] : _031_[9];
  assign _000_[10] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[10] : _031_[10];
  assign _000_[11] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[11] : _031_[11];
  assign _000_[12] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[12] : _031_[12];
  assign _000_[13] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[13] : _031_[13];
  assign _000_[14] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[14] : _031_[14];
  assign _000_[15] = load ? (* src = "./counter_with_load/count.sv:24.14-24.71" *) load_val[15] : _031_[15];
  assign _022_[0] = _021_[0];
  assign _020_[0] = Cnt[0];
  assign _021_[15:1] = Cnt[15:1];
endmodule
