/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Sequence_Detector_2/Detector.sv:4.1-53.10" *)
module Seq_Det(In, Out, clk, rst);
  (* src = "./Sequence_Detector_2/Detector.sv:7.15-7.17" *)
  input In;
  wire In;
  (* src = "./Sequence_Detector_2/Detector.sv:6.16-6.19" *)
  output Out;
  wire Out;
  (* src = "./Sequence_Detector_2/Detector.sv:7.18-7.21" *)
  input clk;
  wire clk;
  (* src = "./Sequence_Detector_2/Detector.sv:7.22-7.25" *)
  input rst;
  wire rst;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [2:0] _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [2:0] _16_;
  wire _17_;
  wire [2:0] _18_;
  wire _19_;
  wire [2:0] _20_;
  wire _21_;
  wire [2:0] _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  (* force_downto = 32'd1 *)
  (* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:579.28-579.29" *)
  wire [17:0] _28_;
  (* force_downto = 32'd1 *)
  (* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:591.28-591.35" *)
  wire [17:0] _29_;
  (* force_downto = 32'd1 *)
  (* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:581.22-581.23" *)
  wire [5:0] _30_;
  (* force_downto = 32'd1 *)
  (* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:586.19-586.22" *)
  wire [2:0] _31_;
  (* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:605.13-605.15" *)
  wire _32_;
  (* enum_type = "$enum0" *)
  (* enum_value_000 = "\\S0" *)
  (* enum_value_001 = "\\S1" *)
  (* enum_value_010 = "\\S2" *)
  (* enum_value_011 = "\\S3" *)
  (* enum_value_100 = "\\S4" *)
  (* enum_value_101 = "\\S5" *)
  (* src = "./Sequence_Detector_2/Detector.sv:15.20-15.28" *)
  (* wiretype = "\\state" *)
  wire [2:0] nx_state;
  (* enum_type = "$enum0" *)
  (* enum_value_000 = "\\S0" *)
  (* enum_value_001 = "\\S1" *)
  (* enum_value_010 = "\\S2" *)
  (* enum_value_011 = "\\S3" *)
  (* enum_value_100 = "\\S4" *)
  (* enum_value_101 = "\\S5" *)
  (* src = "./Sequence_Detector_2/Detector.sv:15.11-15.19" *)
  (* wiretype = "\\state" *)
  reg [2:0] pr_state;
  (* src = "./Sequence_Detector_2/Detector.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[0] <= 1'h0;
    else if (_03_) pr_state[0] <= nx_state[0];
  (* src = "./Sequence_Detector_2/Detector.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[1] <= 1'h0;
    else if (_03_) pr_state[1] <= nx_state[1];
  (* src = "./Sequence_Detector_2/Detector.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[2] <= 1'h0;
    else if (_03_) pr_state[2] <= nx_state[2];
  assign _04_ = ~pr_state[1];
  assign _05_ = ~pr_state[0];
  assign _06_ = ~pr_state[2];
  assign _29_[15] = _28_[15] &(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:593.44-593.84" *)  _30_[5];
  assign _29_[16] = _28_[16] &(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:593.44-593.84" *)  _30_[5];
  assign _29_[13] = _28_[13] &(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:593.44-593.84" *)  _30_[4];
  assign _29_[12] = _28_[12] &(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:593.44-593.84" *)  _30_[4];
  assign _29_[9] = In &(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:593.44-593.84" *)  _30_[3];
  assign _29_[6] = In &(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:593.44-593.84" *)  _30_[2];
  assign _29_[8] = _28_[1] &(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:593.44-593.84" *)  _30_[2];
  assign _29_[3] = In &(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:593.44-593.84" *)  _30_[1];
  assign _29_[1] = _28_[1] &(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:593.44-593.84" *)  Out;
  assign _09_ = _02_ & _01_;
  assign _03_ = _09_ & _00_;
  assign _10_[0] = _30_[1] | _30_[2];
  assign _10_[1] = _30_[3] | _30_[4];
  assign _10_[2] = _30_[5] | Out;
  assign _11_ = _10_[0] | _10_[1];
  assign _02_ = _11_ | _10_[2];
  assign _01_ = _28_[1] | _08_;
  assign _00_ = In | _07_;
  assign _24_ = _12_ |(* src = "./Sequence_Detector_2/Detector.sv:40.15-40.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *)  _06_;
  assign _13_ = _05_ |(* src = "./Sequence_Detector_2/Detector.sv:36.15-36.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *)  _04_;
  assign _25_ = _13_ |(* src = "./Sequence_Detector_2/Detector.sv:36.15-36.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *)  pr_state[2];
  assign _14_ = pr_state[0] |(* src = "./Sequence_Detector_2/Detector.sv:32.15-32.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *)  _04_;
  assign _26_ = _14_ |(* src = "./Sequence_Detector_2/Detector.sv:32.15-32.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *)  pr_state[2];
  assign _15_ = _05_ |(* src = "./Sequence_Detector_2/Detector.sv:29.15-29.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *)  pr_state[1];
  assign _08_ = _15_ |(* src = "./Sequence_Detector_2/Detector.sv:29.15-29.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *)  pr_state[2];
  assign _27_ = _15_ |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *)  _06_;
  assign _16_[2] = _29_[12] |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _29_[16];
  assign _17_ = _29_[3] |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _29_[8];
  assign _31_[2] = _17_ |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _16_[2];
  assign _18_[2] = _29_[13] |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _29_[16];
  assign _19_ = _29_[1] |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _29_[9];
  assign _31_[1] = _19_ |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _18_[2];
  assign _20_[0] = Out |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _29_[3];
  assign _20_[1] = _29_[6] |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _29_[9];
  assign _20_[2] = _29_[12] |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _29_[15];
  assign _21_ = _20_[0] |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _20_[1];
  assign _31_[0] = _21_ |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:601.20-601.31" *)  _20_[2];
  assign _22_[0] = Out |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:605.13-605.15" *)  _30_[1];
  assign _22_[1] = _30_[2] |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:605.13-605.15" *)  _30_[3];
  assign _22_[2] = _30_[4] |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:605.13-605.15" *)  _30_[5];
  assign _23_ = _22_[0] |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:605.13-605.15" *)  _22_[1];
  assign _32_ = _23_ |(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:605.13-605.15" *)  _22_[2];
  assign _12_ = pr_state[0] |(* src = "./Sequence_Detector_2/Detector.sv:26.20-26.20|./Sequence_Detector_2/Detector.sv:26.5-50.14" *)  pr_state[1];
  assign _07_ = _12_ |(* src = "./Sequence_Detector_2/Detector.sv:26.20-26.20|./Sequence_Detector_2/Detector.sv:26.5-50.14" *)  pr_state[2];
  assign _30_[1] = ~(* src = "./Sequence_Detector_2/Detector.sv:40.15-40.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *) _24_;
  assign _30_[2] = ~(* src = "./Sequence_Detector_2/Detector.sv:36.15-36.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *) _25_;
  assign _30_[3] = ~(* src = "./Sequence_Detector_2/Detector.sv:32.15-32.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *) _26_;
  assign _30_[4] = ~(* src = "./Sequence_Detector_2/Detector.sv:29.15-29.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *) _08_;
  assign _30_[5] = ~(* src = "./Sequence_Detector_2/Detector.sv:26.20-26.20|./Sequence_Detector_2/Detector.sv:26.5-50.14" *) _07_;
  assign _28_[1] = ~(* src = "./Sequence_Detector_2/Detector.sv:46.18-46.26|./Sequence_Detector_2/Detector.sv:46.14-47.33" *) In;
  assign _28_[12] = In ? (* src = "./Sequence_Detector_2/Detector.sv:31.18-31.26|./Sequence_Detector_2/Detector.sv:31.14-31.42" *) 1'hx : 1'h0;
  assign _28_[13] = In ? (* src = "./Sequence_Detector_2/Detector.sv:31.18-31.26|./Sequence_Detector_2/Detector.sv:31.14-31.42" *) 1'hx : 1'h1;
  assign _28_[15] = In ? (* src = "./Sequence_Detector_2/Detector.sv:28.18-28.26|./Sequence_Detector_2/Detector.sv:28.14-28.42" *) 1'h1 : 1'hx;
  assign _28_[16] = In ? (* src = "./Sequence_Detector_2/Detector.sv:28.18-28.26|./Sequence_Detector_2/Detector.sv:28.14-28.42" *) 1'h0 : 1'hx;
  assign Out = ~(* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14" *) _27_;
  assign nx_state[0] = _32_ ? (* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:605.13-605.25" *) _31_[0] : 1'hx;
  assign nx_state[1] = _32_ ? (* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:605.13-605.25" *) _31_[1] : 1'hx;
  assign nx_state[2] = _32_ ? (* src = "./Sequence_Detector_2/Detector.sv:44.15-44.15|./Sequence_Detector_2/Detector.sv:26.5-50.14|/share/techmap.v:605.13-605.25" *) _31_[2] : 1'hx;
  assign { _28_[17], _28_[14], _28_[11:2], _28_[0] } = { _28_[16], _28_[12], 1'h0, In, In, _28_[1], 1'h0, In, In, 1'h0, In, 2'h1 };
  assign _30_[0] = Out;
  assign _16_[1:0] = { _29_[8], _29_[3] };
  assign _18_[1:0] = { _29_[9], _29_[1] };
  assign { _29_[17], _29_[14], _29_[11:10], _29_[7], _29_[5:4], _29_[2], _29_[0] } = { _29_[16], _29_[12], 1'h0, _29_[9], 1'h0, _29_[3], 2'h0, Out };
endmodule
