/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Flip_Flops/FF.sv:41.1-50.10" *)
module JKFF(Qj, J, K, clk, rst);
  (* src = "./Flip_Flops/FF.sv:43.16-43.18" *)
  output Qj;
  reg Qj;
  (* src = "./Flip_Flops/FF.sv:42.15-42.16" *)
  input J;
  wire J;
  (* src = "./Flip_Flops/FF.sv:42.17-42.18" *)
  input K;
  wire K;
  (* src = "./Flip_Flops/FF.sv:42.19-42.22" *)
  input clk;
  wire clk;
  (* src = "./Flip_Flops/FF.sv:42.23-42.26" *)
  input rst;
  wire rst;
  (* src = "./Flip_Flops/FF.sv:45.3-48.6" *)
  wire _00_;
  (* src = "./Flip_Flops/FF.sv:47.17-47.25" *)
  wire _01_;
  (* src = "./Flip_Flops/FF.sv:47.31-47.39" *)
  wire _02_;
  (* src = "./Flip_Flops/FF.sv:47.22-47.25" *)
  wire _03_;
  (* src = "./Flip_Flops/FF.sv:47.31-47.33" *)
  wire _04_;
  (* src = "./Flip_Flops/FF.sv:45.3-48.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Qj <= 1'h0;
    else Qj <= _00_;
  assign _03_ = ~(* src = "./Flip_Flops/FF.sv:47.22-47.25" *) Qj;
  assign _04_ = ~(* src = "./Flip_Flops/FF.sv:47.31-47.33" *) K;
  assign _01_ = J &(* src = "./Flip_Flops/FF.sv:47.17-47.25" *)  _03_;
  assign _02_ = _04_ &(* src = "./Flip_Flops/FF.sv:47.31-47.39" *)  Qj;
  assign _00_ = _01_ |(* src = "./Flip_Flops/FF.sv:47.16-47.40" *)  _02_;
endmodule
