/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Gray_Counter/gray_cnt.sv:3.1-21.10" *)
module gray_cnt(gr_cnt, clk, rst);
  (* src = "./Gray_Counter/gray_cnt.sv:5.22-5.28" *)
  output [3:0] gr_cnt;
  reg [3:0] gr_cnt;
  (* src = "./Gray_Counter/gray_cnt.sv:6.15-6.18" *)
  input clk;
  wire clk;
  (* src = "./Gray_Counter/gray_cnt.sv:6.19-6.22" *)
  input rst;
  wire rst;
  (* force_downto = 32'd1 *)
  (* src = "./Gray_Counter/gray_cnt.sv:17.19-17.29|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _00_;
  (* src = "./Gray_Counter/gray_cnt.sv:8.19-8.22" *)
  wire [3:0] bin;
  (* src = "./Gray_Counter/gray_cnt.sv:8.24-8.30" *)
  wire [3:0] br_cnt;
  (* src = "./Gray_Counter/gray_cnt.sv:8.15-8.17" *)
  wire [3:0] gr;
  (* src = "./Gray_Counter/gray_cnt.sv:10.3-13.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) gr_cnt[1] <= 1'h0;
    else gr_cnt[1] <= gr[1];
  (* src = "./Gray_Counter/gray_cnt.sv:10.3-13.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) gr_cnt[2] <= 1'h0;
    else gr_cnt[2] <= gr[2];
  (* src = "./Gray_Counter/gray_cnt.sv:10.3-13.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) gr_cnt[3] <= 1'h0;
    else gr_cnt[3] <= br_cnt[3];
  (* src = "./Gray_Counter/gray_cnt.sv:10.3-13.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) gr_cnt[0] <= 1'h0;
    else gr_cnt[0] <= gr[0];
  assign br_cnt[0] = ~bin[0];
  assign br_cnt[1] = bin[1] ^(* src = "./Gray_Counter/gray_cnt.sv:17.19-17.29|/share/techmap.v:296.13-296.25" *)  bin[0];
  assign br_cnt[2] = bin[2] ^(* src = "./Gray_Counter/gray_cnt.sv:17.19-17.29|/share/techmap.v:296.13-296.25" *)  _00_[1];
  assign br_cnt[3] = gr_cnt[3] ^(* src = "./Gray_Counter/gray_cnt.sv:17.19-17.29|/share/techmap.v:296.13-296.25" *)  _00_[2];
  assign _00_[2] = bin[2] &(* src = "./Gray_Counter/gray_cnt.sv:17.19-17.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _00_[1];
  assign _00_[1] = bin[1] &(* src = "./Gray_Counter/gray_cnt.sv:17.19-17.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  bin[0];
  assign bin[0] = bin[1] ^(* src = "./Gray_Counter/gray_cnt.sv:15.65-15.83" *)  gr_cnt[0];
  assign bin[1] = bin[2] ^(* src = "./Gray_Counter/gray_cnt.sv:15.46-15.64" *)  gr_cnt[1];
  assign bin[2] = gr_cnt[3] ^(* src = "./Gray_Counter/gray_cnt.sv:15.27-15.45" *)  gr_cnt[2];
  assign gr[0] = br_cnt[1] ^(* src = "./Gray_Counter/gray_cnt.sv:19.66-19.85" *)  br_cnt[0];
  assign gr[1] = br_cnt[2] ^(* src = "./Gray_Counter/gray_cnt.sv:19.46-19.65" *)  br_cnt[1];
  assign gr[2] = br_cnt[3] ^(* src = "./Gray_Counter/gray_cnt.sv:19.26-19.45" *)  br_cnt[2];
  assign _00_[0] = bin[0];
  assign bin[3] = gr_cnt[3];
  assign gr[3] = br_cnt[3];
endmodule
