/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:2.1-21.10" *)
module lfsr(Q, clk, rst);
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:3.21-3.22" *)
  output [3:0] Q;
  reg [3:0] Q;
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:4.15-4.18" *)
  input clk;
  wire clk;
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:4.19-4.22" *)
  input rst;
  wire rst;
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:9.34-9.39" *)
  wire _00_;
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:9.18-9.29" *)
  wire _01_;
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:9.17-9.40" *)
  wire _02_;
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:6.9-6.11" *)
  wire Fo;
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:10.3-13.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[0] <= 1'h0;
    else Q[0] <= Q[1];
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:10.3-13.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[1] <= 1'h0;
    else Q[1] <= Q[2];
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:10.3-13.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[2] <= 1'h0;
    else Q[2] <= Q[3];
  (* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:10.3-13.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[3] <= 1'h1;
    else Q[3] <= Fo;
  assign _01_ = Q[0] ^(* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:9.18-9.29" *)  Q[1];
  assign _02_ = _01_ ^(* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:9.17-9.40" *)  _00_;
  assign _00_ = ~(* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:9.34-9.39" *) Q[2];
  assign Fo = ~(* src = "./Linear_Feedback_Shift_Reg/LFSR.sv:9.15-9.41" *) _02_;
endmodule
