/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* dynports =  1  *)
(* top =  1  *)
(* src = "./log2_function/log2.sv:2.1-33.10" *)
module log2(clk, rst, value, result, valid);
  (* src = "./log2_function/log2.sv:3.17-3.20" *)
  input clk;
  wire clk;
  (* src = "./log2_function/log2.sv:4.17-4.20" *)
  input rst;
  wire rst;
  (* src = "./log2_function/log2.sv:5.25-5.30" *)
  input [7:0] value;
  wire [7:0] value;
  (* src = "./log2_function/log2.sv:6.26-6.32" *)
  output [2:0] result;
  reg [2:0] result;
  (* src = "./log2_function/log2.sv:7.18-7.23" *)
  output valid;
  reg valid;
  (* src = "./log2_function/log2.sv:12.3-32.8" *)
  wire [2:0] _000_;
  (* src = "./log2_function/log2.sv:12.3-32.8" *)
  wire _001_;
  wire _002_;
  wire [3:0] _003_;
  wire [1:0] _004_;
  wire _005_;
  wire [3:0] _006_;
  wire [1:0] _007_;
  wire [3:0] _008_;
  wire [1:0] _009_;
  wire [3:0] _010_;
  wire [1:0] _011_;
  wire [3:0] _012_;
  wire [1:0] _013_;
  wire [3:0] _014_;
  wire [1:0] _015_;
  wire [3:0] _016_;
  wire [1:0] _017_;
  wire [3:0] _018_;
  wire [1:0] _019_;
  wire [3:0] _020_;
  wire [1:0] _021_;
  wire [15:0] _022_;
  wire [7:0] _023_;
  wire [3:0] _024_;
  wire [15:0] _025_;
  wire [7:0] _026_;
  wire [3:0] _027_;
  wire [15:0] _028_;
  wire [7:0] _029_;
  wire [3:0] _030_;
  wire [15:0] _031_;
  wire [7:0] _032_;
  wire [3:0] _033_;
  wire [15:0] _034_;
  wire [7:0] _035_;
  wire [3:0] _036_;
  wire [15:0] _037_;
  wire [7:0] _038_;
  wire [3:0] _039_;
  wire [15:0] _040_;
  wire [7:0] _041_;
  wire [3:0] _042_;
  wire [15:0] _043_;
  wire [7:0] _044_;
  wire [3:0] _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  (* src = "./log2_function/log2.sv:18.17-18.27" *)
  wire _055_;
  (* src = "./log2_function/log2.sv:27.29-27.46" *)
  wire _056_;
  (* src = "./log2_function/log2.sv:27.29-27.46" *)
  wire _057_;
  (* src = "./log2_function/log2.sv:27.29-27.46" *)
  wire _058_;
  (* src = "./log2_function/log2.sv:27.29-27.46" *)
  wire _059_;
  (* src = "./log2_function/log2.sv:27.29-27.46" *)
  wire _060_;
  (* src = "./log2_function/log2.sv:27.29-27.46" *)
  wire _061_;
  (* src = "./log2_function/log2.sv:27.29-27.46" *)
  wire _062_;
  (* src = "./log2_function/log2.sv:27.29-27.46" *)
  wire _063_;
  (* src = "./log2_function/log2.sv:25.21-25.38" *)
  wire _064_;
  (* src = "./log2_function/log2.sv:25.21-25.38" *)
  wire _065_;
  (* src = "./log2_function/log2.sv:25.21-25.38" *)
  wire _066_;
  (* src = "./log2_function/log2.sv:25.21-25.38" *)
  wire _067_;
  (* src = "./log2_function/log2.sv:25.21-25.38" *)
  wire _068_;
  (* src = "./log2_function/log2.sv:25.21-25.38" *)
  wire _069_;
  (* src = "./log2_function/log2.sv:25.21-25.38" *)
  wire _070_;
  (* src = "./log2_function/log2.sv:25.21-25.38" *)
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire [2:0] _080_;
  wire [2:0] _081_;
  wire [2:0] _082_;
  wire [2:0] _083_;
  wire [2:0] _084_;
  wire [2:0] _085_;
  wire [2:0] _086_;
  wire [2:0] _087_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [31:0] _088_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:287.21-287.22" *)
  wire [31:0] _089_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:270.26-270.27" *)
  (* unused_bits = "2 3 4 5 6 7" *)
  wire [31:0] _090_;
  wire _091_;
  wire _092_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "4 5 6" *)
  wire [31:0] _093_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:270.26-270.27" *)
  (* unused_bits = "3 4 5 6 7" *)
  wire [31:0] _094_;
  wire _095_;
  wire _096_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "4 5 6" *)
  wire [31:0] _097_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:270.26-270.27" *)
  (* unused_bits = "4 5 6 7" *)
  wire [31:0] _098_;
  wire _099_;
  wire _100_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "4 5 6" *)
  wire [31:0] _101_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:270.26-270.27" *)
  (* unused_bits = "4 5 6 7" *)
  wire [31:0] _102_;
  wire _103_;
  wire _104_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "4 5 6" *)
  wire [31:0] _105_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:270.26-270.27" *)
  (* unused_bits = "4 5 6 7" *)
  wire [31:0] _106_;
  wire _107_;
  wire _108_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "4 5 6" *)
  wire [31:0] _109_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:270.26-270.27" *)
  (* unused_bits = "4 5 6 7" *)
  wire [31:0] _110_;
  wire _111_;
  wire _112_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "4 5 6" *)
  wire [31:0] _113_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:270.26-270.27" *)
  (* unused_bits = "4 5 6 7" *)
  wire [31:0] _114_;
  wire _115_;
  wire _116_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [31:0] _117_;
  (* force_downto = 32'd1 *)
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:270.26-270.27" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [31:0] _118_;
  wire _119_;
  wire _120_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _121_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _122_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _123_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _124_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _125_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _126_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _127_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _128_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _129_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _130_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _131_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _132_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _133_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _134_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _135_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _136_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _137_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _138_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _139_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _140_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _141_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _142_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _143_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _144_;
  (* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _145_;
  (* \always_ff  = 32'd1 *)
  (* src = "./log2_function/log2.sv:12.3-32.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) result[0] <= 1'h0;
    else if (_002_) result[0] <= _000_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./log2_function/log2.sv:12.3-32.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) result[1] <= 1'h0;
    else if (_002_) result[1] <= _000_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "./log2_function/log2.sv:12.3-32.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) result[2] <= 1'h0;
    else if (_002_) result[2] <= _000_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "./log2_function/log2.sv:12.3-32.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) valid <= 1'h0;
    else if (_002_) valid <= _001_;
  assign _089_[3] = ~value[3];
  assign _089_[7] = ~value[7];
  assign _089_[5] = ~value[5];
  assign _089_[4] = ~value[4];
  assign _089_[0] = ~value[0];
  assign _089_[6] = ~value[6];
  assign _089_[2] = ~value[2];
  assign _090_[1] = ~value[1];
  assign _114_[8] = ~_113_[7];
  assign _110_[8] = ~_109_[7];
  assign _106_[8] = ~_105_[7];
  assign _102_[8] = ~_101_[7];
  assign _098_[8] = ~_097_[7];
  assign _094_[8] = ~_093_[7];
  assign _090_[8] = ~_088_[7];
  assign _118_[8] = ~_117_[7];
  assign _117_[7] = _126_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _145_;
  assign _145_ = _023_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _117_[3];
  assign _126_ = _125_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _122_;
  assign _122_ = _022_[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _124_;
  assign _117_[3] = _093_[3] |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _144_;
  assign _144_ = _022_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _117_[1];
  assign _124_ = value[5] |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _034_[2];
  assign _093_[3] = value[3] |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _028_[1];
  assign _117_[1] = value[1] |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _022_[0];
  assign _022_[0] = _090_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  value[0];
  assign _088_[7] = _126_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _123_;
  assign _123_ = _023_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _088_[3];
  assign _088_[3] = _093_[3] |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _121_;
  assign _121_ = _022_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  value[1];
  assign _093_[7] = _126_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _127_;
  assign _127_ = _023_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _093_[3];
  assign _034_[2] = _089_[5] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  value[4];
  assign _097_[7] = _126_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _129_;
  assign _129_ = _023_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _097_[3];
  assign _097_[3] = _128_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _031_[1];
  assign _022_[3] = _089_[7] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _089_[6];
  assign _040_[3] = _089_[7] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  value[6];
  assign _031_[1] = value[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _089_[2];
  assign _128_ = value[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  value[2];
  assign _101_[7] = _132_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _131_;
  assign _131_ = _035_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _101_[3];
  assign _035_[1] = _022_[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _034_[2];
  assign _132_ = _125_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _130_;
  assign _130_ = _022_[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  value[5];
  assign _101_[3] = _093_[3] |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _022_[1];
  assign _125_ = value[7] |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _040_[3];
  assign _105_[7] = _136_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _135_;
  assign _135_ = _038_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _101_[3];
  assign _038_[1] = _022_[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _037_[2];
  assign _136_ = _125_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _134_;
  assign _134_ = _022_[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _133_;
  assign _037_[2] = value[5] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _089_[4];
  assign _133_ = value[5] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  value[4];
  assign _028_[1] = _089_[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  value[2];
  assign _109_[7] = _139_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _138_;
  assign _138_ = _041_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _101_[3];
  assign _139_ = value[7] |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _137_;
  assign _137_ = _040_[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _124_;
  assign _022_[2] = _089_[5] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _089_[4];
  assign _022_[1] = _089_[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _089_[2];
  assign _113_[7] = _143_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _142_;
  assign _142_ = _044_[1] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _101_[3];
  assign _143_ = _140_ |(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _141_;
  assign _141_ = _043_[3] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _124_;
  assign _140_ = value[7] &(* src = "./log2_function/log2.sv:25.21-25.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  value[6];
  assign _120_ = _118_[8] | _024_[0];
  assign _092_ = _090_[8] | _027_[0];
  assign _096_ = _094_[8] | _030_[0];
  assign _100_ = _098_[8] | _033_[0];
  assign _104_ = _102_[8] | _036_[0];
  assign _108_ = _106_[8] | _039_[0];
  assign _112_ = _110_[8] | _042_[0];
  assign _116_ = _114_[8] | _045_[0];
  assign _003_[0] = _055_ | _071_;
  assign _003_[1] = _064_ | _065_;
  assign _003_[2] = _066_ | _067_;
  assign _003_[3] = _068_ | _069_;
  assign _004_[0] = _003_[0] | _003_[1];
  assign _004_[1] = _003_[2] | _003_[3];
  assign _005_ = _004_[0] | _004_[1];
  assign _002_ = _005_ | _070_;
  assign _006_[0] = _089_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  value[1];
  assign _007_[0] = _006_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _006_[1];
  assign _047_ = _007_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _007_[1];
  assign _008_[0] = value[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _090_[1];
  assign _009_[0] = _008_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _006_[1];
  assign _048_ = _009_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _007_[1];
  assign _010_[1] = _089_[2] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  value[3];
  assign _011_[0] = _010_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _010_[1];
  assign _049_ = _011_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _007_[1];
  assign _012_[1] = value[2] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _089_[3];
  assign _013_[0] = _010_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _012_[1];
  assign _007_[1] = _006_[2] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _006_[3];
  assign _050_ = _013_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _007_[1];
  assign _014_[2] = _089_[4] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  value[5];
  assign _015_[1] = _014_[2] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _006_[3];
  assign _051_ = _015_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _015_[1];
  assign _016_[2] = value[4] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _089_[5];
  assign _006_[3] = value[6] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  value[7];
  assign _017_[1] = _016_[2] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _006_[3];
  assign _052_ = _015_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _017_[1];
  assign _018_[3] = _089_[6] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  value[7];
  assign _019_[1] = _006_[2] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _018_[3];
  assign _053_ = _015_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _019_[1];
  assign _010_[0] = value[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  value[1];
  assign _006_[1] = value[2] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  value[3];
  assign _006_[2] = value[4] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  value[5];
  assign _020_[3] = value[6] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _089_[7];
  assign _015_[0] = _010_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _006_[1];
  assign _021_[1] = _006_[2] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _020_[3];
  assign _054_ = _015_[0] |(* src = "./log2_function/log2.sv:27.29-27.46" *)  _021_[1];
  assign _023_[0] = _022_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _022_[1];
  assign _024_[0] = _023_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _023_[1];
  assign _071_ = _119_ | _024_[0];
  assign _025_[0] = _089_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  value[1];
  assign _026_[0] = _025_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _022_[1];
  assign _023_[1] = _022_[2] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _022_[3];
  assign _027_[0] = _026_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _023_[1];
  assign _064_ = _091_ | _027_[0];
  assign _029_[0] = _028_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _028_[1];
  assign _030_[0] = _029_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _023_[1];
  assign _065_ = _095_ | _030_[0];
  assign _028_[0] = _089_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _090_[1];
  assign _032_[0] = _028_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _031_[1];
  assign _033_[0] = _032_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _023_[1];
  assign _066_ = _099_ | _033_[0];
  assign _036_[0] = _035_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _035_[1];
  assign _067_ = _103_ | _036_[0];
  assign _039_[0] = _035_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _038_[1];
  assign _068_ = _107_ | _039_[0];
  assign _035_[0] = _028_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _022_[1];
  assign _041_[1] = _022_[2] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _040_[3];
  assign _042_[0] = _035_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _041_[1];
  assign _069_ = _111_ | _042_[0];
  assign _043_[3] = _089_[6] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  value[7];
  assign _044_[1] = _022_[2] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _043_[3];
  assign _045_[0] = _035_[0] &(* src = "./log2_function/log2.sv:25.21-25.38" *)  _044_[1];
  assign _070_ = _115_ | _045_[0];
  assign _046_ = _015_[0] |(* src = "./log2_function/log2.sv:18.17-18.27" *)  _007_[1];
  assign _055_ = ~(* src = "./log2_function/log2.sv:18.17-18.27" *) _046_;
  assign _056_ = ~(* src = "./log2_function/log2.sv:27.28-27.57" *) _047_;
  assign _057_ = ~(* src = "./log2_function/log2.sv:27.28-27.57" *) _048_;
  assign _058_ = ~(* src = "./log2_function/log2.sv:27.28-27.57" *) _049_;
  assign _059_ = ~(* src = "./log2_function/log2.sv:27.28-27.57" *) _050_;
  assign _060_ = ~(* src = "./log2_function/log2.sv:27.28-27.57" *) _051_;
  assign _061_ = ~(* src = "./log2_function/log2.sv:27.28-27.57" *) _052_;
  assign _062_ = ~(* src = "./log2_function/log2.sv:27.28-27.57" *) _053_;
  assign _063_ = ~(* src = "./log2_function/log2.sv:27.28-27.57" *) _054_;
  assign _072_ = _071_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) _056_ : 1'hx;
  assign _073_ = _064_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) _057_ : _072_;
  assign _074_ = _065_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) _058_ : _073_;
  assign _075_ = _066_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) _059_ : _074_;
  assign _076_ = _067_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) _060_ : _075_;
  assign _077_ = _068_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) _061_ : _076_;
  assign _078_ = _069_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) _062_ : _077_;
  assign _079_ = _070_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) _063_ : _078_;
  assign _001_ = _046_ ? (* src = "./log2_function/log2.sv:18.17-18.27|./log2_function/log2.sv:18.13-30.16" *) _079_ : 1'h0;
  assign _080_[0] = _071_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h0 : 1'hx;
  assign _081_[0] = _064_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _080_[0];
  assign _081_[1] = _064_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h0 : _080_[0];
  assign _082_[0] = _065_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h0 : _081_[0];
  assign _082_[1] = _065_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _081_[1];
  assign _082_[2] = _065_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h0 : _081_[1];
  assign _083_[0] = _066_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _082_[0];
  assign _083_[1] = _066_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _082_[1];
  assign _083_[2] = _066_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h0 : _082_[2];
  assign _084_[0] = _067_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h0 : _083_[0];
  assign _084_[1] = _067_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h0 : _083_[1];
  assign _084_[2] = _067_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _083_[2];
  assign _085_[0] = _068_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _084_[0];
  assign _085_[1] = _068_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h0 : _084_[1];
  assign _085_[2] = _068_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _084_[2];
  assign _086_[0] = _069_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h0 : _085_[0];
  assign _086_[1] = _069_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _085_[1];
  assign _086_[2] = _069_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _085_[2];
  assign _087_[0] = _070_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _086_[0];
  assign _087_[1] = _070_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _086_[1];
  assign _087_[2] = _070_ ? (* src = "./log2_function/log2.sv:25.21-25.38|./log2_function/log2.sv:25.17-28.20" *) 1'h1 : _086_[2];
  assign _000_[0] = _046_ ? (* src = "./log2_function/log2.sv:18.17-18.27|./log2_function/log2.sv:18.13-30.16" *) _087_[0] : 1'h0;
  assign _000_[1] = _046_ ? (* src = "./log2_function/log2.sv:18.17-18.27|./log2_function/log2.sv:18.13-30.16" *) _087_[1] : 1'h0;
  assign _000_[2] = _046_ ? (* src = "./log2_function/log2.sv:18.17-18.27|./log2_function/log2.sv:18.13-30.16" *) _087_[2] : 1'h0;
  assign _119_ = ~(* src = "./log2_function/log2.sv:25.21-25.38" *) _120_;
  assign _091_ = ~(* src = "./log2_function/log2.sv:25.21-25.38" *) _092_;
  assign _095_ = ~(* src = "./log2_function/log2.sv:25.21-25.38" *) _096_;
  assign _099_ = ~(* src = "./log2_function/log2.sv:25.21-25.38" *) _100_;
  assign _103_ = ~(* src = "./log2_function/log2.sv:25.21-25.38" *) _104_;
  assign _107_ = ~(* src = "./log2_function/log2.sv:25.21-25.38" *) _108_;
  assign _111_ = ~(* src = "./log2_function/log2.sv:25.21-25.38" *) _112_;
  assign _115_ = ~(* src = "./log2_function/log2.sv:25.21-25.38" *) _116_;
  assign _017_[0] = _015_[0];
  assign { _016_[3], _016_[1:0] } = { _006_[3], _006_[1], _010_[0] };
  assign { _041_[7:2], _041_[0] } = { 6'h3f, _035_[0] };
  assign { _090_[31:9], _090_[0] } = { _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], _090_[8], value[0] };
  assign { _040_[15:4], _040_[2:0] } = { 12'hfff, _022_[2:1], _028_[0] };
  assign { _088_[31:8], _088_[1:0] } = { _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], _088_[7], value[1], 1'h1 };
  assign _036_[3:1] = 3'h7;
  assign _035_[7:2] = 6'h3f;
  assign { _034_[15:3], _034_[1:0] } = { 12'hfff, _022_[3], _022_[1], _028_[0] };
  assign { _089_[31:8], _089_[1] } = { 24'hffffff, value[1] };
  assign { _014_[3], _014_[1:0] } = { _006_[3], _006_[1], _010_[0] };
  assign { _106_[31:9], _106_[3:0] } = { _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], _106_[8], value[3:0] };
  assign { _098_[31:9], _098_[3:0] } = { _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _098_[8], _089_[3], value[2:0] };
  assign { _097_[31:8], _097_[2:0] } = { _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], _097_[7], 3'h7 };
  assign _027_[3:1] = 3'h7;
  assign _026_[7:1] = { 6'h3f, _023_[1] };
  assign _025_[15:1] = { 12'hfff, _022_[3:1] };
  assign { _105_[31:8], _105_[3:0] } = { _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _105_[7], _101_[3], 3'h7 };
  assign _013_[1] = _007_[1];
  assign { _012_[3:2], _012_[0] } = { _006_[3:2], _010_[0] };
  assign { _118_[31:9], _118_[0] } = { _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _118_[8], _089_[0] };
  assign _045_[3:1] = 3'h7;
  assign { _044_[7:2], _044_[0] } = { 6'h3f, _035_[0] };
  assign { _117_[31:8], _117_[0] } = { _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], _117_[7], value[0] };
  assign { _043_[15:4], _043_[2:0] } = { 12'hfff, _022_[2:1], _028_[0] };
  assign _011_[1] = _007_[1];
  assign _010_[3:2] = _006_[3:2];
  assign { _110_[31:9], _110_[4:0] } = { _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _110_[8], _106_[4], value[3:0] };
  assign _033_[3:1] = 3'h7;
  assign _032_[7:1] = { 6'h3f, _023_[1] };
  assign { _031_[15:2], _031_[0] } = { 12'hfff, _022_[3:2], _028_[0] };
  assign _039_[3:1] = 3'h7;
  assign { _038_[7:2], _038_[0] } = { 6'h3f, _035_[0] };
  assign _024_[3:1] = 3'h7;
  assign _023_[7:2] = 6'h3f;
  assign _022_[15:4] = 12'hfff;
  assign { _037_[15:3], _037_[1:0] } = { 12'hfff, _022_[3], _022_[1], _028_[0] };
  assign _009_[1] = _007_[1];
  assign _008_[3:1] = _006_[3:1];
  assign _021_[0] = _015_[0];
  assign _020_[2:0] = { _006_[2:1], _010_[0] };
  assign { _094_[31:9], _094_[2:0] } = { _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _094_[8], _089_[2], value[1:0] };
  assign { _109_[31:8], _109_[4:0] } = { _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _109_[7], _105_[4], _101_[3], 3'h7 };
  assign { _093_[31:8], _093_[2:0] } = { _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], _093_[7], value[2], 2'h3 };
  assign { _102_[31:9], _102_[3:0] } = { _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], _102_[8], value[3:0] };
  assign { _101_[31:8], _101_[2:0] } = { _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], _101_[7], 3'h7 };
  assign _019_[0] = _015_[0];
  assign _018_[2:0] = { _006_[2:1], _010_[0] };
  assign { _114_[31:9], _114_[5:0] } = { _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _114_[8], _110_[5], _106_[4], value[3:0] };
  assign { _113_[31:8], _113_[5:0] } = { _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _113_[7], _109_[5], _105_[4], _101_[3], 3'h7 };
  assign _080_[2:1] = { _080_[0], _080_[0] };
  assign _030_[3:1] = 3'h7;
  assign _029_[7:1] = { 6'h3f, _023_[1] };
  assign _028_[15:2] = { 12'hfff, _022_[3:2] };
  assign _042_[3:1] = 3'h7;
  assign _081_[2] = _081_[1];
endmodule
