/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./MIPS32_Processor/MIPS32.sv:4.1-193.10" *)
module MIPS32(clk_1, clk_2, rst);
  (* src = "./MIPS32_Processor/MIPS32.sv:5.15-5.20" *)
  input clk_1;
  wire clk_1;
  (* src = "./MIPS32_Processor/MIPS32.sv:5.21-5.26" *)
  input clk_2;
  wire clk_2;
  (* src = "./MIPS32_Processor/MIPS32.sv:5.27-5.30" *)
  input rst;
  wire rst;
endmodule
