/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* src = "./MUX/MUX_16X1.sv:3.1-7.10" *)
module AND(F, A, B);
  (* src = "./MUX/MUX_16X1.sv:4.15-4.16" *)
  output F;
  wire F;
  (* src = "./MUX/MUX_16X1.sv:5.14-5.15" *)
  input A;
  wire A;
  (* src = "./MUX/MUX_16X1.sv:5.16-5.17" *)
  input B;
  wire B;
  assign F = A &(* src = "./MUX/MUX_16X1.sv:6.13-6.19" *)  B;
endmodule

(* top =  1  *)
(* src = "./MUX/MUX_16X1.sv:37.1-49.10" *)
module MUX_16x1(Y, In, Sel);
  (* src = "./MUX/MUX_16X1.sv:38.16-38.17" *)
  output Y;
  wire Y;
  (* src = "./MUX/MUX_16X1.sv:39.22-39.24" *)
  input [15:0] In;
  wire [15:0] In;
  (* src = "./MUX/MUX_16X1.sv:40.21-40.24" *)
  input [3:0] Sel;
  wire [3:0] Sel;
  (* src = "./MUX/MUX_16X1.sv:41.9-41.11" *)
  wire w1;
  (* src = "./MUX/MUX_16X1.sv:41.13-41.15" *)
  wire w2;
  (* src = "./MUX/MUX_16X1.sv:41.17-41.19" *)
  wire w3;
  (* src = "./MUX/MUX_16X1.sv:41.21-41.23" *)
  wire w4;
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:43.11-43.36" *)
  MUX_4x1 M1 (
    .In(In[3:0]),
    .Sel(Sel[1:0]),
    .Y(w1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:44.11-44.36" *)
  MUX_4x1 M2 (
    .In(In[7:4]),
    .Sel(Sel[1:0]),
    .Y(w2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:45.11-45.37" *)
  MUX_4x1 M3 (
    .In(In[11:8]),
    .Sel(Sel[1:0]),
    .Y(w3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:46.11-46.38" *)
  MUX_4x1 M4 (
    .In(In[15:12]),
    .Sel(Sel[1:0]),
    .Y(w4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:47.11-47.41" *)
  MUX_4x1 M5 (
    .In({ w4, w3, w2, w1 }),
    .Sel(Sel[3:2]),
    .Y(Y)
  );
endmodule

(* src = "./MUX/MUX_16X1.sv:15.1-23.11" *)
module MUX_2x1(Y, In, Sel);
  (* src = "./MUX/MUX_16X1.sv:16.15-16.16" *)
  output Y;
  wire Y;
  (* src = "./MUX/MUX_16X1.sv:17.20-17.22" *)
  input [1:0] In;
  wire [1:0] In;
  (* src = "./MUX/MUX_16X1.sv:18.14-18.17" *)
  input Sel;
  wire Sel;
  (* src = "./MUX/MUX_16X1.sv:20.18-20.22" *)
  wire _0_;
  (* src = "./MUX/MUX_16X1.sv:19.8-19.10" *)
  wire w1;
  (* src = "./MUX/MUX_16X1.sv:19.11-19.13" *)
  wire w2;
  assign _0_ = ~(* src = "./MUX/MUX_16X1.sv:20.18-20.22" *) Sel;
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:20.6-20.23" *)
  AND G1 (
    .A(In[0]),
    .B(_0_),
    .F(w1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:21.6-21.22" *)
  AND G2 (
    .A(In[1]),
    .B(Sel),
    .F(w2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:22.5-22.16" *)
  OR G3 (
    .A(w1),
    .B(w2),
    .F(Y)
  );
endmodule

(* src = "./MUX/MUX_16X1.sv:25.1-35.10" *)
module MUX_4x1(Y, In, Sel);
  (* src = "./MUX/MUX_16X1.sv:26.16-26.17" *)
  output Y;
  wire Y;
  (* src = "./MUX/MUX_16X1.sv:27.21-27.23" *)
  input [3:0] In;
  wire [3:0] In;
  (* src = "./MUX/MUX_16X1.sv:28.21-28.24" *)
  input [1:0] Sel;
  wire [1:0] Sel;
  (* src = "./MUX/MUX_16X1.sv:29.9-29.11" *)
  wire w1;
  (* src = "./MUX/MUX_16X1.sv:29.13-29.15" *)
  wire w2;
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:31.11-31.34" *)
  MUX_2x1 M1 (
    .In(In[1:0]),
    .Sel(Sel[0]),
    .Y(w1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:32.11-32.34" *)
  MUX_2x1 M2 (
    .In(In[3:2]),
    .Sel(Sel[0]),
    .Y(w2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./MUX/MUX_16X1.sv:33.11-33.33" *)
  MUX_2x1 M3 (
    .In({ w2, w1 }),
    .Sel(Sel[1]),
    .Y(Y)
  );
endmodule

(* src = "./MUX/MUX_16X1.sv:9.1-13.10" *)
module OR(F, A, B);
  (* src = "./MUX/MUX_16X1.sv:10.15-10.16" *)
  output F;
  wire F;
  (* src = "./MUX/MUX_16X1.sv:11.14-11.15" *)
  input A;
  wire A;
  (* src = "./MUX/MUX_16X1.sv:11.16-11.17" *)
  input B;
  wire B;
  assign F = A |(* src = "./MUX/MUX_16X1.sv:12.13-12.19" *)  B;
endmodule
