/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:3.1-15.10" *)
module Odd_Even_Cnt(Cnt, M, clk, rst);
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:4.23-4.26" *)
  output [15:0] Cnt;
  reg [15:0] Cnt;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:5.15-5.16" *)
  input M;
  wire M;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:5.17-5.20" *)
  input clk;
  wire clk;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:5.21-5.24" *)
  input rst;
  wire rst;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  wire [15:0] _000_;
  wire _001_;
  wire _002_;
  (* force_downto = 32'd1 *)
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "15" *)
  wire [15:0] _003_;
  (* force_downto = 32'd1 *)
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:287.21-287.22" *)
  wire [15:0] _004_;
  (* force_downto = 32'd1 *)
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:270.26-270.27" *)
  wire [15:0] _005_;
  (* force_downto = 32'd1 *)
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "15" *)
  wire [15:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:287.21-287.22" *)
  wire [15:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:270.26-270.27" *)
  wire [15:0] _008_;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _009_;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _010_;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _011_;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _012_;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _013_;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _014_;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _015_;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _016_;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:9.14-9.31" *)
  wire [15:0] _017_;
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[1] <= 1'h0;
    else Cnt[1] <= _000_[1];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[2] <= 1'h0;
    else Cnt[2] <= _000_[2];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[3] <= 1'h0;
    else Cnt[3] <= _000_[3];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[4] <= 1'h0;
    else Cnt[4] <= _000_[4];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[5] <= 1'h0;
    else Cnt[5] <= _000_[5];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[6] <= 1'h0;
    else Cnt[6] <= _000_[6];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[7] <= 1'h0;
    else Cnt[7] <= _000_[7];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[8] <= 1'h0;
    else Cnt[8] <= _000_[8];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[9] <= 1'h0;
    else Cnt[9] <= _000_[9];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[10] <= 1'h0;
    else Cnt[10] <= _000_[10];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[11] <= 1'h0;
    else Cnt[11] <= _000_[11];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[12] <= 1'h0;
    else Cnt[12] <= _000_[12];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[13] <= 1'h0;
    else Cnt[13] <= _000_[13];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[14] <= 1'h0;
    else Cnt[14] <= _000_[14];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[15] <= 1'h0;
    else Cnt[15] <= _000_[15];
  (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:7.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[0] <= _017_[0];
    else if (_001_) Cnt[0] <= _000_[0];
  assign _007_[1] = ~Cnt[1];
  assign _004_[0] = ~Cnt[0];
  assign _001_ = ~_002_;
  assign _002_ = Cnt[0] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.15-12.23" *)  M;
  assign _005_[1] = Cnt[1] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  Cnt[0];
  assign _005_[2] = Cnt[2] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[1];
  assign _005_[3] = Cnt[3] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[2];
  assign _005_[4] = Cnt[4] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[3];
  assign _005_[5] = Cnt[5] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[4];
  assign _005_[6] = Cnt[6] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[5];
  assign _005_[7] = Cnt[7] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[6];
  assign _005_[8] = Cnt[8] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[7];
  assign _005_[9] = Cnt[9] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[8];
  assign _005_[10] = Cnt[10] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[9];
  assign _005_[11] = Cnt[11] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[10];
  assign _005_[12] = Cnt[12] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[11];
  assign _005_[13] = Cnt[13] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[12];
  assign _005_[14] = Cnt[14] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[13];
  assign _005_[15] = Cnt[15] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _003_[14];
  assign _008_[2] = Cnt[2] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  Cnt[1];
  assign _008_[3] = Cnt[3] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[2];
  assign _008_[4] = Cnt[4] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[3];
  assign _008_[5] = Cnt[5] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[4];
  assign _008_[6] = Cnt[6] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[5];
  assign _008_[7] = Cnt[7] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[6];
  assign _008_[8] = Cnt[8] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[7];
  assign _008_[9] = Cnt[9] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[8];
  assign _008_[10] = Cnt[10] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[9];
  assign _008_[11] = Cnt[11] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[10];
  assign _008_[12] = Cnt[12] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[11];
  assign _008_[13] = Cnt[13] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[12];
  assign _008_[14] = Cnt[14] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[13];
  assign _008_[15] = Cnt[15] ^(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:296.13-296.25" *)  _006_[14];
  assign _003_[8] = Cnt[8] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[7];
  assign _003_[4] = Cnt[4] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[3];
  assign _003_[10] = Cnt[10] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[9];
  assign _003_[2] = Cnt[2] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[1];
  assign _003_[13] = _014_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[11];
  assign _003_[9] = _012_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[7];
  assign _003_[12] = Cnt[12] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[11];
  assign _003_[5] = _010_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[3];
  assign _003_[11] = _016_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[7];
  assign _003_[14] = Cnt[14] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[13];
  assign _003_[7] = _015_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _003_[3];
  assign _016_ = _013_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _012_;
  assign _015_ = _011_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _010_;
  assign _003_[3] = _009_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _003_[1];
  assign _014_ = Cnt[13] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[12];
  assign _011_ = Cnt[7] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[6];
  assign _010_ = Cnt[5] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[4];
  assign _009_ = Cnt[3] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[2];
  assign _003_[6] = Cnt[6] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _003_[5];
  assign _003_[1] = Cnt[1] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[0];
  assign _006_[8] = Cnt[8] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _006_[7];
  assign _006_[4] = Cnt[4] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _006_[3];
  assign _006_[10] = Cnt[10] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _006_[9];
  assign _006_[2] = Cnt[2] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  Cnt[1];
  assign _006_[13] = _014_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _006_[11];
  assign _006_[9] = _012_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _006_[7];
  assign _006_[12] = Cnt[12] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _006_[11];
  assign _006_[5] = _010_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _006_[3];
  assign _006_[11] = _016_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _006_[7];
  assign _006_[14] = Cnt[14] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _006_[13];
  assign _006_[7] = _015_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _006_[3];
  assign _006_[3] = _009_ &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[1];
  assign _013_ = Cnt[11] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[10];
  assign _012_ = Cnt[9] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[8];
  assign _006_[6] = Cnt[6] &(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.41-12.52|./Even_Odd_Counter/Odd_Even_Cnt.sv:12.27-12.38|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _006_[5];
  assign _000_[0] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) 1'hx : _004_[0];
  assign _000_[1] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _007_[1] : _005_[1];
  assign _000_[2] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[2] : _005_[2];
  assign _000_[3] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[3] : _005_[3];
  assign _000_[4] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[4] : _005_[4];
  assign _000_[5] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[5] : _005_[5];
  assign _000_[6] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[6] : _005_[6];
  assign _000_[7] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[7] : _005_[7];
  assign _000_[8] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[8] : _005_[8];
  assign _000_[9] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[9] : _005_[9];
  assign _000_[10] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[10] : _005_[10];
  assign _000_[11] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[11] : _005_[11];
  assign _000_[12] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[12] : _005_[12];
  assign _000_[13] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[13] : _005_[13];
  assign _000_[14] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[14] : _005_[14];
  assign _000_[15] = _002_ ? (* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:12.14-12.52" *) _008_[15] : _005_[15];
  assign _017_[0] = ~(* src = "./Even_Odd_Counter/Odd_Even_Cnt.sv:9.14-9.31" *) M;
  assign _005_[0] = _004_[0];
  assign _003_[0] = Cnt[0];
  assign { _007_[15:2], _007_[0] } = { Cnt[15:2], Cnt[0] };
  assign _008_[1:0] = { _007_[1], Cnt[0] };
  assign _004_[15:1] = Cnt[15:1];
  assign _006_[1:0] = { Cnt[1], 1'h0 };
  assign _017_[15:1] = 15'h0000;
endmodule
