/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Parity_Detector/pr_detect.sv:3.1-32.10" *)
module pr_detect(out, sr_in, clk, rst);
  (* src = "./Parity_Detector/pr_detect.sv:5.16-5.19" *)
  output out;
  wire out;
  (* src = "./Parity_Detector/pr_detect.sv:6.15-6.20" *)
  input sr_in;
  wire sr_in;
  (* src = "./Parity_Detector/pr_detect.sv:6.21-6.24" *)
  input clk;
  wire clk;
  (* src = "./Parity_Detector/pr_detect.sv:6.25-6.28" *)
  input rst;
  wire rst;
  wire _00_;
  wire _01_;
  wire [15:0] _02_;
  wire [7:0] _03_;
  wire [3:0] _04_;
  wire [1:0] _05_;
  wire [15:0] _06_;
  wire [7:0] _07_;
  wire [3:0] _08_;
  wire [1:0] _09_;
  wire _10_;
  wire _11_;
  (* force_downto = 32'd1 *)
  (* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12|/share/techmap.v:579.28-579.29" *)
  wire [63:0] _12_;
  (* force_downto = 32'd1 *)
  (* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12|/share/techmap.v:591.28-591.35" *)
  wire [63:0] _13_;
  (* force_downto = 32'd1 *)
  (* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12|/share/techmap.v:581.22-581.23" *)
  wire [1:0] _14_;
  (* force_downto = 32'd1 *)
  (* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12|/share/techmap.v:586.19-586.22" *)
  wire [31:0] _15_;
  (* enum_type = "$enum0" *)
  (* enum_value_00000000000000000000000000000000 = "\\EVEN" *)
  (* enum_value_00000000000000000000000000000001 = "\\ODD" *)
  (* src = "./Parity_Detector/pr_detect.sv:9.18-9.26" *)
  (* wiretype = "\\state" *)
  wire [31:0] nx_state;
  (* enum_type = "$enum0" *)
  (* enum_value_00000000000000000000000000000000 = "\\EVEN" *)
  (* enum_value_00000000000000000000000000000001 = "\\ODD" *)
  (* src = "./Parity_Detector/pr_detect.sv:9.9-9.17" *)
  (* wiretype = "\\state" *)
  wire [31:0] pr_state;
  reg \pr_state_reg[0] ;
  (* src = "./Parity_Detector/pr_detect.sv:11.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pr_state_reg[0]  <= 1'h0;
    else if (_00_) \pr_state_reg[0]  <= nx_state[0];
  assign pr_state[0] = \pr_state_reg[0] ;
  reg \pr_state_reg[30] ;
  (* src = "./Parity_Detector/pr_detect.sv:11.3-14.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \pr_state_reg[30]  <= 1'h0;
    else if (_00_) \pr_state_reg[30]  <= nx_state[30];
  assign pr_state[30] = \pr_state_reg[30] ;
  assign _01_ = ~pr_state[0];
  assign _13_[32] = sr_in &(* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12|/share/techmap.v:593.44-593.84" *)  _14_[1];
  assign _13_[0] = _12_[0] &(* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12|/share/techmap.v:593.44-593.84" *)  out;
  assign _02_[0] = _01_ |(* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12" *)  pr_state[30];
  assign _03_[0] = _02_[0] |(* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12" *)  pr_state[30];
  assign _04_[0] = _03_[0] |(* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12" *)  pr_state[30];
  assign _05_[0] = _04_[0] |(* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12" *)  pr_state[30];
  assign _11_ = _05_[0] |(* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12" *)  pr_state[30];
  assign _15_[0] = _13_[0] |(* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12|/share/techmap.v:601.20-601.31" *)  _13_[32];
  assign _00_ = out |(* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12|/share/techmap.v:605.13-605.15" *)  _14_[1];
  assign _06_[0] = pr_state[0] |(* src = "./Parity_Detector/pr_detect.sv:19.20-19.20|./Parity_Detector/pr_detect.sv:19.5-30.12" *)  pr_state[30];
  assign _07_[0] = _06_[0] |(* src = "./Parity_Detector/pr_detect.sv:19.20-19.20|./Parity_Detector/pr_detect.sv:19.5-30.12" *)  pr_state[30];
  assign _08_[0] = _07_[0] |(* src = "./Parity_Detector/pr_detect.sv:19.20-19.20|./Parity_Detector/pr_detect.sv:19.5-30.12" *)  pr_state[30];
  assign _09_[0] = _08_[0] |(* src = "./Parity_Detector/pr_detect.sv:19.20-19.20|./Parity_Detector/pr_detect.sv:19.5-30.12" *)  pr_state[30];
  assign _10_ = _09_[0] |(* src = "./Parity_Detector/pr_detect.sv:19.20-19.20|./Parity_Detector/pr_detect.sv:19.5-30.12" *)  pr_state[30];
  assign out = ~(* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12" *) _11_;
  assign _14_[1] = ~(* src = "./Parity_Detector/pr_detect.sv:19.20-19.20|./Parity_Detector/pr_detect.sv:19.5-30.12" *) _10_;
  assign _12_[0] = ~(* src = "./Parity_Detector/pr_detect.sv:26.20-26.29|./Parity_Detector/pr_detect.sv:26.16-27.36" *) sr_in;
  assign nx_state[0] = _00_ ? (* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12|/share/techmap.v:605.13-605.25" *) _15_[0] : 1'hx;
  assign nx_state[30] = _00_ ? (* src = "./Parity_Detector/pr_detect.sv:24.17-24.17|./Parity_Detector/pr_detect.sv:19.5-30.12|/share/techmap.v:605.13-605.25" *) 1'h0 : 1'hx;
  assign _08_[3:1] = { pr_state[30], pr_state[30], pr_state[30] };
  assign _09_[1] = pr_state[30];
  assign { _13_[63:33], _13_[31:1] } = 62'h0000000000000000;
  assign _05_[1] = pr_state[30];
  assign _04_[3:1] = { pr_state[30], pr_state[30], pr_state[30] };
  assign _03_[7:1] = { pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30] };
  assign _02_[15:1] = { pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30] };
  assign _14_[0] = out;
  assign _12_[63:1] = { 31'h00000000, sr_in, 31'h00000000 };
  assign _15_[31:1] = 31'h00000000;
  assign _06_[15:1] = { pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30] };
  assign _07_[7:1] = { pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30] };
  assign { nx_state[31], nx_state[29:1] } = { nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30], nx_state[30] };
  assign { pr_state[31], pr_state[29:1] } = { pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30], pr_state[30] };
endmodule
