/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Priority_Encoder/priority_enc.sv:2.1-11.10" *)
module priority_enc(Out, In0, In1, In2, In3);
  (* src = "./Priority_Encoder/priority_enc.sv:3.21-3.24" *)
  output [1:0] Out;
  wire [1:0] Out;
  (* src = "./Priority_Encoder/priority_enc.sv:4.15-4.18" *)
  input In0;
  wire In0;
  (* src = "./Priority_Encoder/priority_enc.sv:4.20-4.23" *)
  input In1;
  wire In1;
  (* src = "./Priority_Encoder/priority_enc.sv:4.25-4.28" *)
  input In2;
  wire In2;
  (* src = "./Priority_Encoder/priority_enc.sv:4.30-4.33" *)
  input In3;
  wire In3;
  (* src = "./Priority_Encoder/priority_enc.sv:7.16-7.26" *)
  wire _00_;
  (* src = "./Priority_Encoder/priority_enc.sv:7.16-7.33" *)
  wire _01_;
  (* src = "./Priority_Encoder/priority_enc.sv:9.35-9.67" *)
  wire [1:0] _02_;
  (* src = "./Priority_Encoder/priority_enc.sv:9.23-9.68" *)
  wire [1:0] _03_;
  (* src = "./Priority_Encoder/priority_enc.sv:5.9-5.12" *)
  wire Vld;
  assign _00_ = In0 |(* src = "./Priority_Encoder/priority_enc.sv:7.16-7.26" *)  In1;
  assign _01_ = _00_ |(* src = "./Priority_Encoder/priority_enc.sv:7.16-7.33" *)  In2;
  assign Vld = _01_ |(* src = "./Priority_Encoder/priority_enc.sv:7.16-7.40" *)  In3;
  assign _02_[0] = In2 ? (* src = "./Priority_Encoder/priority_enc.sv:9.35-9.67" *) 1'h0 : In1;
  assign _03_[0] = In3 ? (* src = "./Priority_Encoder/priority_enc.sv:9.23-9.68" *) 1'h1 : _02_[0];
  assign _03_[1] = In3 ? (* src = "./Priority_Encoder/priority_enc.sv:9.23-9.68" *) 1'h1 : In2;
  assign Out[0] = Vld ? (* src = "./Priority_Encoder/priority_enc.sv:9.16-9.74" *) _03_[0] : 1'hx;
  assign Out[1] = Vld ? (* src = "./Priority_Encoder/priority_enc.sv:9.16-9.74" *) _03_[1] : 1'hx;
  assign _02_[1] = In2;
endmodule
