/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Priority_arbiter/priority_arb.sv:3.1-23.10" *)
module priority_arb(S, M0, P0, M1, P1, M2, P2, M3, P3);
  (* src = "./Priority_arbiter/priority_arb.sv:5.16-5.17" *)
  output S;
  wire S;
  (* src = "./Priority_arbiter/priority_arb.sv:6.15-6.17" *)
  input M0;
  wire M0;
  (* src = "./Priority_arbiter/priority_arb.sv:7.21-7.23" *)
  input [2:0] P0;
  wire [2:0] P0;
  (* src = "./Priority_arbiter/priority_arb.sv:6.18-6.20" *)
  input M1;
  wire M1;
  (* src = "./Priority_arbiter/priority_arb.sv:7.24-7.26" *)
  input [2:0] P1;
  wire [2:0] P1;
  (* src = "./Priority_arbiter/priority_arb.sv:6.21-6.23" *)
  input M2;
  wire M2;
  (* src = "./Priority_arbiter/priority_arb.sv:7.27-7.29" *)
  input [2:0] P2;
  wire [2:0] P2;
  (* src = "./Priority_arbiter/priority_arb.sv:6.24-6.26" *)
  input M3;
  wire M3;
  (* src = "./Priority_arbiter/priority_arb.sv:7.30-7.32" *)
  input [2:0] P3;
  wire [2:0] P3;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [2:0] _008_;
  wire [2:0] _009_;
  wire [2:0] _010_;
  wire [2:0] _011_;
  wire [2:0] _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  (* src = "./Priority_arbiter/priority_arb.sv:12.17-12.25" *)
  wire _017_;
  (* src = "./Priority_arbiter/priority_arb.sv:12.17-12.31" *)
  wire _018_;
  (* src = "./Priority_arbiter/priority_arb.sv:12.17-12.37" *)
  wire _019_;
  (* src = "./Priority_arbiter/priority_arb.sv:12.43-12.55" *)
  wire _020_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.21-279.23" *)
  wire [2:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:274.23-274.25" *)
  wire [2:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:287.21-287.22" *)
  wire [2:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:200.21-200.22" *)
  wire [2:0] _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.21-279.23" *)
  wire [2:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:274.23-274.25" *)
  wire [2:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:287.21-287.22" *)
  wire [2:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:200.21-200.22" *)
  wire [2:0] _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.21-279.23" *)
  wire [2:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:274.23-274.25" *)
  wire [2:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:287.21-287.22" *)
  wire [2:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:200.21-200.22" *)
  wire [2:0] _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  (* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _042_;
  (* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _043_;
  (* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _044_;
  (* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _045_;
  (* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _046_;
  (* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _047_;
  (* src = "./Priority_arbiter/priority_arb.sv:18.21-22.23" *)
  wire _048_;
  (* src = "./Priority_arbiter/priority_arb.sv:19.21-22.23" *)
  wire _049_;
  (* src = "./Priority_arbiter/priority_arb.sv:20.21-22.23" *)
  wire _050_;
  (* src = "./Priority_arbiter/priority_arb.sv:21.21-22.23" *)
  wire _051_;
  (* src = "./Priority_arbiter/priority_arb.sv:9.9-9.12" *)
  wire Vld;
  (* src = "./Priority_arbiter/priority_arb.sv:10.27-10.30" *)
  wire [2:0] max;
  (* src = "./Priority_arbiter/priority_arb.sv:10.15-10.19" *)
  wire [2:0] max1;
  (* src = "./Priority_arbiter/priority_arb.sv:10.21-10.25" *)
  wire [2:0] max2;
  assign _012_[0] = max1[0] ^(* src = "./Priority_arbiter/priority_arb.sv:12.43-12.55" *)  max2[0];
  assign _012_[1] = max1[1] ^(* src = "./Priority_arbiter/priority_arb.sv:12.43-12.55" *)  max2[1];
  assign _012_[2] = max1[2] ^(* src = "./Priority_arbiter/priority_arb.sv:12.43-12.55" *)  max2[2];
  assign _008_[0] = P0[0] ^(* src = "./Priority_arbiter/priority_arb.sv:18.22-18.31" *)  max[0];
  assign _008_[1] = P0[1] ^(* src = "./Priority_arbiter/priority_arb.sv:18.22-18.31" *)  max[1];
  assign _008_[2] = P0[2] ^(* src = "./Priority_arbiter/priority_arb.sv:18.22-18.31" *)  max[2];
  assign _009_[0] = P1[0] ^(* src = "./Priority_arbiter/priority_arb.sv:19.22-19.31" *)  max[0];
  assign _009_[1] = P1[1] ^(* src = "./Priority_arbiter/priority_arb.sv:19.22-19.31" *)  max[1];
  assign _009_[2] = P1[2] ^(* src = "./Priority_arbiter/priority_arb.sv:19.22-19.31" *)  max[2];
  assign _010_[0] = P2[0] ^(* src = "./Priority_arbiter/priority_arb.sv:20.22-20.31" *)  max[0];
  assign _010_[1] = P2[1] ^(* src = "./Priority_arbiter/priority_arb.sv:20.22-20.31" *)  max[1];
  assign _010_[2] = P2[2] ^(* src = "./Priority_arbiter/priority_arb.sv:20.22-20.31" *)  max[2];
  assign _011_[0] = P3[0] ^(* src = "./Priority_arbiter/priority_arb.sv:21.22-21.31" *)  max[0];
  assign _011_[1] = P3[1] ^(* src = "./Priority_arbiter/priority_arb.sv:21.22-21.31" *)  max[1];
  assign _011_[2] = P3[2] ^(* src = "./Priority_arbiter/priority_arb.sv:21.22-21.31" *)  max[2];
  assign _027_ = _025_ | _026_;
  assign _034_ = _032_ | _033_;
  assign _041_ = _039_ | _040_;
  assign _024_[0] = P0[0] &(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.26-205.31" *)  _021_[0];
  assign _024_[1] = P0[1] &(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.26-205.31" *)  _021_[1];
  assign _024_[2] = P0[2] &(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.26-205.31" *)  _021_[2];
  assign _023_[0] = P0[0] ^(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.14-205.19" *)  _021_[0];
  assign _023_[1] = P0[1] ^(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.14-205.19" *)  _021_[1];
  assign _023_[2] = P0[2] ^(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.14-205.19" *)  _021_[2];
  assign _043_ = _023_[2] &(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _022_[1];
  assign _022_[2] = _024_[2] |(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _043_;
  assign _022_[1] = _024_[1] |(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _042_;
  assign _042_ = _023_[1] &(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _022_[0];
  assign _022_[0] = _024_[0] |(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:231.10-231.28" *)  _023_[0];
  assign _031_[0] = P2[0] &(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.26-205.31" *)  _028_[0];
  assign _031_[1] = P2[1] &(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.26-205.31" *)  _028_[1];
  assign _031_[2] = P2[2] &(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.26-205.31" *)  _028_[2];
  assign _030_[0] = P2[0] ^(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.14-205.19" *)  _028_[0];
  assign _030_[1] = P2[1] ^(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.14-205.19" *)  _028_[1];
  assign _030_[2] = P2[2] ^(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.14-205.19" *)  _028_[2];
  assign _045_ = _030_[2] &(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _029_[1];
  assign _029_[2] = _031_[2] |(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _045_;
  assign _029_[1] = _031_[1] |(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _044_;
  assign _044_ = _030_[1] &(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _029_[0];
  assign _029_[0] = _031_[0] |(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:231.10-231.28" *)  _030_[0];
  assign _038_[0] = max1[0] &(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.26-205.31" *)  _035_[0];
  assign _038_[1] = max1[1] &(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.26-205.31" *)  _035_[1];
  assign _038_[2] = max1[2] &(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.26-205.31" *)  _035_[2];
  assign _037_[0] = max1[0] ^(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.14-205.19" *)  _035_[0];
  assign _037_[1] = max1[1] ^(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.14-205.19" *)  _035_[1];
  assign _037_[2] = max1[2] ^(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:292.26-292.70|/share/techmap.v:205.14-205.19" *)  _035_[2];
  assign _047_ = _037_[2] &(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _036_[1];
  assign _036_[2] = _038_[2] |(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _047_;
  assign _036_[1] = _038_[1] |(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _046_;
  assign _046_ = _037_[1] &(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _036_[0];
  assign _036_[0] = _038_[0] |(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:293.27-293.63|/share/techmap.v:231.10-231.28" *)  _037_[0];
  assign _000_ = _012_[0] |(* src = "./Priority_arbiter/priority_arb.sv:12.43-12.55" *)  _012_[1];
  assign _020_ = _000_ |(* src = "./Priority_arbiter/priority_arb.sv:12.43-12.55" *)  _012_[2];
  assign _001_ = _008_[0] |(* src = "./Priority_arbiter/priority_arb.sv:18.22-18.31" *)  _008_[1];
  assign _013_ = _001_ |(* src = "./Priority_arbiter/priority_arb.sv:18.22-18.31" *)  _008_[2];
  assign _002_ = _009_[0] |(* src = "./Priority_arbiter/priority_arb.sv:19.22-19.31" *)  _009_[1];
  assign _014_ = _002_ |(* src = "./Priority_arbiter/priority_arb.sv:19.22-19.31" *)  _009_[2];
  assign _003_ = _010_[0] |(* src = "./Priority_arbiter/priority_arb.sv:20.22-20.31" *)  _010_[1];
  assign _015_ = _003_ |(* src = "./Priority_arbiter/priority_arb.sv:20.22-20.31" *)  _010_[2];
  assign _004_ = _011_[0] |(* src = "./Priority_arbiter/priority_arb.sv:21.22-21.31" *)  _011_[1];
  assign _016_ = _004_ |(* src = "./Priority_arbiter/priority_arb.sv:21.22-21.31" *)  _011_[2];
  assign _005_ = _023_[0] &(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25" *)  _023_[1];
  assign _026_ = _005_ &(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25" *)  _023_[2];
  assign _006_ = _030_[0] &(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25" *)  _030_[1];
  assign _033_ = _006_ &(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25" *)  _030_[2];
  assign _007_ = _037_[0] &(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25" *)  _037_[1];
  assign _040_ = _007_ &(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25" *)  _037_[2];
  assign Vld = _019_ &(* src = "./Priority_arbiter/priority_arb.sv:12.16-12.56" *)  _020_;
  assign _017_ = M0 |(* src = "./Priority_arbiter/priority_arb.sv:12.17-12.25" *)  M1;
  assign _018_ = _017_ |(* src = "./Priority_arbiter/priority_arb.sv:12.17-12.31" *)  M2;
  assign _019_ = _018_ |(* src = "./Priority_arbiter/priority_arb.sv:12.17-12.37" *)  M3;
  assign max1[0] = _027_ ? (* src = "./Priority_arbiter/priority_arb.sv:14.17-14.36" *) P1[0] : P0[0];
  assign max1[1] = _027_ ? (* src = "./Priority_arbiter/priority_arb.sv:14.17-14.36" *) P1[1] : P0[1];
  assign max1[2] = _027_ ? (* src = "./Priority_arbiter/priority_arb.sv:14.17-14.36" *) P1[2] : P0[2];
  assign max2[0] = _034_ ? (* src = "./Priority_arbiter/priority_arb.sv:15.17-15.36" *) P3[0] : P2[0];
  assign max2[1] = _034_ ? (* src = "./Priority_arbiter/priority_arb.sv:15.17-15.36" *) P3[1] : P2[1];
  assign max2[2] = _034_ ? (* src = "./Priority_arbiter/priority_arb.sv:15.17-15.36" *) P3[2] : P2[2];
  assign max[0] = _041_ ? (* src = "./Priority_arbiter/priority_arb.sv:16.17-16.44" *) max2[0] : max1[0];
  assign max[1] = _041_ ? (* src = "./Priority_arbiter/priority_arb.sv:16.17-16.44" *) max2[1] : max1[1];
  assign max[2] = _041_ ? (* src = "./Priority_arbiter/priority_arb.sv:16.17-16.44" *) max2[2] : max1[2];
  assign _051_ = _016_ ? (* src = "./Priority_arbiter/priority_arb.sv:21.21-22.23" *) 1'h0 : M3;
  assign _050_ = _015_ ? (* src = "./Priority_arbiter/priority_arb.sv:20.21-22.23" *) _051_ : M2;
  assign _049_ = _014_ ? (* src = "./Priority_arbiter/priority_arb.sv:19.21-22.23" *) _050_ : M1;
  assign _048_ = _013_ ? (* src = "./Priority_arbiter/priority_arb.sv:18.21-22.23" *) _049_ : M0;
  assign S = Vld ? (* src = "./Priority_arbiter/priority_arb.sv:18.14-22.29" *) _048_ : 1'hz;
  assign _025_ = ~(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25" *) _022_[2];
  assign _032_ = ~(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25" *) _029_[2];
  assign _039_ = ~(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25" *) _036_[2];
  assign _021_[0] = ~(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.31-279.37" *) P1[0];
  assign _021_[1] = ~(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.31-279.37" *) P1[1];
  assign _021_[2] = ~(* src = "./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.31-279.37" *) P1[2];
  assign _028_[0] = ~(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.31-279.37" *) P3[0];
  assign _028_[1] = ~(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.31-279.37" *) P3[1];
  assign _028_[2] = ~(* src = "./Priority_arbiter/priority_arb.sv:15.18-15.25|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.31-279.37" *) P3[2];
  assign _035_[0] = ~(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.31-279.37" *) max2[0];
  assign _035_[1] = ~(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.31-279.37" *) max2[1];
  assign _035_[2] = ~(* src = "./Priority_arbiter/priority_arb.sv:16.18-16.29|./Priority_arbiter/priority_arb.sv:14.18-14.25|/share/techmap.v:279.31-279.37" *) max2[2];
endmodule
