/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./UART_System/receiver.sv:5.1-102.10" *)
module receiver(parity_o, dout, rx_done, rx, tick, clk, rst);
  (* src = "./UART_System/receiver.sv:7.24-7.32" *)
  output parity_o;
  wire parity_o;
  (* src = "./UART_System/receiver.sv:8.22-8.26" *)
  output [2:0] dout;
  wire [2:0] dout;
  (* src = "./UART_System/receiver.sv:7.16-7.23" *)
  output rx_done;
  wire rx_done;
  (* src = "./UART_System/receiver.sv:9.15-9.17" *)
  input rx;
  wire rx;
  (* src = "./UART_System/receiver.sv:9.18-9.22" *)
  input tick;
  wire tick;
  (* src = "./UART_System/receiver.sv:9.23-9.26" *)
  input clk;
  wire clk;
  (* src = "./UART_System/receiver.sv:9.27-9.30" *)
  input rst;
  wire rst;
  (* src = "./UART_System/receiver.sv:40.3-97.6" *)
  wire [2:0] _000_;
  (* src = "./UART_System/receiver.sv:40.3-97.6" *)
  wire _001_;
  (* src = "./UART_System/receiver.sv:40.3-97.6" *)
  wire _002_;
  (* src = "./UART_System/receiver.sv:40.3-97.6" *)
  wire [3:0] _003_;
  (* src = "./UART_System/receiver.sv:40.3-97.6" *)
  wire [2:0] _004_;
  (* src = "./UART_System/receiver.sv:40.3-97.6" *)
  wire [3:0] _005_;
  (* src = "./UART_System/receiver.sv:40.3-97.6" *)
  wire [2:0] _006_;
  (* src = "./UART_System/receiver.sv:40.3-97.6" *)
  wire [2:0] _007_;
  (* src = "./UART_System/receiver.sv:40.3-97.6" *)
  wire [2:0] _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire [1:0] _044_;
  wire _045_;
  wire [4:0] _046_;
  wire [2:0] _047_;
  wire _048_;
  wire [1:0] _049_;
  wire _050_;
  wire [1:0] _051_;
  wire [1:0] _052_;
  wire [1:0] _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire [1:0] _058_;
  wire _059_;
  wire [1:0] _060_;
  wire _061_;
  wire [1:0] _062_;
  wire _063_;
  wire [1:0] _064_;
  wire _065_;
  wire [1:0] _066_;
  wire [1:0] _067_;
  wire _068_;
  wire _069_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:579.28-579.29" *)
  wire [14:0] _070_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:591.28-591.35" *)
  wire [14:0] _071_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:581.22-581.23" *)
  wire [4:0] _072_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:586.19-586.22" *)
  wire [2:0] _073_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:579.28-579.29" *)
  wire [7:0] _074_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:591.28-591.35" *)
  wire [7:0] _075_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:581.22-581.23" *)
  wire [1:0] _076_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:586.19-586.22" *)
  wire [3:0] _077_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:69.44-69.60|/share/techmap.v:287.21-287.22" *)
  wire [1:0] _078_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:69.44-69.60|/share/techmap.v:270.26-270.27" *)
  wire [1:0] _079_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:93.41-93.56|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _080_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:93.41-93.56|/share/techmap.v:287.21-287.22" *)
  wire [3:0] _081_;
  (* force_downto = 32'd1 *)
  (* src = "./UART_System/receiver.sv:93.41-93.56|/share/techmap.v:270.26-270.27" *)
  wire [3:0] _082_;
  (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.15" *)
  wire _083_;
  (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.15" *)
  wire _084_;
  (* src = "./UART_System/receiver.sv:13.15-13.23" *)
  reg [2:0] data_out;
  (* src = "./UART_System/receiver.sv:12.15-12.24" *)
  reg [1:0] dbits_cnt;
  (* enum_type = "$enum0" *)
  (* enum_value_000 = "\\idle" *)
  (* enum_value_001 = "\\start" *)
  (* enum_value_010 = "\\data" *)
  (* enum_value_011 = "\\parity" *)
  (* enum_value_100 = "\\stop" *)
  (* src = "./UART_System/receiver.sv:18.18-18.26" *)
  (* wiretype = "\\state" *)
  wire [2:0] nx_state;
  (* src = "./UART_System/receiver.sv:14.9-14.19" *)
  reg parity_reg;
  (* enum_type = "$enum0" *)
  (* enum_value_000 = "\\idle" *)
  (* enum_value_001 = "\\start" *)
  (* enum_value_010 = "\\data" *)
  (* enum_value_011 = "\\parity" *)
  (* enum_value_100 = "\\stop" *)
  (* src = "./UART_System/receiver.sv:18.9-18.17" *)
  (* wiretype = "\\state" *)
  reg [2:0] pr_state;
  (* src = "./UART_System/receiver.sv:11.15-11.23" *)
  reg [3:0] tick_cnt;
  (* src = "./UART_System/receiver.sv:11.24-11.36" *)
  wire [3:0] tick_cnt_nxt;
  (* src = "./UART_System/receiver.sv:20.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) parity_reg <= 1'h0;
    else if (_026_) parity_reg <= rx;
  (* src = "./UART_System/receiver.sv:20.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) data_out[0] <= 1'h0;
    else if (_025_) data_out[0] <= data_out[1];
  (* src = "./UART_System/receiver.sv:20.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) data_out[1] <= 1'h0;
    else if (_025_) data_out[1] <= data_out[2];
  (* src = "./UART_System/receiver.sv:20.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) data_out[2] <= 1'h0;
    else if (_025_) data_out[2] <= rx;
  (* src = "./UART_System/receiver.sv:20.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) tick_cnt[0] <= 1'h0;
    else if (_024_) tick_cnt[0] <= tick_cnt_nxt[0];
  (* src = "./UART_System/receiver.sv:20.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) tick_cnt[1] <= 1'h0;
    else if (_024_) tick_cnt[1] <= tick_cnt_nxt[1];
  (* src = "./UART_System/receiver.sv:20.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) tick_cnt[2] <= 1'h0;
    else if (_024_) tick_cnt[2] <= tick_cnt_nxt[2];
  (* src = "./UART_System/receiver.sv:20.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) tick_cnt[3] <= 1'h0;
    else if (_024_) tick_cnt[3] <= tick_cnt_nxt[3];
  (* src = "./UART_System/receiver.sv:20.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) dbits_cnt[0] <= 1'h0;
    else if (_023_) dbits_cnt[0] <= _078_[0];
  (* src = "./UART_System/receiver.sv:20.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) dbits_cnt[1] <= 1'h0;
    else if (_023_) dbits_cnt[1] <= _079_[1];
  (* src = "./UART_System/receiver.sv:35.3-38.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[0] <= 1'h0;
    else if (_022_) pr_state[0] <= nx_state[0];
  (* src = "./UART_System/receiver.sv:35.3-38.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[1] <= 1'h0;
    else if (_022_) pr_state[1] <= nx_state[1];
  (* src = "./UART_System/receiver.sv:35.3-38.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[2] <= 1'h0;
    else if (_022_) pr_state[2] <= nx_state[2];
  assign _078_[0] = ~dbits_cnt[0];
  assign _028_ = ~pr_state[0];
  assign _029_ = ~pr_state[2];
  assign _030_ = ~pr_state[1];
  assign _031_ = ~tick_cnt[3];
  assign _032_ = ~tick_cnt[2];
  assign _033_ = ~tick_cnt[1];
  assign _081_[0] = ~tick_cnt[0];
  assign _034_ = ~dbits_cnt[1];
  assign _036_ = ~rx;
  assign _041_ = ~_076_[0];
  assign _071_[0] = _070_[0] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[0];
  assign _071_[3] = _070_[0] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[1];
  assign _071_[5] = _070_[5] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[1];
  assign _071_[6] = _070_[6] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[2];
  assign _071_[8] = _070_[8] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[2];
  assign _071_[9] = _070_[9] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[3];
  assign _071_[10] = _070_[10] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[3];
  assign _071_[12] = _070_[12] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[4];
  assign _071_[13] = _070_[13] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[4];
  assign _075_[4] = _074_[4] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[3];
  assign _075_[5] = _074_[5] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[3];
  assign _075_[6] = _074_[6] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[3];
  assign _075_[7] = _074_[7] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _072_[3];
  assign _075_[0] = _074_[0] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _076_[0];
  assign _075_[1] = _074_[1] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _076_[0];
  assign _075_[2] = _074_[2] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _076_[0];
  assign _075_[3] = _074_[3] &(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:593.44-593.84" *)  _076_[0];
  assign _082_[1] = tick_cnt[1] ^(* src = "./UART_System/receiver.sv:93.41-93.56|/share/techmap.v:296.13-296.25" *)  tick_cnt[0];
  assign _082_[2] = tick_cnt[2] ^(* src = "./UART_System/receiver.sv:93.41-93.56|/share/techmap.v:296.13-296.25" *)  _080_[1];
  assign _082_[3] = tick_cnt[3] ^(* src = "./UART_System/receiver.sv:93.41-93.56|/share/techmap.v:296.13-296.25" *)  _080_[2];
  assign _079_[1] = dbits_cnt[1] ^(* src = "./UART_System/receiver.sv:69.44-69.60|/share/techmap.v:296.13-296.25" *)  dbits_cnt[0];
  assign _080_[2] = tick_cnt[2] &(* src = "./UART_System/receiver.sv:93.41-93.56|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _080_[1];
  assign _080_[1] = tick_cnt[1] &(* src = "./UART_System/receiver.sv:93.41-93.56|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  tick_cnt[0];
  assign _026_ = _042_ & _072_[1];
  assign _042_ = tick & _002_;
  assign _025_ = _042_ & _072_[2];
  assign _043_ = _021_ & _010_;
  assign _024_ = _043_ & _009_;
  assign _021_ = _041_ | tick;
  assign _044_[0] = _027_ & tick;
  assign _044_[1] = _002_ & _072_[2];
  assign _023_ = _044_[0] & _044_[1];
  assign _076_[0] = _045_ | _072_[0];
  assign _046_[0] = _020_ & _019_;
  assign _046_[1] = _018_ & _017_;
  assign _046_[2] = _016_ & _015_;
  assign _046_[3] = _014_ & _013_;
  assign _046_[4] = _012_ & _011_;
  assign _047_[0] = _046_[0] & _046_[1];
  assign _047_[1] = _046_[2] & _046_[3];
  assign _047_[2] = _046_[4] & _009_;
  assign _048_ = _047_[0] & _047_[1];
  assign _022_ = _048_ & _047_[2];
  assign _049_[0] = _072_[4] | _072_[1];
  assign _050_ = _049_[0] | _049_[1];
  assign _020_ = _050_ | _072_[0];
  assign _019_ = _002_ | _040_;
  assign _018_ = _002_ | _038_;
  assign _017_ = _002_ | _037_;
  assign _016_ = _066_[0] | _038_;
  assign _015_ = _067_[0] | _039_;
  assign _014_ = tick | _040_;
  assign _009_ = tick | _039_;
  assign _013_ = tick | _038_;
  assign _012_ = tick | _037_;
  assign _011_ = _036_ | _035_;
  assign _045_ = _072_[1] | _072_[2];
  assign _051_[1] = _072_[3] | _072_[0];
  assign _010_ = _045_ | _051_[1];
  assign _052_[1] = _032_ |(* src = "./UART_System/receiver.sv:55.25-55.42" *)  tick_cnt[3];
  assign _068_ = _052_[0] |(* src = "./UART_System/receiver.sv:55.25-55.42" *)  _052_[1];
  assign _027_ = dbits_cnt[0] |(* src = "./UART_System/receiver.sv:68.27-68.49" *)  _034_;
  assign _052_[0] = _081_[0] |(* src = "./UART_System/receiver.sv:88.25-88.43" *)  _033_;
  assign _053_[1] = _032_ |(* src = "./UART_System/receiver.sv:88.25-88.43" *)  _031_;
  assign _069_ = _052_[0] |(* src = "./UART_System/receiver.sv:88.25-88.43" *)  _053_[1];
  assign _054_ = _028_ |(* src = "./UART_System/receiver.sv:73.20-73.20|./UART_System/receiver.sv:48.5-96.12" *)  _030_;
  assign _037_ = _054_ |(* src = "./UART_System/receiver.sv:73.20-73.20|./UART_System/receiver.sv:48.5-96.12" *)  pr_state[2];
  assign _055_ = pr_state[0] |(* src = "./UART_System/receiver.sv:61.20-61.20|./UART_System/receiver.sv:48.5-96.12" *)  _030_;
  assign _038_ = _055_ |(* src = "./UART_System/receiver.sv:61.20-61.20|./UART_System/receiver.sv:48.5-96.12" *)  pr_state[2];
  assign _056_ = _028_ |(* src = "./UART_System/receiver.sv:51.20-51.20|./UART_System/receiver.sv:48.5-96.12" *)  pr_state[1];
  assign _039_ = _056_ |(* src = "./UART_System/receiver.sv:51.20-51.20|./UART_System/receiver.sv:48.5-96.12" *)  pr_state[2];
  assign _057_ = pr_state[0] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12" *)  pr_state[1];
  assign _040_ = _057_ |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12" *)  _029_;
  assign _058_[0] = _072_[0] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.15" *)  _072_[1];
  assign _049_[1] = _072_[2] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.15" *)  _072_[3];
  assign _059_ = _058_[0] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.15" *)  _049_[1];
  assign _083_ = _059_ |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.15" *)  _072_[4];
  assign _060_[0] = _071_[0] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _071_[3];
  assign _060_[1] = _071_[6] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _071_[9];
  assign _061_ = _060_[0] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _060_[1];
  assign _073_[0] = _061_ |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _071_[12];
  assign _062_[1] = _071_[6] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _071_[10];
  assign _063_ = _060_[0] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _062_[1];
  assign _073_[1] = _063_ |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _071_[13];
  assign _064_[0] = _071_[0] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _071_[5];
  assign _064_[1] = _071_[8] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _071_[9];
  assign _065_ = _064_[0] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _064_[1];
  assign _073_[2] = _065_ |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _071_[13];
  assign _077_[3] = _075_[3] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _075_[7];
  assign _077_[2] = _075_[2] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _075_[6];
  assign _077_[1] = _075_[1] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _075_[5];
  assign _077_[0] = _075_[0] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:601.20-601.31" *)  _075_[4];
  assign _084_ = _076_[0] |(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.15" *)  _072_[3];
  assign _035_ = _057_ |(* src = "./UART_System/receiver.sv:48.20-48.20|./UART_System/receiver.sv:48.5-96.12" *)  pr_state[2];
  assign _067_[0] = ~(* src = "./UART_System/receiver.sv:55.25-55.42" *) _068_;
  assign _066_[0] = ~(* src = "./UART_System/receiver.sv:68.27-68.49" *) _027_;
  assign _072_[4] = ~(* src = "./UART_System/receiver.sv:48.20-48.20|./UART_System/receiver.sv:48.5-96.12" *) _035_;
  assign _072_[1] = ~(* src = "./UART_System/receiver.sv:73.20-73.20|./UART_System/receiver.sv:48.5-96.12" *) _037_;
  assign _072_[2] = ~(* src = "./UART_System/receiver.sv:61.20-61.20|./UART_System/receiver.sv:48.5-96.12" *) _038_;
  assign _072_[3] = ~(* src = "./UART_System/receiver.sv:51.20-51.20|./UART_System/receiver.sv:48.5-96.12" *) _039_;
  assign _072_[0] = ~(* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12" *) _040_;
  assign _002_ = ~(* src = "./UART_System/receiver.sv:88.25-88.43|./UART_System/receiver.sv:88.21-93.57" *) _069_;
  assign _074_[0] = tick ? (* src = "./UART_System/receiver.sv:87.23-87.31|./UART_System/receiver.sv:87.19-94.22" *) _005_[0] : 1'hx;
  assign _074_[1] = tick ? (* src = "./UART_System/receiver.sv:87.23-87.31|./UART_System/receiver.sv:87.19-94.22" *) _005_[1] : 1'hx;
  assign _074_[2] = tick ? (* src = "./UART_System/receiver.sv:87.23-87.31|./UART_System/receiver.sv:87.19-94.22" *) _005_[2] : 1'hx;
  assign _074_[3] = tick ? (* src = "./UART_System/receiver.sv:87.23-87.31|./UART_System/receiver.sv:87.19-94.22" *) _005_[3] : 1'hx;
  assign _001_ = tick ? (* src = "./UART_System/receiver.sv:87.23-87.31|./UART_System/receiver.sv:87.19-94.22" *) _002_ : 1'h0;
  assign _005_[0] = _069_ ? (* src = "./UART_System/receiver.sv:77.25-77.43|./UART_System/receiver.sv:77.21-82.57" *) _081_[0] : 1'h0;
  assign _005_[1] = _069_ ? (* src = "./UART_System/receiver.sv:77.25-77.43|./UART_System/receiver.sv:77.21-82.57" *) _082_[1] : 1'h0;
  assign _005_[2] = _069_ ? (* src = "./UART_System/receiver.sv:77.25-77.43|./UART_System/receiver.sv:77.21-82.57" *) _082_[2] : 1'h0;
  assign _005_[3] = _069_ ? (* src = "./UART_System/receiver.sv:77.25-77.43|./UART_System/receiver.sv:77.21-82.57" *) _082_[3] : 1'h0;
  assign _000_[0] = _069_ ? (* src = "./UART_System/receiver.sv:77.25-77.43|./UART_System/receiver.sv:77.21-82.57" *) 1'hx : 1'h0;
  assign _008_[2] = _069_ ? (* src = "./UART_System/receiver.sv:77.25-77.43|./UART_System/receiver.sv:77.21-82.57" *) 1'hx : 1'h1;
  assign _070_[0] = tick ? (* src = "./UART_System/receiver.sv:76.23-76.31|./UART_System/receiver.sv:76.19-83.22" *) _000_[0] : 1'hx;
  assign _070_[5] = tick ? (* src = "./UART_System/receiver.sv:76.23-76.31|./UART_System/receiver.sv:76.19-83.22" *) _008_[2] : 1'hx;
  assign _007_[0] = _027_ ? (* src = "./UART_System/receiver.sv:68.27-68.49|./UART_System/receiver.sv:68.23-69.61" *) 1'hx : 1'h1;
  assign _007_[2] = _027_ ? (* src = "./UART_System/receiver.sv:68.27-68.49|./UART_System/receiver.sv:68.23-69.61" *) 1'hx : 1'h0;
  assign _006_[0] = _069_ ? (* src = "./UART_System/receiver.sv:65.25-65.43|./UART_System/receiver.sv:65.21-71.57" *) 1'hx : _007_[0];
  assign _006_[2] = _069_ ? (* src = "./UART_System/receiver.sv:65.25-65.43|./UART_System/receiver.sv:65.21-71.57" *) 1'hx : _007_[2];
  assign _070_[6] = tick ? (* src = "./UART_System/receiver.sv:64.23-64.31|./UART_System/receiver.sv:64.19-72.22" *) _006_[0] : 1'hx;
  assign _070_[8] = tick ? (* src = "./UART_System/receiver.sv:64.23-64.31|./UART_System/receiver.sv:64.19-72.22" *) _006_[2] : 1'hx;
  assign _003_[0] = _068_ ? (* src = "./UART_System/receiver.sv:55.25-55.42|./UART_System/receiver.sv:55.21-59.57" *) _081_[0] : 1'h0;
  assign _003_[1] = _068_ ? (* src = "./UART_System/receiver.sv:55.25-55.42|./UART_System/receiver.sv:55.21-59.57" *) _082_[1] : 1'h0;
  assign _003_[2] = _068_ ? (* src = "./UART_System/receiver.sv:55.25-55.42|./UART_System/receiver.sv:55.21-59.57" *) _082_[2] : 1'h0;
  assign _003_[3] = _068_ ? (* src = "./UART_System/receiver.sv:55.25-55.42|./UART_System/receiver.sv:55.21-59.57" *) _082_[3] : 1'h0;
  assign _004_[0] = _068_ ? (* src = "./UART_System/receiver.sv:55.25-55.42|./UART_System/receiver.sv:55.21-59.57" *) 1'hx : 1'h0;
  assign _004_[1] = _068_ ? (* src = "./UART_System/receiver.sv:55.25-55.42|./UART_System/receiver.sv:55.21-59.57" *) 1'hx : 1'h1;
  assign _070_[9] = tick ? (* src = "./UART_System/receiver.sv:54.23-54.31|./UART_System/receiver.sv:54.19-60.22" *) _004_[0] : 1'hx;
  assign _070_[10] = tick ? (* src = "./UART_System/receiver.sv:54.23-54.31|./UART_System/receiver.sv:54.19-60.22" *) _004_[1] : 1'hx;
  assign _074_[4] = tick ? (* src = "./UART_System/receiver.sv:54.23-54.31|./UART_System/receiver.sv:54.19-60.22" *) _003_[0] : 1'hx;
  assign _074_[5] = tick ? (* src = "./UART_System/receiver.sv:54.23-54.31|./UART_System/receiver.sv:54.19-60.22" *) _003_[1] : 1'hx;
  assign _074_[6] = tick ? (* src = "./UART_System/receiver.sv:54.23-54.31|./UART_System/receiver.sv:54.19-60.22" *) _003_[2] : 1'hx;
  assign _074_[7] = tick ? (* src = "./UART_System/receiver.sv:54.23-54.31|./UART_System/receiver.sv:54.19-60.22" *) _003_[3] : 1'hx;
  assign _070_[12] = rx ? (* src = "./UART_System/receiver.sv:50.23-50.31|./UART_System/receiver.sv:50.19-50.52" *) 1'hx : 1'h1;
  assign _070_[13] = rx ? (* src = "./UART_System/receiver.sv:50.23-50.31|./UART_System/receiver.sv:50.19-50.52" *) 1'hx : 1'h0;
  assign rx_done = _040_ ? (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12" *) 1'h0 : _001_;
  assign nx_state[0] = _083_ ? (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.25" *) _073_[0] : 1'hx;
  assign nx_state[1] = _083_ ? (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.25" *) _073_[1] : 1'hx;
  assign nx_state[2] = _083_ ? (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.25" *) _073_[2] : 1'hx;
  assign tick_cnt_nxt[0] = _084_ ? (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.25" *) _077_[0] : 1'hx;
  assign tick_cnt_nxt[1] = _084_ ? (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.25" *) _077_[1] : 1'hx;
  assign tick_cnt_nxt[2] = _084_ ? (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.25" *) _077_[2] : 1'hx;
  assign tick_cnt_nxt[3] = _084_ ? (* src = "./UART_System/receiver.sv:84.21-84.21|./UART_System/receiver.sv:48.5-96.12|/share/techmap.v:605.13-605.25" *) _077_[3] : 1'hx;
  assign _081_[3:1] = tick_cnt[3:1];
  assign _079_[0] = _078_[0];
  assign _062_[0] = _060_[0];
  assign _080_[0] = tick_cnt[0];
  assign _067_[1] = _039_;
  assign _066_[1] = _038_;
  assign _078_[1] = dbits_cnt[1];
  assign _053_[0] = _052_[0];
  assign _082_[0] = _081_[0];
  assign { _070_[14], _070_[11], _070_[7], _070_[4:1] } = { _070_[13], _070_[9], _070_[6], _070_[0], _070_[0], _070_[0], _070_[0] };
  assign _058_[1] = _049_[1];
  assign _007_[1] = _007_[0];
  assign { _071_[14], _071_[11], _071_[7], _071_[4], _071_[2:1] } = { _071_[13], _071_[9], _071_[6], _071_[3], _071_[0], _071_[0] };
  assign _006_[1] = _006_[0];
  assign _004_[2] = _004_[0];
  assign _076_[1] = _072_[3];
  assign _008_[1:0] = { _000_[0], _000_[0] };
  assign _000_[2:1] = { _000_[0], _000_[0] };
  assign _051_[0] = _045_;
  assign dout = data_out;
  assign parity_o = parity_reg;
endmodule
