/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Ring_Counter/ring_cnt.sv:2.1-13.10" *)
module ring_cnt(Q, clk, rst);
  (* src = "./Ring_Counter/ring_cnt.sv:3.21-3.22" *)
  output [3:0] Q;
  reg [3:0] Q;
  (* src = "./Ring_Counter/ring_cnt.sv:4.15-4.18" *)
  input clk;
  wire clk;
  (* src = "./Ring_Counter/ring_cnt.sv:4.19-4.22" *)
  input rst;
  wire rst;
  (* src = "./Ring_Counter/ring_cnt.sv:6.9-6.11" *)
  wire Fo;
  (* src = "./Ring_Counter/ring_cnt.sv:9.3-12.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[0] <= 1'h0;
    else Q[0] <= Q[1];
  (* src = "./Ring_Counter/ring_cnt.sv:9.3-12.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[1] <= 1'h0;
    else Q[1] <= Q[2];
  (* src = "./Ring_Counter/ring_cnt.sv:9.3-12.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[2] <= 1'h1;
    else Q[2] <= Q[3];
  (* src = "./Ring_Counter/ring_cnt.sv:9.3-12.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[3] <= 1'h0;
    else Q[3] <= Q[0];
  assign Fo = Q[0];
endmodule
