/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Sequence_Detector_3/seq_det.sv:4.1-48.10" *)
module Seq_Det(In, Out, clk, rst);
  (* src = "./Sequence_Detector_3/seq_det.sv:7.15-7.17" *)
  input In;
  wire In;
  (* src = "./Sequence_Detector_3/seq_det.sv:6.16-6.19" *)
  output Out;
  wire Out;
  (* src = "./Sequence_Detector_3/seq_det.sv:7.18-7.21" *)
  input clk;
  wire clk;
  (* src = "./Sequence_Detector_3/seq_det.sv:7.22-7.25" *)
  input rst;
  wire rst;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [1:0] _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [1:0] _17_;
  wire [1:0] _18_;
  wire _19_;
  wire [1:0] _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* force_downto = 32'd1 *)
  (* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:579.28-579.29" *)
  wire [14:0] _25_;
  (* force_downto = 32'd1 *)
  (* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:591.28-591.35" *)
  wire [14:0] _26_;
  (* force_downto = 32'd1 *)
  (* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:581.22-581.23" *)
  wire [4:0] _27_;
  (* force_downto = 32'd1 *)
  (* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:586.19-586.22" *)
  wire [2:0] _28_;
  (* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:605.13-605.15" *)
  wire _29_;
  (* enum_type = "$enum0" *)
  (* enum_value_000 = "\\S0" *)
  (* enum_value_001 = "\\S1" *)
  (* enum_value_010 = "\\S2" *)
  (* enum_value_011 = "\\S3" *)
  (* enum_value_100 = "\\S4" *)
  (* src = "./Sequence_Detector_3/seq_det.sv:14.20-14.28" *)
  (* wiretype = "\\state" *)
  wire [2:0] nx_state;
  (* enum_type = "$enum0" *)
  (* enum_value_000 = "\\S0" *)
  (* enum_value_001 = "\\S1" *)
  (* enum_value_010 = "\\S2" *)
  (* enum_value_011 = "\\S3" *)
  (* enum_value_100 = "\\S4" *)
  (* src = "./Sequence_Detector_3/seq_det.sv:14.11-14.19" *)
  (* wiretype = "\\state" *)
  reg [2:0] pr_state;
  (* src = "./Sequence_Detector_3/seq_det.sv:16.3-19.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[0] <= 1'h0;
    else if (_03_) pr_state[0] <= nx_state[0];
  (* src = "./Sequence_Detector_3/seq_det.sv:16.3-19.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[1] <= 1'h0;
    else if (_03_) pr_state[1] <= nx_state[1];
  (* src = "./Sequence_Detector_3/seq_det.sv:16.3-19.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) pr_state[2] <= 1'h0;
    else if (_03_) pr_state[2] <= nx_state[2];
  assign _04_ = ~pr_state[0];
  assign _05_ = ~pr_state[1];
  assign _06_ = ~pr_state[2];
  assign _26_[12] = _25_[12] &(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:593.44-593.84" *)  _27_[4];
  assign _26_[13] = _25_[13] &(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:593.44-593.84" *)  _27_[4];
  assign _26_[9] = _25_[9] &(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:593.44-593.84" *)  _27_[3];
  assign _26_[10] = _25_[10] &(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:593.44-593.84" *)  _27_[3];
  assign _26_[7] = In &(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:593.44-593.84" *)  _26_[6];
  assign _26_[5] = _25_[0] &(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:593.44-593.84" *)  _27_[1];
  assign _26_[0] = _25_[0] &(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:593.44-593.84" *)  Out;
  assign _09_ = _02_ & _01_;
  assign _03_ = _09_ & _00_;
  assign _10_[0] = _27_[1] | _26_[6];
  assign _10_[1] = _27_[3] | _27_[4];
  assign _11_ = _10_[0] | _10_[1];
  assign _02_ = _11_ | Out;
  assign _01_ = _25_[0] | _08_;
  assign _00_ = In | _07_;
  assign _12_ = _04_ |(* src = "./Sequence_Detector_3/seq_det.sv:35.15-35.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *)  _05_;
  assign _22_ = _12_ |(* src = "./Sequence_Detector_3/seq_det.sv:35.15-35.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *)  pr_state[2];
  assign _13_ = pr_state[0] |(* src = "./Sequence_Detector_3/seq_det.sv:31.15-31.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *)  _05_;
  assign _23_ = _13_ |(* src = "./Sequence_Detector_3/seq_det.sv:31.15-31.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *)  pr_state[2];
  assign _14_ = _04_ |(* src = "./Sequence_Detector_3/seq_det.sv:28.15-28.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *)  pr_state[1];
  assign _07_ = _14_ |(* src = "./Sequence_Detector_3/seq_det.sv:28.15-28.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *)  pr_state[2];
  assign _24_ = _15_ |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *)  _06_;
  assign _16_ = _26_[5] |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:601.20-601.31" *)  _26_[9];
  assign _28_[2] = _16_ |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:601.20-601.31" *)  _26_[13];
  assign _17_[1] = _26_[7] |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:601.20-601.31" *)  _26_[10];
  assign _28_[1] = _17_[1] |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:601.20-601.31" *)  _26_[13];
  assign _18_[1] = _26_[6] |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:601.20-601.31" *)  _26_[9];
  assign _19_ = _26_[0] |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:601.20-601.31" *)  _18_[1];
  assign _28_[0] = _19_ |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:601.20-601.31" *)  _26_[12];
  assign _20_[0] = Out |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:605.13-605.15" *)  _27_[1];
  assign _20_[1] = _26_[6] |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:605.13-605.15" *)  _27_[3];
  assign _21_ = _20_[0] |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:605.13-605.15" *)  _20_[1];
  assign _29_ = _21_ |(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:605.13-605.15" *)  _27_[4];
  assign _15_ = pr_state[0] |(* src = "./Sequence_Detector_3/seq_det.sv:25.20-25.20|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *)  pr_state[1];
  assign _08_ = _15_ |(* src = "./Sequence_Detector_3/seq_det.sv:25.20-25.20|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *)  pr_state[2];
  assign _27_[1] = ~(* src = "./Sequence_Detector_3/seq_det.sv:35.15-35.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *) _22_;
  assign _26_[6] = ~(* src = "./Sequence_Detector_3/seq_det.sv:31.15-31.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *) _23_;
  assign _27_[3] = ~(* src = "./Sequence_Detector_3/seq_det.sv:28.15-28.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *) _07_;
  assign _27_[4] = ~(* src = "./Sequence_Detector_3/seq_det.sv:25.20-25.20|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *) _08_;
  assign Out = ~(* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14" *) _24_;
  assign _25_[0] = ~(* src = "./Sequence_Detector_3/seq_det.sv:41.18-41.26|./Sequence_Detector_3/seq_det.sv:41.14-42.33" *) In;
  assign _25_[9] = In ? (* src = "./Sequence_Detector_3/seq_det.sv:30.18-30.26|./Sequence_Detector_3/seq_det.sv:30.14-30.42" *) 1'h0 : 1'hx;
  assign _25_[10] = In ? (* src = "./Sequence_Detector_3/seq_det.sv:30.18-30.26|./Sequence_Detector_3/seq_det.sv:30.14-30.42" *) 1'h1 : 1'hx;
  assign _25_[12] = In ? (* src = "./Sequence_Detector_3/seq_det.sv:27.18-27.26|./Sequence_Detector_3/seq_det.sv:27.14-27.42" *) 1'hx : 1'h1;
  assign _25_[13] = In ? (* src = "./Sequence_Detector_3/seq_det.sv:27.18-27.26|./Sequence_Detector_3/seq_det.sv:27.14-27.42" *) 1'hx : 1'h0;
  assign nx_state[0] = _29_ ? (* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:605.13-605.25" *) _28_[0] : 1'hx;
  assign nx_state[1] = _29_ ? (* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:605.13-605.25" *) _28_[1] : 1'hx;
  assign nx_state[2] = _29_ ? (* src = "./Sequence_Detector_3/seq_det.sv:39.15-39.15|./Sequence_Detector_3/seq_det.sv:25.5-45.14|/share/techmap.v:605.13-605.25" *) _28_[2] : 1'hx;
  assign { _27_[2], _27_[0] } = { _26_[6], Out };
  assign _17_[0] = 1'h0;
  assign { _26_[14], _26_[11], _26_[8], _26_[4:1] } = { _26_[13], _26_[9], 5'h00 };
  assign _18_[0] = _26_[0];
  assign { _25_[14], _25_[11], _25_[8:1] } = { _25_[13], _25_[9], 1'h0, In, 1'h1, _25_[0], 4'h0 };
endmodule
