/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./SIPO_shift_reg/SIPO.sv:3.1-32.10" *)
module SIPO(parallel_out, sr_in, clk, rst);
  (* src = "./SIPO_shift_reg/SIPO.sv:5.22-5.34" *)
  output [7:0] parallel_out;
  wire [7:0] parallel_out;
  (* src = "./SIPO_shift_reg/SIPO.sv:6.15-6.20" *)
  input sr_in;
  wire sr_in;
  (* src = "./SIPO_shift_reg/SIPO.sv:6.21-6.24" *)
  input clk;
  wire clk;
  (* src = "./SIPO_shift_reg/SIPO.sv:6.25-6.28" *)
  input rst;
  wire rst;
  (* src = "./SIPO_shift_reg/SIPO.sv:17.3-21.6" *)
  wire [2:0] _00_;
  (* src = "./SIPO_shift_reg/SIPO.sv:23.3-27.6" *)
  wire _01_;
  wire _02_;
  wire _03_;
  (* force_downto = 32'd1 *)
  (* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.24|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [2:0] _04_;
  (* force_downto = 32'd1 *)
  (* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.24|/share/techmap.v:287.21-287.22" *)
  wire [2:0] _05_;
  (* force_downto = 32'd1 *)
  (* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.24|/share/techmap.v:270.26-270.27" *)
  wire [2:0] _06_;
  (* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _07_;
  (* src = "./SIPO_shift_reg/SIPO.sv:9.15-9.16" *)
  reg [7:0] Q;
  (* src = "./SIPO_shift_reg/SIPO.sv:10.15-10.18" *)
  reg [2:0] cnt;
  (* src = "./SIPO_shift_reg/SIPO.sv:8.9-8.12" *)
  reg out;
  (* src = "./SIPO_shift_reg/SIPO.sv:23.3-27.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) out <= 1'h0;
    else out <= _01_;
  (* src = "./SIPO_shift_reg/SIPO.sv:17.3-21.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) cnt[0] <= 1'h0;
    else cnt[0] <= _00_[0];
  (* src = "./SIPO_shift_reg/SIPO.sv:17.3-21.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) cnt[1] <= 1'h0;
    else cnt[1] <= _00_[1];
  (* src = "./SIPO_shift_reg/SIPO.sv:17.3-21.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) cnt[2] <= 1'h0;
    else cnt[2] <= _00_[2];
  (* src = "./SIPO_shift_reg/SIPO.sv:12.3-15.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[0] <= 1'h0;
    else Q[0] <= Q[1];
  (* src = "./SIPO_shift_reg/SIPO.sv:12.3-15.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[1] <= 1'h0;
    else Q[1] <= Q[2];
  (* src = "./SIPO_shift_reg/SIPO.sv:12.3-15.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[2] <= 1'h0;
    else Q[2] <= Q[3];
  (* src = "./SIPO_shift_reg/SIPO.sv:12.3-15.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[3] <= 1'h0;
    else Q[3] <= Q[4];
  (* src = "./SIPO_shift_reg/SIPO.sv:12.3-15.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[4] <= 1'h0;
    else Q[4] <= Q[5];
  (* src = "./SIPO_shift_reg/SIPO.sv:12.3-15.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[5] <= 1'h0;
    else Q[5] <= Q[6];
  (* src = "./SIPO_shift_reg/SIPO.sv:12.3-15.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[6] <= 1'h0;
    else Q[6] <= Q[7];
  (* src = "./SIPO_shift_reg/SIPO.sv:12.3-15.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[7] <= 1'h0;
    else Q[7] <= sr_in;
  assign _05_[1] = ~cnt[1];
  assign _05_[2] = ~cnt[2];
  assign _06_[0] = ~cnt[0];
  assign _06_[1] = _05_[1] ^(* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.24|/share/techmap.v:296.13-296.25" *)  cnt[0];
  assign _06_[2] = _05_[2] ^(* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.24|/share/techmap.v:296.13-296.25" *)  _04_[1];
  assign _04_[1] = cnt[1] |(* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _07_;
  assign _07_ = _05_[1] &(* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  cnt[0];
  assign _02_ = _06_[0] |(* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.29" *)  _06_[1];
  assign _03_ = _02_ |(* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.29" *)  _06_[2];
  assign parallel_out[0] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:29.25-29.39" *) Q[0] : 1'h0;
  assign parallel_out[1] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:29.25-29.39" *) Q[1] : 1'h0;
  assign parallel_out[2] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:29.25-29.39" *) Q[2] : 1'h0;
  assign parallel_out[3] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:29.25-29.39" *) Q[3] : 1'h0;
  assign parallel_out[4] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:29.25-29.39" *) Q[4] : 1'h0;
  assign parallel_out[5] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:29.25-29.39" *) Q[5] : 1'h0;
  assign parallel_out[6] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:29.25-29.39" *) Q[6] : 1'h0;
  assign parallel_out[7] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:29.25-29.39" *) Q[7] : 1'h0;
  assign _01_ = ~(* src = "./SIPO_shift_reg/SIPO.sv:25.14-25.29|./SIPO_shift_reg/SIPO.sv:25.10-26.20" *) _03_;
  assign _00_[0] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:19.14-19.17|./SIPO_shift_reg/SIPO.sv:19.10-20.28" *) 1'h1 : _06_[0];
  assign _00_[1] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:19.14-19.17|./SIPO_shift_reg/SIPO.sv:19.10-20.28" *) 1'h1 : _06_[1];
  assign _00_[2] = out ? (* src = "./SIPO_shift_reg/SIPO.sv:19.14-19.17|./SIPO_shift_reg/SIPO.sv:19.10-20.28" *) 1'h1 : _06_[2];
  assign _05_[0] = cnt[0];
  assign _04_[0] = cnt[0];
endmodule
