/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Simple_Timer/timer.sv:4.1-34.10" *)
module timer(time_out, preset, preset_val, clk, rst);
  (* src = "./Simple_Timer/timer.sv:6.16-6.24" *)
  output time_out;
  reg time_out;
  (* src = "./Simple_Timer/timer.sv:7.15-7.21" *)
  input preset;
  wire preset;
  (* src = "./Simple_Timer/timer.sv:8.21-8.31" *)
  input [7:0] preset_val;
  wire [7:0] preset_val;
  (* src = "./Simple_Timer/timer.sv:7.22-7.25" *)
  input clk;
  wire clk;
  (* src = "./Simple_Timer/timer.sv:7.26-7.29" *)
  input rst;
  wire rst;
  (* src = "./Simple_Timer/timer.sv:24.3-33.6" *)
  wire [7:0] _00_;
  (* src = "./Simple_Timer/timer.sv:18.3-22.6" *)
  wire _01_;
  wire [3:0] _02_;
  wire [1:0] _03_;
  wire _04_;
  wire [7:0] _05_;
  (* force_downto = 32'd1 *)
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "7" *)
  wire [7:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:287.21-287.22" *)
  wire [7:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:270.26-270.27" *)
  wire [7:0] _08_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _09_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _10_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _11_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _12_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _13_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _14_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _15_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _16_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _17_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _18_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _19_;
  (* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _20_;
  (* src = "./Simple_Timer/timer.sv:11.15-11.18" *)
  reg [7:0] Cnt;
  (* src = "./Simple_Timer/timer.sv:10.15-10.28" *)
  reg [7:0] preset_val_ff;
  (* src = "./Simple_Timer/timer.sv:13.3-16.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) preset_val_ff[0] <= 1'h0;
    else if (preset) preset_val_ff[0] <= preset_val[0];
  (* src = "./Simple_Timer/timer.sv:13.3-16.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) preset_val_ff[1] <= 1'h0;
    else if (preset) preset_val_ff[1] <= preset_val[1];
  (* src = "./Simple_Timer/timer.sv:13.3-16.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) preset_val_ff[2] <= 1'h0;
    else if (preset) preset_val_ff[2] <= preset_val[2];
  (* src = "./Simple_Timer/timer.sv:13.3-16.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) preset_val_ff[3] <= 1'h0;
    else if (preset) preset_val_ff[3] <= preset_val[3];
  (* src = "./Simple_Timer/timer.sv:13.3-16.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) preset_val_ff[4] <= 1'h0;
    else if (preset) preset_val_ff[4] <= preset_val[4];
  (* src = "./Simple_Timer/timer.sv:13.3-16.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) preset_val_ff[5] <= 1'h0;
    else if (preset) preset_val_ff[5] <= preset_val[5];
  (* src = "./Simple_Timer/timer.sv:13.3-16.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) preset_val_ff[6] <= 1'h0;
    else if (preset) preset_val_ff[6] <= preset_val[6];
  (* src = "./Simple_Timer/timer.sv:13.3-16.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) preset_val_ff[7] <= 1'h0;
    else if (preset) preset_val_ff[7] <= preset_val[7];
  (* src = "./Simple_Timer/timer.sv:24.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[0] <= 1'h0;
    else Cnt[0] <= _00_[0];
  (* src = "./Simple_Timer/timer.sv:24.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[1] <= 1'h0;
    else Cnt[1] <= _00_[1];
  (* src = "./Simple_Timer/timer.sv:24.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[2] <= 1'h0;
    else Cnt[2] <= _00_[2];
  (* src = "./Simple_Timer/timer.sv:24.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[3] <= 1'h0;
    else Cnt[3] <= _00_[3];
  (* src = "./Simple_Timer/timer.sv:24.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[4] <= 1'h0;
    else Cnt[4] <= _00_[4];
  (* src = "./Simple_Timer/timer.sv:24.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[5] <= 1'h0;
    else Cnt[5] <= _00_[5];
  (* src = "./Simple_Timer/timer.sv:24.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[6] <= 1'h0;
    else Cnt[6] <= _00_[6];
  (* src = "./Simple_Timer/timer.sv:24.3-33.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[7] <= 1'h0;
    else Cnt[7] <= _00_[7];
  (* src = "./Simple_Timer/timer.sv:18.3-22.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) time_out <= 1'h0;
    else time_out <= _01_;
  assign _07_[1] = ~Cnt[1];
  assign _07_[3] = ~Cnt[3];
  assign _07_[2] = ~Cnt[2];
  assign _07_[4] = ~Cnt[4];
  assign _07_[5] = ~Cnt[5];
  assign _07_[7] = ~Cnt[7];
  assign _07_[6] = ~Cnt[6];
  assign _08_[0] = ~Cnt[0];
  assign _08_[1] = _07_[1] ^(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:296.13-296.25" *)  Cnt[0];
  assign _08_[2] = _07_[2] ^(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:296.13-296.25" *)  _06_[1];
  assign _08_[3] = _07_[3] ^(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:296.13-296.25" *)  _06_[2];
  assign _08_[4] = _07_[4] ^(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:296.13-296.25" *)  _06_[3];
  assign _08_[5] = _07_[5] ^(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:296.13-296.25" *)  _06_[4];
  assign _08_[6] = _07_[6] ^(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:296.13-296.25" *)  _06_[5];
  assign _08_[7] = _07_[7] ^(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:296.13-296.25" *)  _06_[6];
  assign _06_[2] = Cnt[2] |(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _16_;
  assign _16_ = _07_[2] &(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _06_[1];
  assign _17_ = _07_[4] &(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _06_[3];
  assign _06_[5] = _20_ |(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _15_;
  assign _15_ = _14_ &(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _06_[3];
  assign _18_ = _07_[6] &(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _06_[5];
  assign _06_[6] = Cnt[6] |(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _18_;
  assign _06_[3] = _19_ |(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _12_;
  assign _12_ = _13_ &(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _06_[1];
  assign _14_ = _07_[5] &(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _07_[4];
  assign _20_ = Cnt[5] |(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _11_;
  assign _11_ = _07_[5] &(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[4];
  assign _13_ = _07_[3] &(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _07_[2];
  assign _19_ = Cnt[3] |(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _10_;
  assign _10_ = _07_[3] &(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[2];
  assign _06_[4] = Cnt[4] |(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _17_;
  assign _06_[1] = Cnt[1] |(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _09_;
  assign _09_ = _07_[1] &(* src = "./Simple_Timer/timer.sv:31.19-31.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[0];
  assign _02_[0] = _08_[0] |(* src = "./Simple_Timer/timer.sv:20.14-20.30" *)  _08_[1];
  assign _02_[1] = _08_[2] |(* src = "./Simple_Timer/timer.sv:20.14-20.30" *)  _08_[3];
  assign _02_[2] = _08_[4] |(* src = "./Simple_Timer/timer.sv:20.14-20.30" *)  _08_[5];
  assign _02_[3] = _08_[6] |(* src = "./Simple_Timer/timer.sv:20.14-20.30" *)  _08_[7];
  assign _03_[0] = _02_[0] |(* src = "./Simple_Timer/timer.sv:20.14-20.30" *)  _02_[1];
  assign _03_[1] = _02_[2] |(* src = "./Simple_Timer/timer.sv:20.14-20.30" *)  _02_[3];
  assign _04_ = _03_[0] |(* src = "./Simple_Timer/timer.sv:20.14-20.30" *)  _03_[1];
  assign _05_[0] = time_out ? (* src = "./Simple_Timer/timer.sv:30.16-30.30|./Simple_Timer/timer.sv:30.12-31.30" *) preset_val_ff[0] : _08_[0];
  assign _05_[1] = time_out ? (* src = "./Simple_Timer/timer.sv:30.16-30.30|./Simple_Timer/timer.sv:30.12-31.30" *) preset_val_ff[1] : _08_[1];
  assign _05_[2] = time_out ? (* src = "./Simple_Timer/timer.sv:30.16-30.30|./Simple_Timer/timer.sv:30.12-31.30" *) preset_val_ff[2] : _08_[2];
  assign _05_[3] = time_out ? (* src = "./Simple_Timer/timer.sv:30.16-30.30|./Simple_Timer/timer.sv:30.12-31.30" *) preset_val_ff[3] : _08_[3];
  assign _05_[4] = time_out ? (* src = "./Simple_Timer/timer.sv:30.16-30.30|./Simple_Timer/timer.sv:30.12-31.30" *) preset_val_ff[4] : _08_[4];
  assign _05_[5] = time_out ? (* src = "./Simple_Timer/timer.sv:30.16-30.30|./Simple_Timer/timer.sv:30.12-31.30" *) preset_val_ff[5] : _08_[5];
  assign _05_[6] = time_out ? (* src = "./Simple_Timer/timer.sv:30.16-30.30|./Simple_Timer/timer.sv:30.12-31.30" *) preset_val_ff[6] : _08_[6];
  assign _05_[7] = time_out ? (* src = "./Simple_Timer/timer.sv:30.16-30.30|./Simple_Timer/timer.sv:30.12-31.30" *) preset_val_ff[7] : _08_[7];
  assign _00_[0] = preset ? (* src = "./Simple_Timer/timer.sv:29.11-29.17|./Simple_Timer/timer.sv:29.7-31.30" *) preset_val[0] : _05_[0];
  assign _00_[1] = preset ? (* src = "./Simple_Timer/timer.sv:29.11-29.17|./Simple_Timer/timer.sv:29.7-31.30" *) preset_val[1] : _05_[1];
  assign _00_[2] = preset ? (* src = "./Simple_Timer/timer.sv:29.11-29.17|./Simple_Timer/timer.sv:29.7-31.30" *) preset_val[2] : _05_[2];
  assign _00_[3] = preset ? (* src = "./Simple_Timer/timer.sv:29.11-29.17|./Simple_Timer/timer.sv:29.7-31.30" *) preset_val[3] : _05_[3];
  assign _00_[4] = preset ? (* src = "./Simple_Timer/timer.sv:29.11-29.17|./Simple_Timer/timer.sv:29.7-31.30" *) preset_val[4] : _05_[4];
  assign _00_[5] = preset ? (* src = "./Simple_Timer/timer.sv:29.11-29.17|./Simple_Timer/timer.sv:29.7-31.30" *) preset_val[5] : _05_[5];
  assign _00_[6] = preset ? (* src = "./Simple_Timer/timer.sv:29.11-29.17|./Simple_Timer/timer.sv:29.7-31.30" *) preset_val[6] : _05_[6];
  assign _00_[7] = preset ? (* src = "./Simple_Timer/timer.sv:29.11-29.17|./Simple_Timer/timer.sv:29.7-31.30" *) preset_val[7] : _05_[7];
  assign _01_ = ~(* src = "./Simple_Timer/timer.sv:20.14-20.30|./Simple_Timer/timer.sv:20.10-21.25" *) _04_;
  assign _07_[0] = Cnt[0];
  assign _06_[0] = Cnt[0];
endmodule
