/* Generated by Yosys 0.64 (git sha1 6d2c445ae, ccache clang++  -O3 -flto -flto) [yowasp/yosys at release-0.64] */

(* top =  1  *)
(* src = "./Up_Down_Counter/UD_cnt.sv:9.1-38.10" *)
module UD_Cnt(Cnt, load, load_val, clk, rst);
  (* src = "./Up_Down_Counter/UD_cnt.sv:10.22-10.25" *)
  output [7:0] Cnt;
  reg [7:0] Cnt;
  (* src = "./Up_Down_Counter/UD_cnt.sv:11.15-11.19" *)
  input load;
  wire load;
  (* src = "./Up_Down_Counter/UD_cnt.sv:12.21-12.29" *)
  input [7:0] load_val;
  wire [7:0] load_val;
  (* src = "./Up_Down_Counter/UD_cnt.sv:11.20-11.23" *)
  input clk;
  wire clk;
  (* src = "./Up_Down_Counter/UD_cnt.sv:11.24-11.27" *)
  input rst;
  wire rst;
  (* src = "./Up_Down_Counter/UD_cnt.sv:28.3-37.6" *)
  wire [7:0] _000_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:22.3-26.6" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire [3:0] _010_;
  wire [1:0] _011_;
  wire [7:0] _012_;
  wire [3:0] _013_;
  wire [1:0] _014_;
  wire [15:0] _015_;
  wire _016_;
  wire _017_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:24.14-24.29" *)
  wire _018_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)
  wire _019_;
  wire [7:0] _020_;
  wire _021_;
  (* force_downto = 32'd1 *)
  (* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "7" *)
  wire [7:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:287.21-287.22" *)
  wire [7:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:270.26-270.27" *)
  wire [7:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:274.23-274.25" *)
  wire [15:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:287.21-287.22" *)
  wire [15:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:270.26-270.27" *)
  wire [15:0] _027_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _028_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _029_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _030_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _031_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _032_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _033_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _034_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _035_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _036_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _037_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _038_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _039_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)
  wire _040_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _041_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _042_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _043_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)
  wire _044_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _045_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _046_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _047_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)
  wire _048_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:15.9-15.13" *)
  reg flag;
  (* src = "./Up_Down_Counter/UD_cnt.sv:14.16-14.27" *)
  wire [15:0] load_val_ff;
  reg \load_val_ff_reg[0] ;
  (* src = "./Up_Down_Counter/UD_cnt.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \load_val_ff_reg[0]  <= 1'h0;
    else if (load) \load_val_ff_reg[0]  <= load_val[0];
  assign load_val_ff[0] = \load_val_ff_reg[0] ;
  reg \load_val_ff_reg[1] ;
  (* src = "./Up_Down_Counter/UD_cnt.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \load_val_ff_reg[1]  <= 1'h0;
    else if (load) \load_val_ff_reg[1]  <= load_val[1];
  assign load_val_ff[1] = \load_val_ff_reg[1] ;
  reg \load_val_ff_reg[2] ;
  (* src = "./Up_Down_Counter/UD_cnt.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \load_val_ff_reg[2]  <= 1'h0;
    else if (load) \load_val_ff_reg[2]  <= load_val[2];
  assign load_val_ff[2] = \load_val_ff_reg[2] ;
  reg \load_val_ff_reg[3] ;
  (* src = "./Up_Down_Counter/UD_cnt.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \load_val_ff_reg[3]  <= 1'h0;
    else if (load) \load_val_ff_reg[3]  <= load_val[3];
  assign load_val_ff[3] = \load_val_ff_reg[3] ;
  reg \load_val_ff_reg[4] ;
  (* src = "./Up_Down_Counter/UD_cnt.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \load_val_ff_reg[4]  <= 1'h0;
    else if (load) \load_val_ff_reg[4]  <= load_val[4];
  assign load_val_ff[4] = \load_val_ff_reg[4] ;
  reg \load_val_ff_reg[5] ;
  (* src = "./Up_Down_Counter/UD_cnt.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \load_val_ff_reg[5]  <= 1'h0;
    else if (load) \load_val_ff_reg[5]  <= load_val[5];
  assign load_val_ff[5] = \load_val_ff_reg[5] ;
  reg \load_val_ff_reg[6] ;
  (* src = "./Up_Down_Counter/UD_cnt.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \load_val_ff_reg[6]  <= 1'h0;
    else if (load) \load_val_ff_reg[6]  <= load_val[6];
  assign load_val_ff[6] = \load_val_ff_reg[6] ;
  reg \load_val_ff_reg[7] ;
  (* src = "./Up_Down_Counter/UD_cnt.sv:17.3-20.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \load_val_ff_reg[7]  <= 1'h0;
    else if (load) \load_val_ff_reg[7]  <= load_val[7];
  assign load_val_ff[7] = \load_val_ff_reg[7] ;
  (* src = "./Up_Down_Counter/UD_cnt.sv:22.3-26.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) flag <= 1'h0;
    else if (_002_) flag <= _001_;
  (* src = "./Up_Down_Counter/UD_cnt.sv:28.3-37.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[0] <= 1'h0;
    else Cnt[0] <= _000_[0];
  (* src = "./Up_Down_Counter/UD_cnt.sv:28.3-37.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[1] <= 1'h0;
    else Cnt[1] <= _000_[1];
  (* src = "./Up_Down_Counter/UD_cnt.sv:28.3-37.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[2] <= 1'h0;
    else Cnt[2] <= _000_[2];
  (* src = "./Up_Down_Counter/UD_cnt.sv:28.3-37.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[3] <= 1'h0;
    else Cnt[3] <= _000_[3];
  (* src = "./Up_Down_Counter/UD_cnt.sv:28.3-37.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[4] <= 1'h0;
    else Cnt[4] <= _000_[4];
  (* src = "./Up_Down_Counter/UD_cnt.sv:28.3-37.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[5] <= 1'h0;
    else Cnt[5] <= _000_[5];
  (* src = "./Up_Down_Counter/UD_cnt.sv:28.3-37.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[6] <= 1'h0;
    else Cnt[6] <= _000_[6];
  (* src = "./Up_Down_Counter/UD_cnt.sv:28.3-37.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) Cnt[7] <= 1'h0;
    else Cnt[7] <= _000_[7];
  assign _023_[0] = ~Cnt[0];
  assign _026_[1] = ~Cnt[1];
  assign _026_[2] = ~Cnt[2];
  assign _026_[4] = ~Cnt[4];
  assign _026_[5] = ~Cnt[5];
  assign _026_[3] = ~Cnt[3];
  assign _026_[6] = ~Cnt[6];
  assign _026_[7] = ~Cnt[7];
  assign _003_ = ~_024_[7];
  assign _004_ = ~_024_[6];
  assign _005_ = ~_024_[5];
  assign _006_ = ~_024_[4];
  assign _007_ = ~_024_[3];
  assign _008_ = ~_024_[2];
  assign _009_ = ~_024_[1];
  assign _027_[8] = ~_025_[7];
  assign _015_[0] = _023_[0] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  load_val_ff[0];
  assign _015_[1] = _027_[1] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  load_val_ff[1];
  assign _015_[2] = _027_[2] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  load_val_ff[2];
  assign _015_[3] = _027_[3] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  load_val_ff[3];
  assign _015_[4] = _027_[4] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  load_val_ff[4];
  assign _015_[5] = _027_[5] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  load_val_ff[5];
  assign _015_[6] = _027_[6] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  load_val_ff[6];
  assign _015_[7] = _027_[7] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  load_val_ff[7];
  assign _027_[1] = _026_[1] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:296.13-296.25" *)  Cnt[0];
  assign _027_[2] = _026_[2] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:296.13-296.25" *)  _025_[1];
  assign _027_[6] = _026_[6] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:296.13-296.25" *)  _025_[5];
  assign _027_[7] = _026_[7] ^(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:296.13-296.25" *)  _025_[6];
  assign _027_[3] = _026_[3] ^(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:296.13-296.25" *)  _025_[2];
  assign _027_[4] = _026_[4] ^(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:296.13-296.25" *)  _025_[3];
  assign _027_[5] = _026_[5] ^(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:296.13-296.25" *)  _025_[4];
  assign _024_[1] = Cnt[1] ^(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:296.13-296.25" *)  Cnt[0];
  assign _024_[2] = Cnt[2] ^(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:296.13-296.25" *)  _022_[1];
  assign _024_[3] = Cnt[3] ^(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:296.13-296.25" *)  _022_[2];
  assign _024_[4] = Cnt[4] ^(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:296.13-296.25" *)  _022_[3];
  assign _024_[5] = Cnt[5] ^(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:296.13-296.25" *)  _022_[4];
  assign _024_[6] = Cnt[6] ^(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:296.13-296.25" *)  _022_[5];
  assign _024_[7] = Cnt[7] ^(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:296.13-296.25" *)  _022_[6];
  assign _025_[4] = Cnt[4] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _043_;
  assign _025_[2] = Cnt[2] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _042_;
  assign _025_[5] = _046_ |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _041_;
  assign _041_ = _038_ &(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _025_[3];
  assign _025_[6] = Cnt[6] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:248.12-248.41" *)  _044_;
  assign _025_[7] = _048_ |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _036_;
  assign _025_[3] = _045_ |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _034_;
  assign _039_ = _026_[7] &(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _026_[6];
  assign _047_ = Cnt[7] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _033_;
  assign _033_ = _026_[7] &(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[6];
  assign _038_ = _026_[5] &(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _026_[4];
  assign _046_ = Cnt[5] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _032_;
  assign _032_ = _026_[5] &(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[4];
  assign _037_ = _026_[3] &(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _026_[2];
  assign _045_ = Cnt[3] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _031_;
  assign _044_ = _026_[6] &(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _025_[5];
  assign _025_[1] = Cnt[1] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.24|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _030_;
  assign _042_ = _026_[2] &(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _025_[1];
  assign _043_ = _026_[4] &(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _025_[3];
  assign _036_ = _040_ &(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _025_[3];
  assign _040_ = _039_ &(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  _038_;
  assign _048_ = _047_ |(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:293.27-293.63|/share/techmap.v:240.12-240.41" *)  _035_;
  assign _035_ = _039_ &(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _046_;
  assign _034_ = _037_ &(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _025_[1];
  assign _031_ = _026_[3] &(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[2];
  assign _030_ = _026_[1] &(* src = "./Up_Down_Counter/UD_cnt.sv:34.35-34.45|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[0];
  assign _022_[2] = Cnt[2] &(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _022_[1];
  assign _022_[4] = Cnt[4] &(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _022_[3];
  assign _022_[5] = _029_ &(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _022_[3];
  assign _022_[6] = Cnt[6] &(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:293.27-293.63|/share/techmap.v:248.19-248.41" *)  _022_[5];
  assign _022_[3] = _028_ &(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  _022_[1];
  assign _029_ = Cnt[5] &(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[4];
  assign _028_ = Cnt[3] &(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:293.27-293.63|/share/techmap.v:241.12-241.34" *)  Cnt[2];
  assign _022_[1] = Cnt[1] &(* src = "./Up_Down_Counter/UD_cnt.sv:35.19-35.29|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)  Cnt[0];
  assign _002_ = _018_ | _019_;
  assign _010_[0] = Cnt[0] |(* src = "./Up_Down_Counter/UD_cnt.sv:24.14-24.29" *)  _009_;
  assign _010_[1] = _008_ |(* src = "./Up_Down_Counter/UD_cnt.sv:24.14-24.29" *)  _007_;
  assign _010_[2] = _006_ |(* src = "./Up_Down_Counter/UD_cnt.sv:24.14-24.29" *)  _005_;
  assign _010_[3] = _004_ |(* src = "./Up_Down_Counter/UD_cnt.sv:24.14-24.29" *)  _003_;
  assign _011_[0] = _010_[0] |(* src = "./Up_Down_Counter/UD_cnt.sv:24.14-24.29" *)  _010_[1];
  assign _011_[1] = _010_[2] |(* src = "./Up_Down_Counter/UD_cnt.sv:24.14-24.29" *)  _010_[3];
  assign _016_ = _011_[0] |(* src = "./Up_Down_Counter/UD_cnt.sv:24.14-24.29" *)  _011_[1];
  assign _012_[0] = _015_[0] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  _015_[1];
  assign _012_[1] = _015_[2] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  _015_[3];
  assign _012_[2] = _015_[4] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  _015_[5];
  assign _012_[3] = _015_[6] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  _015_[7];
  assign _013_[0] = _012_[0] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  _012_[1];
  assign _013_[1] = _012_[2] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  _012_[3];
  assign _014_[0] = _013_[0] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  _013_[1];
  assign _017_ = _014_[0] |(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *)  _027_[8];
  assign _018_ = ~(* src = "./Up_Down_Counter/UD_cnt.sv:24.14-24.29" *) _016_;
  assign _019_ = ~(* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39" *) _017_;
  assign _020_[1] = flag ? (* src = "./Up_Down_Counter/UD_cnt.sv:34.16-34.26|./Up_Down_Counter/UD_cnt.sv:34.12-35.30" *) _027_[1] : _024_[1];
  assign _020_[2] = flag ? (* src = "./Up_Down_Counter/UD_cnt.sv:34.16-34.26|./Up_Down_Counter/UD_cnt.sv:34.12-35.30" *) _027_[2] : _024_[2];
  assign _020_[3] = flag ? (* src = "./Up_Down_Counter/UD_cnt.sv:34.16-34.26|./Up_Down_Counter/UD_cnt.sv:34.12-35.30" *) _027_[3] : _024_[3];
  assign _020_[4] = flag ? (* src = "./Up_Down_Counter/UD_cnt.sv:34.16-34.26|./Up_Down_Counter/UD_cnt.sv:34.12-35.30" *) _027_[4] : _024_[4];
  assign _020_[5] = flag ? (* src = "./Up_Down_Counter/UD_cnt.sv:34.16-34.26|./Up_Down_Counter/UD_cnt.sv:34.12-35.30" *) _027_[5] : _024_[5];
  assign _020_[6] = flag ? (* src = "./Up_Down_Counter/UD_cnt.sv:34.16-34.26|./Up_Down_Counter/UD_cnt.sv:34.12-35.30" *) _027_[6] : _024_[6];
  assign _020_[7] = flag ? (* src = "./Up_Down_Counter/UD_cnt.sv:34.16-34.26|./Up_Down_Counter/UD_cnt.sv:34.12-35.30" *) _027_[7] : _024_[7];
  assign _000_[0] = load ? (* src = "./Up_Down_Counter/UD_cnt.sv:33.11-33.15|./Up_Down_Counter/UD_cnt.sv:33.7-35.30" *) load_val[0] : _023_[0];
  assign _000_[1] = load ? (* src = "./Up_Down_Counter/UD_cnt.sv:33.11-33.15|./Up_Down_Counter/UD_cnt.sv:33.7-35.30" *) load_val[1] : _020_[1];
  assign _000_[2] = load ? (* src = "./Up_Down_Counter/UD_cnt.sv:33.11-33.15|./Up_Down_Counter/UD_cnt.sv:33.7-35.30" *) load_val[2] : _020_[2];
  assign _000_[3] = load ? (* src = "./Up_Down_Counter/UD_cnt.sv:33.11-33.15|./Up_Down_Counter/UD_cnt.sv:33.7-35.30" *) load_val[3] : _020_[3];
  assign _000_[4] = load ? (* src = "./Up_Down_Counter/UD_cnt.sv:33.11-33.15|./Up_Down_Counter/UD_cnt.sv:33.7-35.30" *) load_val[4] : _020_[4];
  assign _000_[5] = load ? (* src = "./Up_Down_Counter/UD_cnt.sv:33.11-33.15|./Up_Down_Counter/UD_cnt.sv:33.7-35.30" *) load_val[5] : _020_[5];
  assign _000_[6] = load ? (* src = "./Up_Down_Counter/UD_cnt.sv:33.11-33.15|./Up_Down_Counter/UD_cnt.sv:33.7-35.30" *) load_val[6] : _020_[6];
  assign _000_[7] = load ? (* src = "./Up_Down_Counter/UD_cnt.sv:33.11-33.15|./Up_Down_Counter/UD_cnt.sv:33.7-35.30" *) load_val[7] : _020_[7];
  assign _021_ = _017_ ? (* src = "./Up_Down_Counter/UD_cnt.sv:25.14-25.39|./Up_Down_Counter/UD_cnt.sv:25.10-25.51" *) 1'hx : 1'h0;
  assign _001_ = _016_ ? (* src = "./Up_Down_Counter/UD_cnt.sv:24.14-24.29|./Up_Down_Counter/UD_cnt.sv:24.10-25.51" *) _021_ : 1'h1;
  assign { _025_[15:8], _025_[0] } = { _025_[7], _025_[7], _025_[7], _025_[7], _025_[7], _025_[7], _025_[7], _025_[7], Cnt[0] };
  assign { _026_[15:8], _026_[0] } = { 8'hff, Cnt[0] };
  assign _024_[0] = _023_[0];
  assign _014_[1] = _027_[8];
  assign _013_[3:2] = { _027_[8], _027_[8] };
  assign _012_[7:4] = { _027_[8], _027_[8], _027_[8], _027_[8] };
  assign _015_[15:8] = { _027_[8], _027_[8], _027_[8], _027_[8], _027_[8], _027_[8], _027_[8], _027_[8] };
  assign _022_[0] = Cnt[0];
  assign _023_[7:1] = Cnt[7:1];
  assign _020_[0] = _023_[0];
  assign { _027_[15:9], _027_[0] } = { _027_[8], _027_[8], _027_[8], _027_[8], _027_[8], _027_[8], _027_[8], _023_[0] };
  assign load_val_ff[15:8] = 8'h00;
endmodule
